### ISSUE TITLE
< operator value treated as invalid JSX element name

### ISSUE THREAD

**Issue by gandm** [gandm/language-babel#1]
Disabled JSX attribute name highlighting. Shame, but seems impossible to fix unless I attack the whole grammar. Can't see it's worth it so I'm closing.

**Comment by gandm** [comment]
@michaelmcd

I noticed you had some issues on your port of language-babel - issues 10 & 11

If needed the user can override the color of the scopes like this

![image](https://user-images.githubusercontent.com/2313237/31292776-9629ea2c-aacc-11e7-96cb-ebc1f667c7b5.png)
which gives
![image](https://user-images.githubusercontent.com/2313237/31292794-ad0adae4-aacc-11e7-9b46-c7a87214796a.png)

**Comment by michaelgmcd** [comment]
Ah! I didn't know that this kind of overriding was possible. Thanks again @gandm.
