### ISSUE TITLE
Couldn't find preset "stage-0"

### ISSUE THREAD

**Issue by tofagerl** [gandm/language-babel#100]
For some reason stage-0 isn't found or loaded. It is correctly installed and listed in .babelrc. The language-babel options haven't been touched, and using babel in gulp works fine. 

This has no practical effect for me other than an annoying error popup, but there you go...

**Comment by gandm** [comment]
Plugins and presets have to be installed in the Atom path. See my readme which explains how to install plugins and presets within Atom. Babel finds the presets by using the process.cwd() which in Atom isn't a project folder but the atom path.  I would like to do this in a more sensible way but i'm waiting to see what the Atom team are going to do with V6 and how they handle packages using the "use Babel" option.

Dos that help?

**Comment by tofagerl** [comment]
But isn't that just the folder I launch Atom from? Because that's where it is installed.

**Comment by gandm** [comment]
Take a look a language-babel package settings. You will see two fields - plugins and presets - above these is a field description with an indication of the working directory. The preset should  be installed somewhere in that path.

**Comment by tofagerl** [comment]
Apparently my atom path is '/', which won't work. 

Oh well, problem is not in this package - I'll try to change the path. Thanks!

**Comment by gandm** [comment]
@tofagerl I seem you asked about this in the help forum. I have released v2.1.0 that changes how plugins are found in Babel 6. It should solve your problems.

**Comment by tofagerl** [comment]
And so it did! Thanks :)

I still think there's some error in my configuration since the cwd is wrong, but for now it doesn't matter.
