### ISSUE TITLE
The latest version of the editor with language-babel compiles es6 in es6 (babel-core installed)

### ISSUE THREAD

**Issue by dshm** [gandm/language-babel#103]
I did all the instructions .. 
node v4.2.2

**Comment by gandm** [comment]
In Babel V6 the babel-core does nothing - it just takes a js file and pipes it to the output unchanged. Babel now requires plugins and/or presets to do the transformations. Please read http://babeljs.io/blog/2015/10/31/setting-up-babel-6/

**Comment by gandm** [comment]
I will close this issue. Please reopen it if you believe there to be a problem in language-babel.

**Comment by dshm** [comment]
Sorry,I don't understand...
my 
```
class ClassName {
  constructor() {
   let a; 
   const b = 10;
  }
}
```
transpile to 
```
class ClassName {
  constructor() {
    let a;
    const b = 10;
  }
}
//# sourceMappingURL=/home/dshm/www/markup-tools/js.js.map

```
help me please )

**Comment by gandm** [comment]
You can look at this https://github.com/gandm/example-language-babel it is a simple project that gives some examples of how to use .babelrc and .languagebabel configuration files. As I mentioned Babel does nothing without adding plugins or presets. Presets are groups of plugins. If you look at the example project you will see the package.json has dependencies on babel-core and as well as some presets and syntax plugins. It is these presets and plugins that do the syntax checking transpiles. 

Hope that helps.

**Comment by dshm** [comment]
Thanks!

**Comment by jasuperior** [comment]
I know this issue is marked as closed, but i have followed your instruction, and it still seems to transpile to the same code i input... i have babel install globally and locally in my project, with the plugins, and i still cannot get it to work. please help.

**Comment by gandm** [comment]
@jasuperior what does you .babelrc file look like? Have you downloaded the examples project mentioned in my post above?

**Comment by jasuperior** [comment]
Hey, sorry, I've fixed things.... I was confused as to wear to save the .languagebabel and the .babelrc file.  at first it was ignoring them, but it was a typo. my mistake

**Comment by gandm** [comment]
@jasuperior No problem, glad you fixed it. `.babelrc` and `.languagebabel` files are read and merged recursively starting at the directory holding the source file back to the project root directory or, in the case of  `.babelrc`  back to the filesystem's root.
