### ISSUE TITLE
Number detection detects whitespace

### ISSUE THREAD

**Issue by natew** [gandm/language-babel#106]
![image](https://cloud.githubusercontent.com/assets/12100/11058340/12aa88aa-8747-11e5-9cee-606f0e3d076d.png)

This breaks number-dragging plugins and syntax highlighting depending on the theme:

![image](https://cloud.githubusercontent.com/assets/12100/11058375/437bb5a8-8747-11e5-9871-2b00627ef481.png)

**Comment by ncammarata** [comment]
Thank you @gandm for fixing this so quickly. It was really frustrating with a tool we're building that relies on .numeric and your turnaround was incredibly quick!
