### ISSUE TITLE
TAB as indentation

### ISSUE THREAD

**Issue by andrejsm** [gandm/language-babel#111]
I don't see an option in config where I could set tab as an indentation char.
To use Auto Indent I'm forced to spaces which I don't like.

Are there any plans to enable tab option?

**Comment by gandm** [comment]
Unless I have misunderstood you, this is nothing to do with language-babel.

TAB options e.g. hard/soft number of space characters, etc. are not part of the language grammar itself. They are provided by the core of atom. Atom provides these options in the global [settings](https://cloud.githubusercontent.com/assets/38924/10392228/787d4c9c-6e85-11e5-946a-7ee4b2d4b70f.png) page and some additional overrides in each grammar package settings. Each language scope may have individual settings but again these are part of atom core.

**Comment by andrejsm** [comment]
Seems then it's Atom issue. If enabling Auto Indent in this package settings, global settings are ignored.
Will create an issue in Atom repo. Thanks.
