### ISSUE TITLE
Option to specify location of .babelrc

### ISSUE THREAD

**Issue by michaelprescott** [gandm/language-babel#114]
Not really a bug, but I couldn't find where to make a request.

I'm coding my gulpfile.babel.js in ES2015 and there is conflict between what gulp can handle and what I want language-babel to do.  I want language-babel to compile using the systemjs transform; however, when my .babelrc file specifies any plugins Gulp throws errors.

For example:
`System.register(['gulp', 'gulp-task-listing', 'require-dir'], function (_export) {
^
ReferenceError: System is not defined`

This .babelrc fails with gulp:
`{
  "presets": ["es2015"],
  "plugins": [
    "transform-flow-strip-types",
    "transform-class-properties",
    "transform-es2015-modules-systemjs"
  ]
}`

Only this works with gulp:
`{
  "presets": ["es2015"]
}`

Perhaps there is a work-around for the gulp problem; however, I haven't found it.  I figured another solution would be to tell language-babel in the .languagebabel files to use an alternate file for babelrc config.

**Comment by gandm** [comment]
It works for me. i.,e. 

test source file
```jsx
import someJsFile from 'someJsfile';
import someOtherJsFile from 'someOtherJsfile';
var a = "aaa"
```
.babelrc
```json
{
  "presets": ["es2015","react"],
  "plugins": ["transform-es2015-modules-systemjs"]
}
```
gulpfile.js
```jsx
var gulp = require("gulp");
var babel = require("gulp-babel");

gulp.task("default", function () {
  return gulp.src("babel-source/test.js")
  .pipe(babel())
    .pipe(gulp.dest("dist"));
});
```
ouput file from gulp & language-babel
```jsx
'use strict';

System.register(['someJsfile', 'someOtherJsfile'], function (_export) {
  var someJsFile, someOtherJsFile, a;
  return {
    setters: [function (_someJsfile) {
      someJsFile = _someJsfile.default;
    }, function (_someOtherJsfile) {
      someOtherJsFile = _someOtherJsfile.default;
    }],
    execute: function () {
      a = "aaa";
    }
  };
});
```

However, I did notice that if I placed babel options in the `gulpfile.js` then the output was a double wrapped `System.register` which I think is a bug in babel-core. It's as though the syntax plugins are run twice!!!

e.g. gulpfile.js
```jsx
var gulp = require("gulp");
var babel = require("gulp-babel");

gulp.task("default", function () {
  return gulp.src("babel-source/test.js")
  .pipe(babel({
    presets: ['es2015',"react"], plugins: ["transform-es2015-modules-systemjs"] }
  ))
    .pipe(gulp.dest("dist"));
});
```

produces
```jsx
'use strict';

System.register([], function (_export2) {
  return {
    setters: [],
    execute: function () {
      System.register(['someJsfile', 'someOtherJsfile'], function (_export) {
        var someJsFile, someOtherJsFile, a;
        return {
          setters: [function (_someJsfile) {
            someJsFile = _someJsfile.default;
          }, function (_someOtherJsfile) {
            someOtherJsFile = _someOtherJsfile.default;
          }],
          execute: function () {
            a = "aaa";
          }
        };
      });
    }
  };
});
```

**Comment by gandm** [comment]
Reopen if you still believe this to be an issue.
