### ISSUE TITLE
jsx auto-indent

### ISSUE THREAD

**Issue by stopachka** [gandm/language-babel#115]
Hey everyone, big fan of this package.

There is one pet peeve though -- when editing jsx, auto-indent doesn't seem to work. Here's an example ->
![image](https://cloud.githubusercontent.com/assets/984574/11726884/a925226c-9f35-11e5-8b52-5902575d8dea.png)

When pressing enter from `<FooButton`, I expect cursor to align with `className`, but instead, it aligns right under `<`

**Comment by gandm** [comment]
Sorry, I'm unlikely to support this as it's tricky. It can't be done with Atom's Regex based auto intent feature as I can't make distinctions between flow typing polymorphs, comparisons such as 'if x <variable-name', etc.  It could be done in javascript but it isn't trivial and I don't have time. See https://github.com/gandm/language-babel/pull/33 for more info.

**Comment by gandm** [comment]
It is mentioned in the above issue but you might want to try using https://atom.io/packages/react 

It uses it's own jsx grammar in conjunction with the atom provided  language-javascript. People seem to like it.

**Comment by gandm** [comment]
@stopachka fyi I'm near to completing jsx auto indent and automatic reformatting of jsx blocks according to .eslintrc rules in a project. Not sure when I'll release it but should be sometime next week.

**Comment by stopachka** [comment]
Nice! Looking forward to it Graham :)

**Comment by gandm** [comment]
@stopachka Released 2.8.0 that starts to do this. See the readme for some basic info. Any feedback welcome.

**Comment by stopachka** [comment]
nice! great push Graham : )
