### ISSUE TITLE
Closing JSX tags rendering incorrectly

### ISSUE THREAD

**Issue by nathanborror** [gandm/language-babel#116]
Closing JSX tags are all rendering as </> with the tag name showing up in the right margin:
![Image](https://s3.amazonaws.com/f.cl.ly/items/0F3G1y3M0F2b0d1y2P2H/Screen%20Shot%202015-12-22%20at%201.09.32%20PM.png?v=c9ad2097)

**Comment by gandm** [comment]
Works for me 
![image](https://cloud.githubusercontent.com/assets/2313237/11966239/7b80abda-a8f2-11e5-9a29-08e918b5d70b.png)

**Comment by nathanborror** [comment]
I'm running Atom 1.3.2 with the following packages:

```
/Users/nathan/.atom/packages (12)
├── gist-it@0.8.0
├── github-2014@3.13.0
├── go-oracle@0.2.1
├── go-plus@3.5.2
├── language-babel@2.6.2
├── language-css@0.36.0
├── language-swift@0.4.0
├── lepton@0.7.0
├── pretty-json@0.4.1
├── react@0.12.10
├── xml-formatter@0.9.1
└── yosemite-unity-ui@0.3.13
```

**Comment by nathanborror** [comment]
Disabling all packages but language-babel doesn't seem to resolve the problem either.

**Comment by gandm** [comment]
Weird. 1.3.2 here as well.

Does `Babel ES6 JavaScript` display on the bottom status bar?
Any console messages? 
Have you restarted Atom?

**Comment by nathanborror** [comment]
Looks like styles from `/Applications/Atom.app/Contents/Resources/app.asar/static/bootstrap.css` are leaking onto the closing tags `close` class. 
![Example](https://s3.amazonaws.com/f.cl.ly/items/101R3Z1M2U3P1w391T2J/Screen%20Shot%202015-12-22%20at%201.59.19%20PM.png?v=6beeac84)

**Comment by gandm** [comment]
What UI & syntax themes are you using. I thought you were using One Dark as in screen image above and the Styles below. Not sure where bootstrap.css comes into it?
![image](https://cloud.githubusercontent.com/assets/2313237/11967206/d9850a54-a8f8-11e5-91c0-fc83de1f2d9f.png)

**Comment by nathanborror** [comment]
I'm using One Dark. It's not clear to me either but it's showing up above atom.less:
![](https://s3.amazonaws.com/f.cl.ly/items/3W132W012J2r3Q381G0n/Screen%20Shot%202015-12-22%20at%202.19.54%20PM.png?v=67ef4fa2)

**Comment by gandm** [comment]
Oh I think you have the shadow DOM option in Atom's settings turned off like this
![image](https://cloud.githubusercontent.com/assets/2313237/11967427/9ccddfc6-a8fa-11e5-9666-e975f7e0e756.png)
This gives your problem.
It is not recommended turning it off as CSS leaks into the text windows.

**Comment by nathanborror** [comment]
:+1: — that fixed it. Thanks for your help!

**Comment by gandm** [comment]
No problem. Glad it's fixed.
