### ISSUE TITLE
JavaScript function parameters missing .parameter class.

### ISSUE THREAD

**Issue by ramanpreetnara** [gandm/language-babel#117]
The `span` tags generated for parameters in JavaScript functions are missing the `.parameter` class. Just curious if this was by design, or a bug. (Some syntax themes (like [monokai](https://github.com/kevinsawicki/monokai/blob/master/index.less#L174-L177)) depend on that class to uniquely colour function parameters).

### Example
```JavaScript
function stuff(one) {
  return one;
}
```

#### language-babel DOM:
```HTML
<span class="variable other readwrite js">one</span>
```

#### language-javascript DOM:
```HTML
<span class="variable parameter function js">one</span>
```

**Comment by gandm** [comment]
Maybe unhelpful, but it is by design. It is less code and and easier to cope with the typed flow arguments.

**Comment by ramanpreetnara** [comment]
Okay, cool. Thanks for the quick reply!
