### ISSUE TITLE
Spelling error in stylesheet (non-critical)

### ISSUE THREAD

**Issue by dsifford** [gandm/language-babel#118]
The class `primitive` is spelled `primitve` on the stylesheet.

Not sure if this is intentional or not, but it did trip me up for a few minutes until I noticed it.

![image](https://cloud.githubusercontent.com/assets/5240018/12023282/f1376f9a-ad65-11e5-9a1a-3ab31e7c0313.png)

**Comment by gandm** [comment]
Thanks. Will fix.
