### ISSUE TITLE
Commas aren't stylable/tokenized

### ISSUE THREAD

**Issue by nfour** [gandm/language-babel#119]
Currently language-babel is lacking over the base javascript language in at least one way;

```js
someFn(a, b, c);
var fn = (a, b) => { }
someFn2(function(a, b, c) { });
var array = [ a, b, c ];
```

Commas aren't stylable currently. I'd be happy to contribute this fix.

Tried to contrib function-calls fixes to [langauge-javascript](https://github.com/atom/language-javascript/pull/295) but am realizing language-babel is more feature rich.

Thanks.

**Comment by gandm** [comment]
Thanks for the report this should be fixed. Your PR would have worked if you had uses "\\s*," rathjer than ","  in the delimiter regex. But the PR would have stopped the facebook flow syntax parsing.

**Comment by nfour** [comment]
Ah I wasn't sure whether the whitespace capture was significant, thanks.
