### ISSUE TITLE
`new` keyword broken highlighting

### ISSUE THREAD

**Issue by nfour** [gandm/language-babel#123]
```js
new this.is.some.Thing();
```
The above misses tokens for the `.` and `this` keyword due to the `new` keyword being used.

```js
new prop.some['aa'].Thing();
```
The `some` above is given `entity.name.type.new`.

I'd recommend removing new keyword entity scoping in this case or fixing it so that it only ever tries to do it to variables starting with capital letters or something.

**Comment by gandm** [comment]
@nfour I'll take a look asap.

**Comment by gandm** [comment]
For my info - some forms of new
```js
new x(); new new x()();
new x[0](); new x.a(); new x[0].a(); new x.a[0]();
new x; new new x; new new x();
new new x().a; new new x()[0];
class B extends new A {}
```

**Comment by gandm** [comment]
@nfour I've disabled it for now. I may review some other time.

**Comment by dubert** [comment]
Can you tell me the desired behavior? I would be interested in tackling this issue.

**Comment by gandm** [comment]
@dubert there isn't any real desired behaviour, or at least I haven't thought it through. I originally ported the grammar from  Babel-sublime but I've changed big sections of it and added lots new - jsx, flow, etc. This is a hangover from the original code that doesn't seem to do much. It needs to be reviewed at some stage but grammar isn't a fun thing to look at or do 😢

**Comment by dubert** [comment]
This is what I have so far:

Current:
![screen shot 2016-02-01 at 10 30 40](https://cloud.githubusercontent.com/assets/1843672/12721669/e7ed2202-c8ce-11e5-9973-a06572d0fd72.png)


My version:
![screen shot 2016-02-01 at 10 30 09](https://cloud.githubusercontent.com/assets/1843672/12721677/f14e48d0-c8ce-11e5-91ef-2f42d559898e.png)

**Comment by gandm** [comment]
@dubert looks good but I don't know what the colours mean in this theme. Why green 'Thing()' and 'a()' but purple 'x()' and underscore B but not A or Thing?  Will you be doing a PR?
