### ISSUE TITLE
Is there a way to "Preview" the generated javascript?

### ISSUE THREAD

**Issue by kumarharsh** [gandm/language-babel#124]
Hi,

Forgive me if this functionality is already there. I'm new to Atom, and coming from SublimeText, I had a nifty little command called `babel_transform` which I had bound to `ctrl+b`. Whenever I was writing es6 or JSX code, and wanted to see what that code compiled down to, I'd just press the shortcut and Sublime would show me the compiled file (as a temp file) in a new tab. This is super-useful as I can very quickly find bugs or typos in my code.

Does this tool have that functionality? If not, would you consider adding it in?

**Comment by gandm** [comment]
Just added the preview option in 2.12.0. language-babel acts as a  provider to another package - [source-preview](https://atom.io/packages/source-preview) which must be v4.0 or greater.  [source-preview](https://atom.io/packages/source-preview) provides a command `Source Preview Toggle` 0On on the first toggle it activates the program and on subsequent toggles displays a preview window for the current source code. ![extra](https://cloud.githubusercontent.com/assets/2313237/12490818/7535fc50-c06f-11e5-8752-ec0878c5205c.gif)
