### ISSUE TITLE
error reading .eslintrc

### ISSUE THREAD

**Issue by 2c2c** [gandm/language-babel#129]
http://someimage.com/SQQl6m9

began with this update

**Comment by gandm** [comment]
That message is generated by parsing the file using https://github.com/gandm/language-babel/blob/master/lib/auto-indent.coffee#L302 not sure why it can't be parsed as JSON. You have a trailing , on line 24 of your .eslintrc file.

**Comment by gandm** [comment]
P.S. I will be either implementing json5 or use the cli engine from eslint to parse these files. Both will allow comments and trailing , 

Most probably I'll do that this weekend.

**Comment by 2c2c** [comment]
the goofy syntax highlighting I saw when I opened the file threw me off from thinking that was issue

whoops

**Comment by gandm** [comment]
No problem. I'll close this issue for now. Thx.

**Comment by gandm** [comment]
Fyi 2.9.0 now supports json5 so trailing commas should be acceptable.
