### ISSUE TITLE
Having problems with Spread Operator 

### ISSUE THREAD

**Issue by IngenieroLata** [gandm/language-babel#13]
Hi, 
I just came to Atom world from Sublime and I'm trying to compile a .jsx component and when I try to save it always appears this message 

```
Babel v5.6.15 Transpiler Error
/app/components/Lane.jsx: Unexpected token (35:18)
 ```

The line that is  broking

```
const {i, name, ...props} = this.props;
```

Referring the spread operator.

**Comment by gandm** [comment]
This is nothing to do with language-babel. That message is passed back from the Babel API. I would imagine you would also get this message from the Babel CLI. You have to enable the spread transformer es6.spread or set the stage to enable it. Either use the babelrc files or set via settings.

**Comment by gandm** [comment]
spread as a lhs?

**Comment by IngenieroLata** [comment]
I'm using webpack so I just disabled the transpile and that's it, but I'm still wondering about it, I was using a destructuring with "..." to keep the props and with webpack is working well. 

And... Sorry may I ask What is lhs?

**Comment by mathieumg** [comment]
> What is lhs?

Left-hand side

**Comment by gandm** [comment]
The LHS spread should be an array.
e.g
[ a, b, ...c ] = this.props

**Comment by gandm** [comment]
Sorry I misunderstood what you were doing. Yes this should work if the correct stage is set in either babelrc or settings.

**Comment by IngenieroLata** [comment]
ooooo yes, but I'm using destructuring also  https://babeljs.io/docs/learn-es2015/#destructuring  like this

```
bla=>{
  const {a, b, ...props} = this.props;
}
```

**Comment by IngenieroLata** [comment]
yeah, but I don't know where to put it on settings, Just now I think I broke Atom.

**Comment by gandm** [comment]
This is experimental stage 1 or use transformer es7.objectRestSpread https://github.com/sebmarkbage/ecmascript-rest-spread 

You can set this in .babelrc file or  language-babel settings. In language Babel's settings put es7.objectRestSpread in the Optional Transformers field Or use stage 1
In babelrc use stage 1 or use the 'optional' option.

I've never used the webpack loader so I don't know why this works without these settings. I may have a look given time.

**Comment by IngenieroLata** [comment]
Thanks! I'll check it
