### ISSUE TITLE
Support commenting inside JSX

### ISSUE THREAD

**Issue by dubert** [gandm/language-babel#131]
It would be incredible if block commenting inside a render function added the curly brackets. Like so:

```js
render() {
  return (
    <View>
      <MyComponent />
      <MyOtherComponent>
        {/*<Text>asdfasdf</Text>*/}
      </MyOtherComponent>
    </View>
  )
}
```

I'm looking into implementing it myself. If I can figure it out, I can submit a PR.

**Comment by gandm** [comment]
I'll take a look.

**Comment by dubert** [comment]
I just realized that I use the `block-comment` package, and Atom doesn't do them by default.

**Comment by gandm** [comment]
Does this mean you don't want my package to do this?

**Comment by dubert** [comment]
Well, not everyone uses block-comment, so it would be awesome if this package included it. But if you don't think others would use it, you can close the issue.

**Comment by gandm** [comment]
Pushed 2.10.0 Does it work for you?
![gif](https://cloud.githubusercontent.com/assets/2313237/12441752/4d672be6-bf42-11e5-8e20-33a96a81db66.gif)

**Comment by dubert** [comment]
Wow, that's incredible. I just tested it and it works beautifully.

This is just a fantastic addition. :smile_cat:
