### ISSUE TITLE
Disable or configure auto-indent on JSX only

### ISSUE THREAD

**Issue by tschaub** [gandm/language-babel#132]
I've just upgraded to 2.9.3 and am not sure if I am seeing expected auto-indent behavior with JSX (or a bug).

![auto-indent](https://cloud.githubusercontent.com/assets/41094/12403851/1d671d74-bdf4-11e5-91c2-f333e112782f.gif)

Given this code:
```js
var React = require('react');

var TestIndent = React.createClass({

  render: function() {
    return (
      <div
        oneProp="value"
        twoProp="value">
      </div>
    );
  }

});

module.exports = TestIndent;
```

When I add a newline before the closing `</div>`, one level of indentation is removed from the line with the `twoProp` attribute.

I don't have any other React related package installed.  I do use the ESLint `indent` rule with `[2, 2, {"SwitchCase": 1}]` (see [the full config](https://github.com/planetlabs/eslint-config-planet/blob/master/config/base.json) for more).

Let me know if I can provide any other detail on my setup.  If this is expected behavior, I'm curious if it is possible to disable the auto-indenting for JSX only.

Thanks.

**Comment by gandm** [comment]
No it's a bug! You can disable the indenting either globally via the package `Format JSX` option or by a toggle command via the command pallete  and search for Language Babel.

**Comment by gandm** [comment]
Does 2.9.4 fix it for you?

**Comment by tschaub** [comment]
Thanks @gandm!  It looks like 2.9.4 fixes the issue.

This is better for a separate issue, but I'm guessing that this might not play well with people who use the [`jsx-indent-props` rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent-props.md), where JSX prop indentation might differ from the ES indentation.

**Comment by gandm** [comment]
@tschaub The readme explains all but it works with the following rules and their various options. The only one I don't re-format is the Closing bracket variations that would mean inserting or removing a  a new line. I could do it, but it may be too aggressive. i.e. I only indent at the moment. Also, I don't use the normal indent rule at all.
```json
{
  "rules": {
    "react/jsx-closing-bracket-location": 1,
    "react/jsx-indent-props": 1,
    "react/jsx-indent": 1,
  }
}```

**Comment by tschaub** [comment]
Thanks for the additional detail @gandm.  I'll give the latest a try with the `jsx-indent-props` rule.
