### ISSUE TITLE
JSX inside of a `return ( ... )` causes the trailing `)` to indent

### ISSUE THREAD

**Issue by ryancole** [gandm/language-babel#136]
I don't believe that this used to happen in prior versions, but I just started noticing it within the past few days. Whenever typing a block of code such as ...

```
return (

);
```

and then coming back to put in some JSX, to make it like ...

```
return (
  <div>
  </div<
);
```

causes the trailing `)` to end up indenting and looking like ...

```
return (
  <div>
  </div>
  );
```

Not sure if this is related to #128 or not? I don't have a `react` package installed, so I don't think it is.

**Comment by gandm** [comment]
@ryancole Should be OK now.

**Comment by ryancole** [comment]
Yup, works great. Thanks!
