### ISSUE TITLE
Reformatting code incorrectly, and often.

### ISSUE THREAD

**Issue by brandondurham** [gandm/language-babel#139]
This package recently started reformatting my code incorrectly while I type, and often. I’ve gone through and disabled every package one-at-a-time to track it down to this one.

Here is a short video illustrating the issue: http://cloud.smallparade.com/eu0y

Typically only happens when hitting “Enter” in the file. Suggestions on ways to work around this?

**Comment by gandm** [comment]
Language-babel attempts to indent jsx according to eslint rules. It is still a work in progress but is described [here](https://github.com/gandm/language-babel/blob/master/README.md#automatic-indenting-of-jsx). You can turn off this either using a command toggle or by setting the auto indent jsx option in the package settings and reopening any files.

**Comment by brandondurham** [comment]
Oh, thank you, Graham. Appreciate the super fast response. Disabled!
