### ISSUE TITLE
Odd indentation for object/maps

### ISSUE THREAD

**Issue by N0hbdy** [gandm/language-babel#14]
Just wanted to bring this up, but when using the babel plugin the indentation gets a bit off with text-to-cursor location.  This is mostly problematic with maps, where keys that have no quotes around them cause the cursor to be a few characters behind where is should be:
![screen shot 2015-06-29 at 2 18 00 pm](https://cloud.githubusercontent.com/assets/760906/8418726/e88562a2-1e69-11e5-897c-59097ae75f3c.png)

The cursor (in the above image) is between the last double quote, but if I start typing characters appear after the comma.

If this is something that only i'm experiencing, let me know, but I'm only able to get it to work with the Babel plugin (but not the normal JS or JSX plugin).  Also free to give any other info you might need!

**Comment by gandm** [comment]
I can't see this when I display a map. The gif you enclosed seems weird as it has different font sizes? language babel does no styling of syntax other than italicizing names in JSX tags. What theme are you using for the editor? I'm using Atom Dark in the image here.
![image](https://cloud.githubusercontent.com/assets/2313237/8419750/22a2fde2-1eb4-11e5-82f8-dd0bf0e6a080.png)

It maybe your theme is styling certain scope names.

The map key is styled with these scopes 
![image](https://cloud.githubusercontent.com/assets/2313237/8419780/81762f38-1eb4-11e5-9416-1a2abb3f3f47.png)
and the scope at the start of "Virtual" is 
![image](https://cloud.githubusercontent.com/assets/2313237/8419793/9e5e6746-1eb4-11e5-96e8-4f60cd3eae42.png)

**Comment by gandm** [comment]
P.S. 

There are quite a few reports on cursors not being where they should be in atom which is why the devs are working on a new char measurement system https://github.com/atom/atom/issues/6055 

I'm guessing that it is because of the different size fonts being used in your theme.

**Comment by N0hbdy** [comment]
Awesome - thanks for taking a look and helping me out, even though its not Babel's fault!  I'm able to have this not happen on a fresh install, so it must be some other package or setting thats causing the oddity - really appreciate your time to help explain!
