### ISSUE TITLE
JSX closing tags appear on the other side of the window.

### ISSUE THREAD

**Issue by danpantry** [gandm/language-babel#141]
[Demo](https://i.imgur.com/Fde66q6.png). See how the closing tag for form is appearing on the right side of the Atom window. This occurs with every tag.

Atom version is 1.2.4, and I'm using the latest version of `language-babel` on apm, which I believe is 2.15.0.

**Comment by gandm** [comment]
It looks as though you have `Use Shadow DOM` turned off in the main Atom settings. THis is recommended to be on as styles from the parent CSS leaks into the themes for the editor page.
![image](https://cloud.githubusercontent.com/assets/2313237/12695849/303fecd4-c752-11e5-9d2d-bac679b3ac3c.png)

**Comment by danpantry** [comment]
Thanks. I'll give it a shot when I am back on my Linux partition. I was having issues before due to nvidia drivers, but I've since fixed those issues, so I might be able to switch this back on.

**Comment by danpantry** [comment]
Thanks, this solved the issue.
