### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by colinmeinke** [gandm/language-babel#148]
I'm using https://github.com/atom/highlights away from atom and it would be cool to pull in this dependency from npm, rather than from github.

**Comment by gandm** [comment]
Does `npm install git://github.com/gandm/language-babel` not do it for you? 

I know this also loads in redundant modules and you just need the grammar but it uses non atom loading.

**Comment by colinmeinke** [comment]
Yeah it totally works installing from git, that's what I'm doing https://github.com/colinmeinke/colinmeinke/blob/master/package.json#L20... it would just be nice to have it on npm :smiley:

**Comment by gandm** [comment]
Sorry, but I'm not sure it is worthwhile as:-

- I can't any benefit in using npmjs over just installing from github in this case? 
- The package has more than just grammar and isn't really suitable for npmjs and just pollutes it.
- It means I would have to publish the package twice.
