### ISSUE TITLE
Add option "Disable when no .babelrc file in path"

### ISSUE THREAD

**Issue by louisremi** [gandm/language-babel#15]
Most linters I use have this option, which avoids having the plugin run in all projects which contain JS files.

**Comment by gandm** [comment]
The plugin only runs when js files are in the `Babel Source Path` directory within a project directory. Isn't this good enough? If I do this then I have to traverse all the paths from source back to root looking for `.babelrc` files on every save.

**Comment by louisremi** [comment]
I'm not sure how other plugin creators have optimized their plugin to avoid frequent lookups. But having to modify settings to ignore or include all my present and future project isn't manageable.
.babelrc detection is much more convenient.

**Comment by gandm** [comment]
Well I can't cache it as the editor may be open for long periods. I could easily put this in but I have to think about it. 

You can add ignore/only regex or globs to `.babelrc` and this would do it. It is also standard babel practice. Any good?

What linters check for .babelrc?

**Comment by louisremi** [comment]
Creating a .babelrc in a project where I don't use es6 just so that the plugins ignore everything isn't convenient either.
Here's what linter-eslint package is doing: https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L52

**Comment by gandm** [comment]
Ok. They don't seem to check for babelrc, only the linter config file. I have meant to put a language-babel JSON config  file  that would be read from the project root that overrides the global language Babel settings. This would help. E.g. transpile on save could be overridden per project but the grammar is still active.

My other concern is js files that use Babel register and provide transpile options there. 

Maybe I'll put a flag in that checks for babelrc as well as providing a project JSON file for project config settings.

**Comment by gandm** [comment]
Just published 0.9.0. which has a new flag that suppresses transpile if no `.babelrc` is in any directory along source path.

**Comment by louisremi** [comment]
\o/ Yay you!

**Comment by gandm** [comment]
Yeah but I just screwed the deprecation of some unused configs. Will have to pub another release!
