### ISSUE TITLE
JSX closing 'element' tags - styling bug

### ISSUE THREAD

**Issue by InSuperposition** [gandm/language-babel#151]
I'm experiencing the following issue with the JSX closing tags. It appears to only happen when I use Babel ES6 Highlighting.

<img width="1440" alt="fullscreen_3_5_16__3_16_pm" src="https://cloud.githubusercontent.com/assets/433871/13550521/714cb672-e2e5-11e5-8a36-ab631b25263c.png">

**Comment by gandm** [comment]
See https://github.com/gandm/language-babel/issues/141 it's most likely a problem with your atom setup.

**Comment by InSuperposition** [comment]
Thanks, after enabling SHadow DOM and a restart, it now works correctly. Its interesting that Atom advises to disable the feature if you are having a styling issue, yet that is what caused my issue. :)

**Comment by gandm** [comment]
Only disable if you have issues with old packages that were prior to shadow dom support. New packages should have it ticked.
