### ISSUE TITLE
Highlighting the string

### ISSUE THREAD

**Issue by vmakhaev** [gandm/language-babel#152]
Why `string` is highlighted? What makes it different from `array` or `number`?
![screen shot 2016-03-10 at 21 10 40](https://cloud.githubusercontent.com/assets/964688/13679469/f1febd4c-e704-11e5-960e-37055070e96d.png)

**Comment by gandm** [comment]
string is being incorrectly scoped as a node support type. I'll fix this.

**Comment by gandm** [comment]
@vmakhaev  Should be fixed in 2.15.6

**Comment by vmakhaev** [comment]
Cool, thanks
