### ISSUE TITLE
Incorrect JSX auto-formatting inside curly braces

### ISSUE THREAD

**Issue by kjendrzyca** [gandm/language-babel#153]
The problem:
![jsx-indentation-problem](https://cloud.githubusercontent.com/assets/7491025/13730333/9f6d21c8-e94c-11e5-8329-2d116111a967.gif)

it's event more interesting when I use tenary operator:
![jsx-indentation-problem-2](https://cloud.githubusercontent.com/assets/7491025/13730338/adec206e-e94c-11e5-9a1e-89e0c3bb3c38.png)

my .eslintrc config (migrated to 2.0, but there might be some errors):
https://gist.github.com/kjendrzyca/7e59803494a4955919b2

atom settings:
```cson
"*":
  "atom-ternjs": {}
  "autocomplete-plus": {}
  core:
    themes: [
      "one-dark-ui"
      "oceanic-next"
    ]
  editor:
    invisibles:
      cr: false
      eol: false
    preferredLineLength: 100
    showIndentGuide: true
    showInvisibles: true
    tabLength: 4
    tabType: "soft"
  emmet: {}
  "language-babel":
    autoIndentJSX: true
  linter: {}
  "linter-eslint":
    useGlobalEslint: true
  "one-dark-ui": {}
  "status-bar": {}
".babel.regexp.source":
  editor:
    preferredLineLength: 100
".js.jsx.source":
  editor:
    autoIndent: true
    preferredLineLength: 100
    tabLength: 2
```

I'm using latest versions of all packages, eslint and eslint-react-plugin.

I'm also using auto-detect-indentation package but disabling it and setting tab-size to 2 spaces doesn't fix this problem.

I think I've tried all combinations of formatting (with and without parenthesis also) but cannot make it work.

**Comment by gandm** [comment]
I'll take a look. You'll have to disable auto indent jsx at the moment.

**Comment by gandm** [comment]
@kjendrzyca Can you try 2.15.7. Problems with the ternary operator may be different so please raise another issue as appropriate.

**Comment by kjendrzyca** [comment]
It's better in 2.15.7, props indent is correct, but there is no auto-indent for the whole element:

![jsx-indentation-problem-3](https://cloud.githubusercontent.com/assets/7491025/13737690/868d911a-e9bf-11e5-848e-3625e992ad68.gif)

I'll create new issue for tenary operator.

**Comment by gandm** [comment]
@kjendrzyca Can you try 2.15.8

**Comment by kjendrzyca** [comment]
fixed! thanks for quick fix :)
