### ISSUE TITLE
Incorrect JSX auto-formatting when using tenary operator

### ISSUE THREAD

**Issue by kjendrzyca** [gandm/language-babel#154]
In version 2.15.6:
![jsx-indentation-problem-2](https://cloud.githubusercontent.com/assets/7491025/13737754/03df2d7c-e9c0-11e5-8b15-00f968d6ba0c.png)

and in 2.15.7:
![image](https://cloud.githubusercontent.com/assets/7491025/13737792/43004496-e9c0-11e5-977c-112c16b289d4.png)

my .eslintrc config (migrated to 2.0, but there might be some errors):
https://gist.github.com/kjendrzyca/7e59803494a4955919b2

atom settings:
```cson
"*":
  "atom-ternjs": {}
  "autocomplete-plus": {}
  core:
    themes: [
      "one-dark-ui"
      "oceanic-next"
    ]
  editor:
    invisibles:
      cr: false
      eol: false
    preferredLineLength: 100
    showIndentGuide: true
    showInvisibles: true
    tabLength: 4
    tabType: "soft"
  emmet: {}
  "language-babel":
    autoIndentJSX: true
  linter: {}
  "linter-eslint":
    useGlobalEslint: true
  "one-dark-ui": {}
  "status-bar": {}
".babel.regexp.source":
  editor:
    preferredLineLength: 100
".js.jsx.source":
  editor:
    autoIndent: true
    preferredLineLength: 100
    tabLength: 2
```

**Comment by gandm** [comment]
@kjendrzyca Can you try 2.15.8

**Comment by kjendrzyca** [comment]
fixed!
