### ISSUE TITLE
can't turn off auto indent

### ISSUE THREAD

**Issue by DexterHaslem** [gandm/language-babel#155]
my .eslintrc doesn't have any "indent" or any react indent rules and I have "Auto Indent" and "Indent on Paste" off and restarted atom. However the package keeps indenting JSX as soon as my cursor crosses it. Is there some way to see what is triggering indentation in a file? I disabled all linters as well

**Comment by gandm** [comment]
There is a language-babel package setting autoindentjsx which turns it off for all files, or a command palette key to toggle it.
________________________________

**Comment by DexterHaslem** [comment]
well that is the source of my confusion, autoindentjsx is off. I'll dig in and try to get some specifics

**Comment by gandm** [comment]
@DexterHaslem if autoindentjsx is off then any files opened will not be auto indented so I'm not sure what is indenting your jsx.  The line that instantiates the indent feature is here https://github.com/gandm/language-babel/blob/master/lib/main.coffee#L27
