### ISSUE TITLE
Clear the error notifications upon successful transpilation.

### ISSUE THREAD

**Issue by vramana** [gandm/language-babel#16]

**Comment by gandm** [comment]
Not sure I understand the issue.

**Comment by vramana** [comment]
The error notifications that I get when have some wrong code don't go away after I fix them. I have to click on the close button to close them. I am hoping if my code transpiles successfully then those error messages can be closed automatically since they are no longer probably relevant.

**Comment by chrishiestand** [comment]
Thanks for this improvement.
