### ISSUE TITLE
Compile all files

### ISSUE THREAD

**Issue by tomitrescak** [gandm/language-babel#160]
Hi, is it possible to compile all files in the given project root directory?
 Thanks

**Comment by gandm** [comment]
@tomitrescak  Not sure exactly what you mean. What is the intent? I could add a context menu to the tree view to compile files in that directory.

**Comment by tomitrescak** [comment]
That would be fantastic .. build all files in the selected directory.

**Comment by gandm** [comment]
@tomitrescak Just released 2.17.0 that has a context menu for directories to allow files to be transpiled.
