### ISSUE TITLE
Regression in TODO highlighting.

### ISSUE THREAD

**Issue by phyllisstein** [gandm/language-babel#161]
Hey there! Looks like #37 is rearing its ugly head again. `TODO` comments aren't being caught by the built-in grammar when using this package. I'm enclosing screenshots of the default JavaScript grammar and this one, with the Web Inspector toggled in case that's useful. Happy to provide any information that'd help debug this! Thanks for looking into it.

![screen shot 2](https://cloud.githubusercontent.com/assets/2207980/14332236/8341c7ba-fc16-11e5-9a0b-27b91a640eca.png)

![screen shot 3](https://cloud.githubusercontent.com/assets/2207980/14332239/8574e42c-fc16-11e5-8de2-3b9e8324a684.png)

**Comment by gandm** [comment]
Thanks for the report. Yes it's a regression. I'll fix and push out a new release.

**Comment by patrick-boatner** [comment]
I believe this issue is occurring again. I'm using Atom version 1.32.1, language-babel version 2.85.0, and One Dark syntax theme (if that matters).
