### ISSUE TITLE
Indenting issue with jsx files

### ISSUE THREAD

**Issue by MiracleBlue** [gandm/language-babel#163]
I've got a bit of an indenting issue with jsx files when using the Babel ES6 JavaScript file type.  When making a new line within an element block, the indenting falls back by one each new line.  Example:

<img width="296" alt="screen shot 2016-04-14 at 7 40 33 am" src="https://cloud.githubusercontent.com/assets/23368/14510364/719dddd8-0214-11e6-8f12-3f52cabcde2a.png">

language-babel version: 2.17.1
Atom version: 1.6.2

**Comment by MiracleBlue** [comment]
Updating to 1.7.0 this morning seems to have fixed the issue.

**Comment by gandm** [comment]
I can't recreate this on atom 1.6.2 & language-babel 2.17.1. Maybe Atom was in the process of auto-updating and this caused the issue?  I'll leave open for a few days and see if anyone else experiences this.

**Comment by MiracleBlue** [comment]
That's entirely possible, in fact I think I noticed it only start happening at a certain point in the day when it had been working just fine prior, and that then made me try the update.
