### ISSUE TITLE
flow comment syntax breaks highlighting

### ISSUE THREAD

**Issue by despairblue** [gandm/language-babel#164]
A picture is better than... 😃 

![screen shot 2016-04-14 at 17 02 05](https://cloud.githubusercontent.com/assets/927609/14532884/f0e07058-0262-11e6-9301-5ac1191b69a3.png)

**Comment by gandm** [comment]
Should be fixed in 2.17.2

**Comment by despairblue** [comment]
It is. Awesome. Thanks!
