### ISSUE TITLE
Unrecognized char is being shown for jsx sintax.

### ISSUE THREAD

**Issue by luiz-pereira-movile** [gandm/language-babel#165]
After atom updating to 1.7.1 and language-babel to 2.17.2 I've noticed I small but annoying bug.

![screen shot 2016-04-15 at 9 54 16 am](https://cloud.githubusercontent.com/assets/12236202/14561922/1c3c1b7a-02f0-11e6-83cf-ef3d0bb60cbf.png)

Every file with jsx has this error sign on the first line of the jsx sintax. But I'm able to transpile without errors.

My .babelrc file looks like this:

```
{
  "presets": ["es2015"],
  "plugins": ["transform-flow-strip-types", "transform-react-jsx"]
}
```

**Comment by gandm** [comment]
I have no idea where this comes from. language-babel doesn't put anything in the margins/gutter so I presume it is another package or something native in Atom.

**Comment by luiz-pereira-movile** [comment]
Any ideas of where I should start looking for what is causing that?

**Comment by gandm** [comment]
Does hovering over or clicking the icon do anything? Maybe using the Chrome inspector and investigating that element would give you a clue as to it's origin. Do you have a list of packages you have installed? You could disable packages one by one until the offending one shows itself.

**Comment by luiz-pereira-movile** [comment]
I found it!

It was the refactor module! Thanks a lot for your help.
