### ISSUE TITLE
backtick content highlighting in SolarizedDark

### ISSUE THREAD

**Issue by dasilvacontin** [gandm/language-babel#167]
Shouldn't backtick + their content be highlighted in a similar way to a string, or at least with a different-than-default color?
<img width="532" alt="screenshot 2016-04-20 16 35 53" src="https://cloud.githubusercontent.com/assets/1260830/14678482/1da5239c-0716-11e6-99f6-75f64bf64883.png">

**Comment by gandm** [comment]
It depends on your theme - what theme is that? I scope a template string as `string.quasi.js` and a string as `string.quoted.double.js`. The default Atom langauge-javascript pacakge scopes as `string.quoted.template.js` and a string as `string.quoted.double.js`

I guess I could change my scope names but it appears to work OK in most themes. Additionally, there are several themes customised to my package and I don't know if they use my scopes specifically. My scopes in various themes:-
One Dark 
![image](https://cloud.githubusercontent.com/assets/2313237/14680432/358ee318-0715-11e6-8502-6e52588e1d97.png)
Atom Dark
![image](https://cloud.githubusercontent.com/assets/2313237/14680459/4a04fce2-0715-11e6-9ceb-25185d3b30a3.png)
Material
![image](https://cloud.githubusercontent.com/assets/2313237/14680490/5e369874-0715-11e6-9111-1ed352690ee2.png)
Monokai Phoenix
![image](https://cloud.githubusercontent.com/assets/2313237/14680510/7597ced4-0715-11e6-9b0c-c4f11bedab9a.png)
Visual Studio Dark
![image](https://cloud.githubusercontent.com/assets/2313237/14680525/867c53e6-0715-11e6-92ce-da9f2c716655.png)

**Comment by dasilvacontin** [comment]
I'm using Solarized Dark, and it doesn't work with it. I don't have a strong preference, so if it's too much of a hassle I can just pick another theme. Thanks for the response!

**Comment by gandm** [comment]
Yeah looking at the styles for solarized dark it appears that the author doesn't support a straight forward style of `string`. Maybe he would be amenable to a PR or I could use two classes for the quasi. I can check but before I do I noticed you aren't using semi's to terminate statements. If you are using flow typing this may be an issue and I'd probably recommend finding another grammar. See open issue 46 for more info.

**Comment by dasilvacontin** [comment]
Works, thanks @gandm! :)

**Comment by gandm** [comment]
@dasilvacontin thanks. FYI version ^2.18.0 I also support inline flow typing with ASI files. No more semi-colons.

**Comment by dasilvacontin** [comment]
@gandm Oh, that's huge, kudos! 🙌 (and thanks for letting me know)
