### ISSUE TITLE
Regression; async token

### ISSUE THREAD

**Issue by nfour** [gandm/language-babel#168]
```js
let obj = { a: () => async () => 1 }
```

In this example `async` has a scope of  `entity name function method js` instead of the `storage type js`

**Comment by prescottprue** [comment]
+1 for async support in general

Below are some examples of async implementations I have found to not work

```javascript
// Methods on objects
let something = {
  someAsyncMethod: async function (user) { },
  someOtherMethod: async (user) => { },
}
```
```javascript
// lets, consts, and exports
let exportedThing = async () => false
const exportedThing = async () => false
export const exportedThing = async () => false
```

**Comment by nfour** [comment]
@prescottprue all of your examples are fixed and do indeed highlight for me. Check your syntax theme.

**Comment by gandm** [comment]
@nfour Just pushed 2.18.1 that should fix your issue.

@prescottprue I can't see any issues with the examples you provided? Are you sure you have langauge-babel as the grammar for the file you are checking?

**Comment by gandm** [comment]
@prescottprue I'm going to close this. async functions have been supported since the beginning. If you are sure that you are using language-babel and it gets an error, or maybe I've misunderstood the issue please open another. Thx.
