### ISSUE TITLE
Support for method shorthand

### ISSUE THREAD

**Issue by glortho** [gandm/language-babel#170]
Greetings! Thanks for the hard work on this great extension.

I've noticed, however, that es2015 method shorthand gets treated as `meta.function-call`. for example:

```
const obj = {
  myMethod() { // <-- this gets meta.function-call where i would expect meta.function
    //
  }
}
```
Is this by design?

**Comment by gandm** [comment]
Doesn't appear to do that for me?
![image](https://cloud.githubusercontent.com/assets/2313237/14898091/f9c75ef0-0d7c-11e6-9a3f-d6d0b0937fd2.png)

**Comment by gandm** [comment]
I think you would have got the bad scopes on versions of language-babel prior to 2.17.3. Maybe you are running an older version?

**Comment by glortho** [comment]
Ah sorry I gave the wrong example. It's when inside another function-call:
```
foo({ // <-- function-call (correct)
  bar() {} // <-- function-call (incorrect)
})
```
Do you show the same on your side?

**Comment by glortho** [comment]
Ah sorry I gave the wrong example. It's when inside another function-call:
```
foo({ // <-- function-call (correct)
  bar() {} // <-- function-call (incorrect)
})
```
Do you show the same on your side?

**Comment by gandm** [comment]
I haven't tested this but I can envisage how this happens. I'll look at it and push out a fix asap. Probably tomorrow. Hope it doesn't break anything for you.

**Comment by glortho** [comment]
Okay many thanks @gandm !

**Comment by glortho** [comment]
My example above is fixed but I think there is now an additional issue:
```javascript
const foo = {
  bar() {} // <-- bar gets .function.method > .name.function.method
};

const foo = {
  bar: baz() // <-- baz also gets .function.method > .name.function.method
};
```
It seems like `baz` should get `.function-call > .name.function`. Do you agree?

**Comment by gandm** [comment]
Yes totally agree. Try 2.20.6.

**Comment by glortho** [comment]
Fixed! Many thx @gandm
