### ISSUE TITLE
Missing highlight on async functions when returning objects

### ISSUE THREAD

**Issue by Alaneor** [gandm/language-babel#171]
I have found some cases where the `async` keyword is not highlighted properly, attaching code snippet - please see the comments inline.

```js
function getObject() {  
  return {
    // No async highlight for function shorthands
    async doStuff() {},
    // No async highlight for function declarations
    doOtherStuff: async doOtherStuff() {},
    // async is highlighted properly for function expressions
    doDifferent: async function() {}
    // async is highlighted properly for arrow function expressions
    doElse: async () => {}
  }
}
```

Changing `return` to an assignment (`const obj = { ...`) fixes the highlight for the `async` keyword.

I am attaching a screenshot from my editor for brevity, since github shows the highlights properly for the snippet above, which might be confusing. 😄

![missing highlights for async](https://cloud.githubusercontent.com/assets/3058150/14919726/6c0e7270-0e2a-11e6-85f2-d3e5c817f907.png)

Here is a screenshot of what happens when I change the return to an assignment:

![working highlights for async](https://cloud.githubusercontent.com/assets/3058150/14919750/8e31217c-0e2a-11e6-8209-a1860bcfcb1a.png)

**Comment by gandm** [comment]
Thanks for reporting this. Should be fixed now.

**Comment by Alaneor** [comment]
That was fast! Tested and all good now. Thanks!
