### ISSUE TITLE
type keyword highlighting

### ISSUE THREAD

**Issue by kamek-pf** [gandm/language-babel#172]
Hey,
Looks like `type` always gets highlighted now, no matter where it is.
![type](https://cloud.githubusercontent.com/assets/3883992/14940162/d49220d2-0f36-11e6-8ec6-0fdb6bb724ce.png)

Is this the intended behavior ?

**Comment by gandm** [comment]
@kamek-pf Thanks for reporting this. No it isn't the intended behaviour and the moral is, double check global replaces. I'll fix this and push out.
