### ISSUE TITLE
Custom components in different color (enhancement)

### ISSUE THREAD

**Issue by hex13** [gandm/language-babel#173]
Would it be possible to highlight custom JSX components (which are starting either with upper-case or have dots in itself like this `<this.props.component />`) in different color that common DOM elements (lower-case)?  

In other words instead of this:

![image](https://cloud.githubusercontent.com/assets/3883359/14953425/b3ceb8fe-1069-11e6-809f-2dd9d319c1ce.png)

I would like to see this (changed via dev tools):
![image](https://cloud.githubusercontent.com/assets/3883359/14953387/4e220cea-1069-11e6-9d38-5e34951c9295.png)

Being able to see instantly where custom elements are will make me easier to read and change JSX templates.

**Comment by gandm** [comment]
@hex13 Yes seems like a good idea for obvious components beginning `<Component>`  but I'm not sure about `<props.component>` as it's not a pattern I see frequently used and I guess the component in this case could be an html element?  Do you have any examples of this?

**Comment by hex13** [comment]
https://facebook.github.io/react/docs/jsx-in-depth.html
![image](https://cloud.githubusercontent.com/assets/3883359/14957942/51101f54-1088-11e6-863c-17f5af4fa2c2.png)

I'm using this pattern to make Higher Order Components.

In docs namespaced components are also uppercase, but they do work lowercase:
https://jsfiddle.net/69z2wepo/40609/

**Comment by gandm** [comment]
Thanks. Yes I understand the principle but I would still think that a custom component should have an uppercase component name prefix. I appreciate that the compiler will convert tag names with dots to a create element with that tag name as a variable name but it seems at odds with the conventions of jsx. Maybe I'm wrong but the examples above show this uppercase convention.

I have no control over the colour of an element. I have modified the grammar to highlight uppercase component names as a class. This will work with most syntax themes as they will highlight classes in a distinct colour. But I'm not sure whether to further modify it to highlight dotted tag names as classes before rolling it out.

**Comment by hex13** [comment]
Ok, at least support for upper cased tags would be good :)

**Comment by gandm** [comment]
I've just pushed out 2.19.0. It highlights jsx such as `<Component>` and `<this.dottedname.component>` as classes.

**Comment by hex13** [comment]
thanks 👍
