### ISSUE TITLE
Invalid highlighting in ternary operator in JSX

### ISSUE THREAD

**Issue by roman01la** [gandm/language-babel#174]
Highlighting seems to be broken when ternary operator has `null` or `undefined` as the first operand and arrow function or usual function declaration as the second operand.

```js
<button onClick={disabled ? null : () => onClick(val)}>Click me!</button>
```

Highlighting gets wrong after the closing JSX tag of a node which has ternary operator.

**Comment by gandm** [comment]
It's actually the arrow func that's causing this not the null. This is being parsed as a key/value `null: () => onClick(val)` and the ternary never see's the `:` This is quite difficult to isolate using just regex. I'll take a look. Thanks

**Comment by gandm** [comment]
Hopefully it fixes your issue.

**Comment by roman01la** [comment]
@gandm Thanks, it works now. But I also mentioned that usual function declaration `function() {}` instead of arrow function also breaks highlighting. This is still presented.

<img width="731" alt="screen shot 2016-05-03 at 9 26 24 pm" src="https://cloud.githubusercontent.com/assets/1355501/14993932/e712edea-1175-11e6-92a2-b4abfde2c980.png">
<img width="747" alt="screen shot 2016-05-03 at 9 26 07 pm" src="https://cloud.githubusercontent.com/assets/1355501/14993933/e8e3617c-1175-11e6-9c47-13003f627fdc.png">

**Comment by gandm** [comment]
@roman01la Yeah I realised that some more patterns needed a regex prefix. I've just running the specs for these now and if clean will publish soon.

**Comment by gandm** [comment]
@roman01la Just pushed 2.19.3. Should fix the above + other issues.when using ternary's.
