### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by taulatin** [gandm/language-babel#175]
**Hello!**

**I've installed plugin to ATOM editor. I tried to save my *.JSX file and got this error message:**

<%DIRECTORY%>/js/vvt_datatable/test.jsx: Unexpected token (99:7)
 
Using babel-core at
C:\Users\<%USER%>\.atom\packages\language-babel\node_modules\babel-core\index.js
 
   97 | 	    //console.log(this.props.data.url);
   98 | 	    return (
>  99 | 	      <table id={this.state.table_id} className="vvt_table_class">
      | 	      ^
  100 | 	        <thead>
  101 | 	          {this.getHeader()}
  102 | 	          {this.getCustomFilterHeader()}

**It looks like that BABELJS doesn't have some REACTJS plugins or something. But, how I understood from the documentation it should work from the box.**

**Comment by gandm** [comment]
No it only provides a core Babel 6 out of the box. As plugins (and babel core ) are now recommended to be provided on a project by project basis I don't provide any plugins; in fact it would be almost impossible. If a project has plugins mentioned in it's package.json or .babelrc files and the modules are in the projects node_modules folder then I will find them and use them. 

This is mentioned in my readme.md 

> In a Babel project we expect to see one or more  .babelrc  files, a  node_modules  folder at the root of the project containing an optional  babel-core  and other babel plugins/presets as determined by the project's  package.json  file. In addition we may expect to see one or more  .languagebabel  files in the project. Projects are either implicit (an Atom project folder) or explicit (denoted by a  .languagebabel  property of  "projectRoot": true ). If no  babel-core  is found in the project then a version will be provided by the package but this will be a Babel Version 6 instance. Plugins and presets will not be provided by the package.

I follow the guidelines in the Babel 6 User Handbook here https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md

**Comment by gandm** [comment]
@taulatin you might also want to look at https://github.com/gandm/example-language-babel It is not a real project but shows how one might wet one up. It's pretty standard Babel but adds .languagebabel files to  control where and if files are directed to.

**Comment by taulatin** [comment]
https://github.com/gandm/example-language-babel
has the same error on my computer.

**Comment by taulatin** [comment]
May be anybody know what I should do for fixing it? Yes, I'm a little lazy and don't want to read tons of documents for BABELJS. But, I'm just a developer who want to use tool without stupid monkey work in command line.

**Comment by gandm** [comment]
Can you provide me with some of the JSX that's giving you the problem? The `<%DIRECTORY%>/js/vvt_datatable/test.jsx: Unexpected token (99:7)` message indicates a syntax error but I can't see anything on line 99?

**Comment by taulatin** [comment]
No, code is correct. I've tested it on this https://github.com/gandm/example-language-babel
with the same 'Unexpected token' error

**Comment by gandm** [comment]
That error is coming straight from Babel not from my package so there something wrong and nothing much I can do about it. Put the code in here http://babeljs.io/repl/ and see if it works. I'm going to close this issue as it isn't the package.
