### ISSUE TITLE
Custom elements jsx broken

### ISSUE THREAD

**Issue by jscissr** [gandm/language-babel#176]
Very recently, custom html elements in jsx are no longer highlighted correctly:

```jsx
 <paper-button></paper-button>
```

It guess it is because of a minus which was dropped from a regex in [this commit](https://github.com/gandm/language-babel/commit/a256580c194139753c43fde3f9fade6e8cca0d1d#diff-84d196d176a806166c5319d65e586325L1523).

**Comment by gandm** [comment]
Just pushed 2.19.4 that adds back the - as a possible name for custom elements. It will be highlighted as a component. Sorry about that.

**Comment by jscissr** [comment]
Thanks! :+1:
