### ISSUE TITLE
React classes are wrong color

### ISSUE THREAD

**Issue by jamby** [gandm/language-babel#177]
<img width="304" alt="screen shot 2016-05-05 at 10 33 43 am" src="https://cloud.githubusercontent.com/assets/250728/15046299/f9ecf482-12ac-11e6-9a05-09ea891b5bfb.png">

I'm using Atom Material UI and Atom Material Syntax Dark, and the syntax coloring for a React class seems to be the same as attributes. It used to be red in this case, now it is yellow.

**Comment by gandm** [comment]
I had an enhancement request [here](https://github.com/gandm/language-babel/issues/173) to change the highlight of JSX components and custom elements. These are now scoped as `support.class.component.open.jsx` and it happens in your theme that attributes are themed with the same colour. Not sure what I can do about these issues I tested with about 10 themes and didn't have an issue ( too many themes! ). I just checked a few Material themes and they all have the problem.

**Comment by jamby** [comment]
So is there any way I can change it back myself?

**Comment by gandm** [comment]
You can add some colors to your Atom `styles.less` which can be found on one of the atom menu's e.g. Adding this

```
atom-text-editor::shadow {
  .source.js.jsx {
    .jsx {
      .entity {
        &.name.tag {
          color: blue;
        }
        &.other.attribute-name {
           font-style: italic;
           color: green;
        }
      }
      .support.class.component {
        color: red;
      }
    }
  }
}
```
gives
![image](https://cloud.githubusercontent.com/assets/2313237/15047937/184d192a-12df-11e6-990d-10580703c279.png)

**Comment by jamby** [comment]
Coolio, just what I wanted. Thanks!

**Comment by grabbou** [comment]
FYI that doesn't work well with built-in React Native components

**Comment by gandm** [comment]
@grabbou I'm not sure what you mean? ReactNative uses JSX  the same as React. There is no distinction between the two in terms of JSX.

**Comment by gandm** [comment]
Can you give me an example.

Sent from my Windows Phone
________________________________
