### ISSUE TITLE
Invalid highlighting with if statements

### ISSUE THREAD

**Issue by bjrmatos** [gandm/language-babel#178]
I have updated my language babel package and noticed that `if` statements are in wrong formatting

OS: OSX

<img width="1587" alt="captura de pantalla 2016-05-07 a las 12 58 54 p m" src="https://cloud.githubusercontent.com/assets/4262050/15093671/0ad233f4-1454-11e6-9205-f90e7777c877.png">

**Comment by gandm** [comment]
Sorry about that. I pushed out a large change and added something at the last minute that caused this. I'll fix it and push out shortly.

**Comment by bjrmatos** [comment]
@gandm no problem! i can't express how much your work make my work more pleasure 😄

**Comment by gandm** [comment]
@bjrmatos should be fixed.

**Comment by gandm** [comment]
@bjrmatos the latest version is 2.20.2 that should fix the problem. I've closed this but feel free to reopen if it's still an issue. Thanks for the kind words; appreciated.

**Comment by bjrmatos** [comment]
indeed! it's fixed now! thnk you for ur time!
