### ISSUE TITLE
Suggestion: let us change the time the notifications stay up for, or their position?

### ISSUE THREAD

**Issue by rohan-deshpande** [gandm/language-babel#18]
Using this with Atom, really liking it but the notifications are a little intrusive. I like them because they give me good feedback, but their position means I can't access tabs they cover, they also stay up for too long sometimes. 

Would be great if changing their timing and position was configurable.

**Comment by gandm** [comment]
Yes that would be nice. The notifications are part of the atom package and don't appear to have any timer option. Yes they do cover the tab bar and again this is atom core. I will raise issues there. Other than that the only other option is to change the method of notification but I'd prefer to keep it standard.

**Comment by rohan-deshpande** [comment]
Oh yeah totally keep them in line with the standard, I guess Atom need to provide ways to easily configure that stuff then.

**Comment by gandm** [comment]
https://github.com/atom/notifications/issues/86
