### ISSUE TITLE
Cursor being moved to after closing tag after autocomplete in JSX

### ISSUE THREAD

**Issue by ilmatic** [gandm/language-babel#180]
Steps to repro:

1. Create an opening tag inside of a JSX file (Mine is being written inside a ```<script>``` tag, per the official React tutorial)
<img width="541" alt="screenshot_language-babel-bug_0" src="https://cloud.githubusercontent.com/assets/2415202/15123040/a1aa3186-15d6-11e6-943a-175ae20cfdb7.png">

2. Press "return" to select the closing tag. At this point the cursor is in between the two tags.
<img width="360" alt="screenshot_language-babel-bug_1" src="https://cloud.githubusercontent.com/assets/2415202/15123086/d40cfc4e-15d6-11e6-85bd-973aa0ebdf18.png">

3. Press "return" two more times to add a line between the two tags. At this point the cursor is right before the closing tag.
<img width="359" alt="screenshot_language-babel-bug_2" src="https://cloud.githubusercontent.com/assets/2415202/15123125/ffad57c2-15d6-11e6-89f4-4ebe9e3e21a1.png">

4. Press the "up" arrow once to move the cursor to the beginning of the previous line.
<img width="426" alt="screenshot_language-babel-bug_3" src="https://cloud.githubusercontent.com/assets/2415202/15123139/140e34e8-15d7-11e6-8196-c8ee15fc4cb3.png">

5. Press "tab".

Expected: It should automatically indent to one level deeper than the opening and closing tags, and leave the cursor at that point.
(Simulated screenshot of what should be happening)
<img width="320" alt="screenshot_language-babel-bug_5" src="https://cloud.githubusercontent.com/assets/2415202/15123190/651096b0-15d7-11e6-89fd-a895633aefb8.png">

Actual: It moves the cursor to right after the closing tab.
<img width="433" alt="screenshot_language-babel-bug_4" src="https://cloud.githubusercontent.com/assets/2415202/15123195/73e8ad44-15d7-11e6-98ae-1e09ee2eaae2.png">

**Comment by ilmatic** [comment]
Operating System: OS X 10.11.3 
Atom version: 1.7.3
language-babel version: 2.20.4

**Comment by gandm** [comment]
@ilmatic It should work as intended now. Thanks.

**Comment by ilmatic** [comment]
Confirmed working. Thanks!
