### ISSUE TITLE
Incorrect higher-order function parsing

### ISSUE THREAD

**Issue by billyjanitsch** [gandm/language-babel#181]
The following code is incorrectly parsed:

```js
const withStore = store => Component => props =>
  <Provider store={store}>
    <Component {...props} />
  </Provider>
```

<img width="515" alt="screen shot 2016-05-09 at 4 45 19 pm" src="https://cloud.githubusercontent.com/assets/1158733/15127646/843f4d46-1605-11e6-90f9-2f4a54127bf6.png">

Expected: `props` should be red, `Provider` should be yellow, `store` should be orange, etc.

**Comment by gandm** [comment]
I'll have to mull this over. I can easily fix this issue but it has some undesired side effects with my flow support. As a workaround the code below works, abeit it uses a let and is two lines.
```
let withStore; // can't use const as we reassign
withStore = store => Component => props =>
  <Provider store={store}>
    <Component {...props} />
  </Provider>
```
