### ISSUE TITLE
add support for template literals

### ISSUE THREAD

**Issue by rickmed** [gandm/language-babel#183]

**Comment by gandm** [comment]
Not sure what you mean; can you eleaborate. This is already in the package.
![image](https://cloud.githubusercontent.com/assets/2313237/15128794/d74717be-1635-11e6-9264-608bf5d32716.png)

**Comment by rickmed** [comment]
@gandm should it work like this?

![image](https://cloud.githubusercontent.com/assets/7104786/15130892/c8936c66-1619-11e6-8348-73bdaaa2b3d8.png)

**Comment by gandm** [comment]
Looks as though you are using a Monokai based theme? The theme determines the colours displayed and Monokai just shows  template strings with embedded vars as yellow. See https://github.com/kevinsawicki/monokai/issues/67 

e.g.
Monokai 
![image](https://cloud.githubusercontent.com/assets/2313237/15135330/f78b5abc-166c-11e6-9028-24dfd98004b6.png)
Atom Dark
![image](https://cloud.githubusercontent.com/assets/2313237/15135335/0a586342-166d-11e6-8a23-f7b1ec2637aa.png)
Visual Studio Dark 
![image](https://cloud.githubusercontent.com/assets/2313237/15135341/2101153a-166d-11e6-85b4-23087e9c9613.png)

**Comment by gandm** [comment]
I'll close. Open again if you feel the need,
