### ISSUE TITLE
Incorrect highlighting of quoted shorthand method notation

### ISSUE THREAD

**Issue by kaicataldo** [gandm/language-babel#184]
Came across something while working on my own theme - not sure if this is an issue with the language-babel package or something else.

In the following example, the highlighting is incorrect. If I remove the `this` or the hyphen in the method name, everything works as it should. This seems to only happen for the first quoted shorthand method name with a hyphen in it when it is in an object that is an arg of a method being called on `this`.

![screen shot 2016-05-09 at 6 10 34 pm](https://cloud.githubusercontent.com/assets/7041728/15129708/59f8c204-1611-11e6-8514-ebe60f406a8c.png)

Screenshot taken with the default One Dark theme.

**Comment by gandm** [comment]
Yes I can see the problem area. I'll fix it tomorrow sometime.
