### ISSUE TITLE
Class property “type”

### ISSUE THREAD

**Issue by daltones** [gandm/language-babel#185]
Class properties named “type” break highlight on the entire line.

```js
class SomeClass {
  myProperty = 'some value'               // highlight okay
  type = ('any' + ' ' + 'expression')     // no highlight at all
}
```

**Comment by gandm** [comment]
OK thanks for this. type, declare, interface are flow keywords and that's why it isn't working. I'll modify the grammar and fix this but it won't be until the weekend. If you are using flow then typing the field works. e.g. `type: string = 'some string'`

**Comment by gandm** [comment]
@daltones Just pushed 2.20.9 - See if that does the trick.

**Comment by daltones** [comment]
Yes, it does! :smile: 

Thanks!
