### ISSUE TITLE
Very slow processing for some kind of strings

### ISSUE THREAD

**Issue by styx** [gandm/language-babel#187]
In attach you will find 2 files. One is a total DoS (with `kill` in the name). Don't know how long you will need to wait for to open it. The second file will take some seconds to process (~5 secs on my laptop).

If you will edit the string `url` you will get a freeze again.

Note: it is not a problem of conflict with other plugins. I've checked that. Atom freezes with single babel extension.

[1.zip](https://github.com/gandm/language-babel/files/275839/1.zip)

**Comment by gandm** [comment]
Looks like an issue with Oniguruma which Atom uses to process the regex in language grammars. A couple of expressions I use to process arrow functions work in  [RegExBuddy](http://www.regexbuddy.com/)  but appear to cause infinite back tracking in Oniguruma. All the expressions are probably overkill in any case as they attempt to handle flow typed arrow function where the argument has no brackets. It's an area of flow that's not documented, so it was a guess on my part. 
e.g.
```jsx
arg: string  => { return arg } // is this valid flow?
(arg: string) => { return arg } // because this is.

```

I'll probably change the three expressions causing the issue even though I think Oniguruma is not working quite correctly. Oniguruma seems to be incorrectly reading ahead to the `xxx0:` in your template string and than balking on it. if you put a space between xxx and 0 then it works.

**Comment by styx** [comment]
@gandm Thanks for the fast response! 😸 Would be nice to post an issue to Oniguruma then, what do you think? I believe you will describe the situation clearer, sorry for passing this to you.

**Comment by gandm** [comment]
@styx Just pushed 2.21.0 that should fix your problem. I'll look into the Oniguruma issue.

**Comment by styx** [comment]
Yay, it works (: Thnx again.
