### ISSUE TITLE
Snippets for es6

### ISSUE THREAD

**Issue by puranjayjain** [gandm/language-babel#188]
@gandm Can I start a PR to include es6 related snippets like import?

**Comment by gandm** [comment]
@puranjayjain Thanks for the offer but I'm not sure if I want to add snippets to the package. I have always felt that snippets should be a separate package as Atom provides no easy way to opt out. By having a separate package, of which there are many, you can choose to opt in. Questions also arise such as - do you provide snippets with or without semi-colons; for Flow; for Typescript; for React, for Angular, etc.

**Comment by puranjayjain** [comment]
Ah that's a bigger issue than I thought :sweat_smile:
