### ISSUE TITLE
Remove `label` from classes applied for syntax highlighting

### ISSUE THREAD

**Issue by Glavin001** [gandm/language-babel#19]
Text that matches `constant.other.object.key.js` is being matched and having the classes `string.unquoted.label.js` applied. The `.label` class applies Bootstrap's CSS which has bold, a different font size, and padding, which all contribute to making the rendered text a headache to edit because the visible location of the cursor does not match the actual cursor position, and therefore I end up editing the wrong characters.

## Example

Now the `testWithLabel` is default syntax highlighting. `ing` key is that is detected by another grammar pattern and correctly highlights. `testWithoutLabel` is what I expect to see, and I was able to accomplish by manually removing the `label` class from the element in the DOM.

### Screenshot
![image](https://cloud.githubusercontent.com/assets/1885333/8611263/bd890ea4-2694-11e5-9757-e9ce889f6b18.png)

### Code

```javascript
let obj = {
  testWithLabel: null,
  testWithoutLabel: null,
  ing: function() {

  }
};
```

## Bug

See https://github.com/gandm/language-babel/blob/master/grammars/Babel%20Language.json#L197

### Code
```
 "literal-labels": {
      "patterns": [
        {
          "begin": "(?<!\\?)(?<!\\?\\s)(?=(((')((?:[^']|\\\\')*)('))|((\")((?:[^\"]|\\\\\")*)(\")))\\s*:)",
          "end": ":",
          "endCaptures": {
            "0": { "name": "punctuation.separator.key-value.js" }
          },
          "patterns": [
            { "include": "#literal-string" }
          ]
        },
        {
          "name": "constant.other.object.key.js",
          "match": "(?<!\\.|\\?|\\?\\s)([_$a-zA-Z][$\\w]*)\\s*(:)",
          "captures": {
            "1": { "name": "string.unquoted.label.js" },
            "2": { "name": "punctuation.separator.key-value.js" }
          }
        }
      ]
    },
```

**Comment by gandm** [comment]
Good catch. Someone else had this issue and I knew it was something else styling it but I couldn't recreate it and their issue went away on a reload of Atom. You say Bootstrap CSS is styling it but from where? a package? a theme?

**Comment by Glavin001** [comment]
Not sure, it could be Atom's core styles? In case it's a theme, here is my current theme settings:
- UI Theme: Atom Dark
- Syntax Theme: One Dark

Static screenshot showing what I see as the source style file of the `.label` rule:
![image](https://cloud.githubusercontent.com/assets/1885333/8612768/4594e7f2-26ac-11e5-87c2-7cf8db4e2276.png)

**Comment by gandm** [comment]
It doesn't appear to be either of those themes, nor does it seem to be core, at least not on my system. I'm happy enough to accept the pull request but I'd like to understand what is doing this. Things shouldn't style text without being asked! I don't suppose you could list your installed packages and themes?

**Comment by Glavin001** [comment]
Gladly. I am also curious.

```
✗ apm list --installed
/Users/glavin/.atom/dev/packages (1)
└── amp-tester@0.0.0

/Users/glavin/.atom/packages (65)
├── .bin
├── Sublime-Style-Column-Selection@1.3.0
├── Termrk@0.1.17
├── Tern@0.8.0
├── angularjs@0.3.0
├── apm-publish@0.1.3
├── ask-stack@2.0.0
├── atom-beautify@0.28.7
├── atom-color-highlight@3.0.9
├── atom-handlebars@0.5.0
├── atom-html-preview@0.1.6
├── atom-lint@0.20.1
├── atom-typescript@4.5.9
├── atomatigit@1.5.2
├── autocomplete-paths@1.0.2
├── autocomplete-plus-python-jedi@0.3.6
├── bezier-curve-editor@0.7.1
├── break@0.3.1
├── coffee-navigator@0.0.16
├── coffee-refactor@0.6.2
├── coffee-trace@0.2.2
├── color-picker@2.0.2
├── coverage@0.6.0
├── emmet@2.3.10
├── file-icons@1.5.6
├── filetype-color@0.1.4
├── find-and-replace@0.170.0
├── firepad@0.3.1
├── focus-dark@1.1.0
├── git-blame@0.4.4
├── git-diff@0.55.0
├── git-plus@5.0.3
├── gitignore-snippets@0.2.3
├── gitter@0.6.2
├── go-plus@3.3.11
├── grunt-runner@0.10.0
├── iTunes@0.2.0
├── irc@0.4.0
├── jshint@1.3.7
├── keybinding-resolver@0.33.0
├── language-babel@0.10.0
├── language-cjsx@0.3.0
├── language-csharp@0.5.0
├── language-ejs@0.1.0
├── language-html-swig@2.0.0
├── language-jade@0.4.0
├── language-jsx@0.1.4
├── language-marko@0.4.15
├── language-rust@0.4.3
├── language-spacebars@0.2.2
├── language-swift@0.4.0
├── language-swig@0.1.0
├── language-tss@0.1.0
├── linter@0.12.6
├── linter-coffeelint@0.2.4
├── linter-csslint@0.0.13
├── linter-jshint@0.1.5
├── linter-pylint@0.2.2
├── linter-scss-lint@1.0.4
├── makro@0.2.0
├── merge-conflicts@1.3.2
├── preview@0.16.2
├── refactor@0.4.1
├── tabs-to-spaces@0.11.0
└── term2@0.9.12
```

**Comment by gandm** [comment]
Thanks. I'll look at that list. FYI when I put your example code in my editor it looks fine and inspector shows that that the computed style is generated from `app.asar\node_modules\one-dark-syntax\index.less`

**Comment by gandm** [comment]
One further thing. If you revert your PR and reload Atom is the issue still present. I can't see why bootstrap.css is selected on your system when on mine it is the one-dark-syntax styling it!
