### ISSUE TITLE
JSX niceties only work for *.jsx (not for *.react.js)

### ISSUE THREAD

**Issue by artursgirons** [gandm/language-babel#190]

**Comment by gandm** [comment]
I don't understand what you mean? a file named `foo.react.js` is treated no differently than `foo.jsx`

**Comment by artursgirons** [comment]
For me it works differently :( I don't get nice commenting features, and autocomplete also does not work. Not sure how could I fix this, maybe there are some conflicting packages for me.

**Comment by gandm** [comment]
For the file you are having issues with what isnthe name  of the grammar displayed . Bottom right bar of Atom should show 'Babel ES6 JavaScript"

**Comment by artursgirons** [comment]
Much appreciated! This solved the issue! React package was setting it to "Javascript (JSX)"

**Comment by gandm** [comment]
Thanks for the update. Yes it seems quite a lot of people use the react package in conjunction with this one but I'm not really sure why.

**Comment by artursgirons** [comment]
For me it was that I used react package before, but now with language-babel i have no need for react package! Thanks!
