### ISSUE TITLE
Tab length can't be set

### ISSUE THREAD

**Issue by mivade** [gandm/language-babel#191]
I'm not entirely sure if this is an issue with this package or something else, but I am having an annoying issue where my tab length keeps getting set to `4`. If I try to edit the setting to `2`, the `2` is immediately replaced by a `4`. If I just delete the `4`, placeholder text says `Default: 2`, but this is not actually the case when I try to autoindent and get 4 spaces instead of 2.

I also see similar behavior when editing `config.cson`: I can add `tabLength: 2` under the appropritae settings, but as soon as I save, that line is deleted and replaced with `tabLength: 4`! This does *not* happen with editor settings with any other language.

My default tab length is set to 4, but I would like to use 2 spaces for Javascript.

Atom version:

```
$ atom --version
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

language-babel version 2.23.0.

**Comment by gandm** [comment]
Appears to be a bug in Atom itself.  As a fix you will need to remove the lines shown in the image below from config.cson and save it. Atom creates these when a non-default setting has been set on a grammar's settings but they keep getting created when a global tab length is changed!!!!! Very bad.

Detail: Atom has a global tab setting and each grammar package can have an individual tab setting. e.g. In language babel's package settings you will see two distinct grammar settings `Babel ES6 Grammar` and `Regular Expressions (Babel) Grammar`. If you set a tab length here you will see something like this in `config.cson`

![image](https://cloud.githubusercontent.com/assets/2313237/15547182/98ffba1c-229a-11e6-861b-56aa47219115.png)

However setting a global tab length also set's these two options. BUT resetting the global doesn't reset the individual settings. The same seems to happen for any grammar if that grammars tab length is changed just once!!

**Comment by gandm** [comment]
Referred to Atom https://github.com/atom/atom/issues/11840

**Comment by mivade** [comment]
Thank you!

**Comment by Trudko** [comment]
Anyone experiencing this issue? I am using 1.14.1 Atom and Latest version of the package but I am having the same issue.

**Comment by sangdth** [comment]
I still have this problem even in Atom 1.19. Had to work around with manual edit as @gandm wrote.

**Comment by mattcbro** [comment]
gandm's technique does not work for me.  My tab settings are always set to 8 no matter what tabLength parameter I have in any setting.  Yet 8 shows up nowhere in any config file.  Very frustrating.
