### ISSUE TITLE
Atom freezes on <Route> tag

### ISSUE THREAD

**Issue by kpompei** [gandm/language-babel#192]
When I type in <Route></Route> into a .jsx or .js page and then click my mouse anywhere in the document.  Atom's editor immediately freezes and Atom has to be restarted.  This just begun when upgrading to 2.23.0.

**Comment by gandm** [comment]
I can't recreate this on Atom 1.7.4 & language-babel 2.23.0
![jsx](https://cloud.githubusercontent.com/assets/2313237/15549814/52912992-22a6-11e6-8b65-16728b046dff.gif)
Do you have a sample of the code? Preferably all of it. Place it in a gist if you want.
What Atom version/platform?

**Comment by kpompei** [comment]
Same versions you have below.  On Mac OS X 10.11.5.

Here is the code:

var React = require('react');
var ReactDOM = require('react-dom');
import {Route, Router, IndexRoute, hashHistory} from 'react-router';

ReactDOM.render(
  <Router history={hashHistory}>
     <Route></Route>
  </Router>,
  document.getElementById('app')
);

If I even paste this in a file and then click anywhere in the file, it immediately freezes.

Thank you, btw, for responding!

Kevin

**Comment by gandm** [comment]
Kevin, I cut and pasted you code into my editor with no issues. The only thing I can suggest is that it isn't this package causing the problem or when it was updated it somehow got corrupt. Atom also changed versions from 1.7.3 to 1.7.4, so maybe that got corrupted during the update. You could uninstall language-babel, stop atom and then remove ~/.atom/compile-cache, restart atom and re-install language-babel. If that doesn't work you can try installing an older version e.g. `apm install@2.22.0`

**Comment by kpompei** [comment]
Yep, that did it.  Just uninstalling and reinstalling the plugin fixed it.  Thank you so much for taking the time to respond.  It is such a useful plugin!

Thanks Graham!

**Comment by gandm** [comment]
Kevin, thanks for letting me know. I'll close the issue.
