### ISSUE TITLE
Trailing White Space Being Added with Auto Indent JSX

### ISSUE THREAD

**Issue by jnmorse** [gandm/language-babel#193]
Enabling auto-indent with JSX end up inserting trailing white space whenever my cursor moves over a blank line.

[Eslint Settings](https://gist.github.com/jnmorse/891ae08c88575355d0790f32dda9fcde)

![annoying-whitespace](https://cloud.githubusercontent.com/assets/1467889/15562354/842fced8-22cc-11e6-8618-bfdaa1b2826b.png)

**Comment by gandm** [comment]
Just published a new version v2.23.2 that should fix your problems. To fix existing code just position the cursor on the last JSX line. e.g. line 106 in the screen capture you sent.

**Comment by jnmorse** [comment]
Cool, Seems to be no longer inserting the white space now.  Thanks
