### ISSUE TITLE
jsx: bracket-match behavior

### ISSUE THREAD

**Issue by aeosynth** [gandm/language-babel#195]
hi, i'm requesting behavior like that of the bracket-matcher package - when inserting a newline between 2 brackets, insert 2 newlines, and move the cursor. example:

```
{.}
```

```
{
  .
}
```

replace the brackets with jsx tags

**Comment by gandm** [comment]
This has been added to 2.25.0

**Comment by aeosynth** [comment]
works great, thanks. i had to restart atom to get it.
