### ISSUE TITLE
Highlighting brakes if JSX components start or end with a space.

### ISSUE THREAD

**Issue by Fahrradflucht** [gandm/language-babel#196]
Try this in atom:
```JSX
      return ( 
        < Provider store = { this.state.store } >
          <AlrightApp >
        </Provider>
      );
```

I wanted to file this here because I considered it as a bug, but now that I see githubs highlighting breaking too i'm not sure if it's a bug or a feature, but as it seems like valid JSX I thought I file it anyway.

Let me know what you think. Don't hesitate closing though.

**Comment by gandm** [comment]
In my opinion  the example is incorrect. You can't have a space between the opening tag and it's name. So  `< Provider` is incorrect,  Also `<AlrightApp >` isn't terminated - It should either self close or be matched. That is why the closing tag is showing as unmatched.

I used this [document](http://facebook.github.io/jsx/) which facebook issued to describe the syntax and it appears to indicate no spaces are allowed between < and the name.

However Babel does seem to compile the component with a space between the < and tagName which is strange.

**Comment by Fahrradflucht** [comment]
Yeah you are right in that my example missed a `/` but if you do `<App / > the highlighting for the next component breaks.

I never did it that way but for some reason [atom-beautify](https://github.com/Glavin001/atom-beautify) does this to my JSX. But if you are right in that this is against the spec, then I maybe should file a bug on JS Beautify. - Oh wait! It seems to be [this](https://github.com/beautify-web/js-beautify/issues/914) one if I skim correctly...

**Comment by gandm** [comment]
Well it goes against the spec so as far as I'm concerned it's wrong. By the way GitHub use my grammar for JSX files and code blocks starting ```jsx so that maybe not the best check. I'm closing this. Thanks.

**Comment by gandm** [comment]
Oh by the way the highlighting isn't breaking. It is designed to show tags that are open but not closed or closed and not open.
