### ISSUE TITLE
recursive transpile

### ISSUE THREAD

**Issue by aeosynth** [gandm/language-babel#197]
the 'babel transpile' menu item only transpiles one level deep; it should transpile the entire tree

**Comment by gandm** [comment]
It was designed like that to avoid large side effects. Unsure about the requirement for this as I'd imagine most people would use gulp, grunt, webpack and their ilk, to do mass transpiles.  Why would you use this option?

**Comment by aeosynth** [comment]
yes, i will set up a real build system, but for now i'm working on an unreleased project, and it's been neat using this package for builds. if you're assuming people have a build system, then what's the point of this option?

**Comment by gandm** [comment]
I'm happy to add a recursive option but I didn't think anyone would use it. I guess it depends on the application being developed.

**Comment by aeosynth** [comment]
you could remove the option entirely and tell people to use a real build system. the issue i have is that this option only half works.

**Comment by gandm** [comment]
Just pushed 2.26.0 that has a sub-menu under a menu `Language-Babel` that allows recursive directory descent transpiles.

**Comment by aeosynth** [comment]
works, thanks
