### ISSUE TITLE
Incorrect highlighting for `export foo from './bar'`

### ISSUE THREAD

**Issue by billyjanitsch** [gandm/language-babel#198]
I noticed an issue with the syntax highlighting for namespace exports (an [ES2017 stage 1 proposal](https://github.com/leebyron/ecmascript-export-ns-from), implemented in Babel):

```js
// I'd expect these to be highlighted similarly:
import foo from './bar'
export foo from './bar'
```

Instead, I see:

<img width="241" alt="screen shot 2016-06-01 at 1 37 07 am" src="https://cloud.githubusercontent.com/assets/1158733/15699228/79574f00-2799-11e6-96a0-c75a823e6113.png">

I think this is a regression within the past few versions.

**Comment by gandm** [comment]
As far as I can see that proposal doesn't support that form of export. It suggests  "export * as ns from "mod"

**Comment by gandm** [comment]
Ok I see it in this other [proosal](https://github.com/leebyron/ecmascript-export-default-from)

**Comment by gandm** [comment]
Added this in v2 25.0.

**Comment by billyjanitsch** [comment]
Thanks a lot! Sorry for the incorrect link.
