### ISSUE TITLE
Source maps are not created inside the files

### ISSUE THREAD

**Issue by mazzy89** [gandm/language-babel#199]
Here is `.babelrc` config

```json
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "transform-async-to-generator"
  ],
  "env": {
    "development": {
      "sourceMaps": "inline"
    }
  }
}
```
and here is my `.languagebabel` config file

```json
{
  "babelMapsPath": "",
  "babelMapsAddUrl": false,
  "babelSourcePath": "lib",
  "babelTranspilePath": "dist",
  "createMap": false,
  "createTargetDirectories": true,
  "createTranspiledCode": true,
  "disableWhenNoBabelrcFileInPath": true,
  "suppressSourcePathMessages": false,
  "suppressTranspileOnSaveMessages": false,
  "transpileOnSave": true,
  "projectRoot": true
}
```

the problem is that when I automatically save the sourceMaps are not created inside the file. is it a bug or I'm missing anything?

**Comment by gandm** [comment]
I'm not near a system so I can't test. My guess is that atoms default node environment is set to production. You can try launching atom --dev and see if that works.
________________________________

**Comment by mazzy89** [comment]
No it doesn't work @gandm.

**Comment by gandm** [comment]
And NODE_ENV is set to development?
________________________________

**Comment by mazzy89** [comment]
where should I check on Atom if NODE_ENV is equal to `development`?

**Comment by gandm** [comment]
Depends on how you start it. Best start from a shell where you can set it before you start atom.

Can't be more helpful without a system.

Sent from my Windows Phone
________________________________

**Comment by mazzy89** [comment]
Gotcha. :-) Executed from the shell with the following command but without luck:

`NODE_ENV=development atom --dev`

it doesn't work

**Comment by gandm** [comment]
Not back online until Monday. Sorry.
________________________________

**Comment by mazzy89** [comment]
It's not a problem 👍 enjoy the weekend

**Comment by gandm** [comment]
I've fixed this in 2.26.2. Not sure if babel has changed the precedent of map overrides or maybe this never worked for inline maps! Anyway, close if it solves the issue.

**Comment by mazzy89** [comment]
Thank you. I'll test later today and I'll close it if this solve has solved the issue

**Comment by gandm** [comment]
Actually, there is still an issue in enviroments. I'll take another look.

**Comment by gandm** [comment]
No, it does work - I forgot to set my env variables when I re-tested doh!. Obviously you need to set either `BABEL_ENV` or `NODE_ENV` environment variables to `development` before launching atom as per the babel docs.

```
# at the start of a command
$ BABEL_ENV=production atom

# or as a separate command
$ NODE_ENV=production
$ atom
```

**Comment by mazzy89** [comment]
But according to the doc http://babeljs.io/docs/usage/babelrc/#env-option if nothing is set then development will be used. so do I need to set manually env var?

**Comment by gandm** [comment]
Yes because atom sets it to production if NODE_ENV is missing [here](https://github.com/atom/atom/blob/6e6771ad5c913313de2bf83fecb38cdd0d6724b8/src/initialize-application-window.coffee#L20)

If you start atom as atom --dev then it would most likely work as that atom then just passes the node env through even if null.

I'll think about how I can fix this but it would probably require spawning to get the env before atom patched it.

**Comment by mazzy89** [comment]
Tested and now it works. For me it can be considered closed but I'd add this in the documentation because it is not obvious
