### ISSUE TITLE
Console is treated like a function

### ISSUE THREAD

**Issue by anIddan** [gandm/language-babel#204]
for some reason when i type console (with log or anything) it colours it as it was a function instead of an object.

**Comment by gandm** [comment]
The scopes for console are `support.type.object.console.js` and for log `support.function.console.js`

How they are highlighted is down to the syntax theme.

![image](https://cloud.githubusercontent.com/assets/2313237/15859554/8528b6d8-2cbd-11e6-9f31-340fe6be74e6.png)

**Comment by gandm** [comment]
@anIddan I assume the above answers your query. I'll close this issue but will re-open if I have misunderstood you.

**Comment by anIddan** [comment]
Thanks
