### ISSUE TITLE
Commenting attributes in JSX 

### ISSUE THREAD

**Issue by philraj** [gandm/language-babel#206]
I couldn't find a way to change the behavior of auto-commenting (`cmd + /`) when the cursor is inside a JSX element's attributes. Webpack is throwing a build error when I comment out an attribute (for example, if I want to test an element without the `className` attribute) because it puts `{*  *}` around the line, but apparently this is an "unexpected token". 

Comments using regular `//` or `/* */` are valid when inside the angled brackets of an element declaration, e.g.:
```
<MyComponent
  // className="my-class"
  myProp={propValue}
/>
```
Is there a way to enable this type of behavior selectively, or would it be difficult to implement?

**Comment by gandm** [comment]
I do this automatically. My guess is you aren't using my grammar. Should show Babel ES JavaScript on the status bar.
________________________________

**Comment by gandm** [comment]
Sorry just re-read this and i'll check.

**Comment by philraj** [comment]
Thanks! Appreciate it.

**Comment by gandm** [comment]
I just pushed 2.28.0 that has improved the commenting of JSX. Hopefully, it will use the most appropriate comment type depending on the start line being commented. e.g. attributes will use //

**Comment by philraj** [comment]
Seems to work great. Thanks again.
