### ISSUE TITLE
jsx auto indent failure with sibling elements

### ISSUE THREAD

**Issue by cshanejennings** [gandm/language-babel#207]
I'm not sure if this is a configuration issue, plugin conflict or a bug, but I'm not sure where to find a resolution so I'm pasting my issue here, apologies if this isn't the right place as I humbly lay my problem out before you.

Everything seems to be working fine (thank you for that, no really), except for one issue in JSX files, pressing enter after a closing tag results in a new line with an indentation set to one level below it's sibling tag.  See below:
````
export default class Test extends Component {
  render() {
    return (
      <div>
        <h1>Title</h1>{/* pressing enter here returns one indentation lower than this line */}
      <p>This level of indention reached by pressing enter after the h1 tag</p>
    <p>This level of indention after pressing enter again</p>
  <p>and so on...</p>
      </div>
    );
  }
}
`````

This will continue as a reverse staircase until there is no more indention.  I'm using v 2.28.0 on Windows 10.  If I add a tag as a child into a single line tag, it will expand into a properly indented parent / child expanded view, only the siblings fall one indentation short.  Thoughts?  Of course I'm happy to provide more info if it could be helpful.

**Comment by gandm** [comment]
I can't recreate this - gif below was WIndows 10. Are you sure you are using my grammar? `Babel ES6 JavaScript` should be displayed on the bottom status bar.
![indent](https://cloud.githubusercontent.com/assets/2313237/16285241/0644608a-38cd-11e6-8919-c9b1c863b17a.gif)

**Comment by cshanejennings** [comment]
Yes, confirmed Babel ES6 Javascript.  I'll try disabling some plugins and see if that helps.  Any suggestions on configuration?

**Comment by cshanejennings** [comment]
Disabling all my plugins and re-enabling seems to have done the trick.  Must have been some kind of strange config corruption issue.  Anyhow, obviously the issue wasn't language-babel.  Thanks for taking a look and sorry about the distraction!

**Comment by gandm** [comment]
What version of Atom?
I had a similar report that just went away see https://github.com/gandm/language-babel/issues/163 
Atom seems to glitch sometimes when updating packages or itself. Maybe uninstalling my package and reinstalling will fix it.

**Comment by cshanejennings** [comment]
1.8.0   It's all working now.  I think there's some issue with apm and windows among other things.  Atom.is is a huge undertaking, I get that.  I think windows is a bit of a second class citizen as a natural consequence to the number of open source developers using it.  I had to jump through a lot of git and npm related hoops when trying to restart with a clean installation and there may still be some leftover radiation from that meltdown. :)  I'm comfortable with cycling the enabled status of my plugins if it happens again.  As far as the plugin goes, I think this kind of issue is well outside the sphere of influence for language-babel and 90+% chance it's core related. :)
