### ISSUE TITLE
Self-closing JSX tags mess with indentation

### ISSUE THREAD

**Issue by clessg** [gandm/language-babel#208]
Hopefully this gif explains it:

![](http://i.imgur.com/wTGIoaF.gif)

Is anybody able to reproduce this? Is this expected behavior?

**Comment by gandm** [comment]
The only way I can recreate this is by having the [react package](https://atom.io/packages/react) enabled/active? This package monkey patches the indentation atom code. If this is the case I suggest you disable it and restart Atom and try again.

I also have a package setting `Auto Indent JSX` that will always indent JSX correctly regardless. See the readme for more info.

**Comment by gandm** [comment]
Closing this issue. Re-open if required.

**Comment by clessg** [comment]
Thank you, that resolved it. I really appreciate your assistance!

**Comment by andywarren** [comment]
HI all, I'm brand new to Atom and React. I'm trying to take a Udemy React course, and I literally have no idea what packages I need in Atom, but I'm getting the same error as stated above. I have the React and Language Babel packages installed. Which is preferred for learning Atom and React? Is there a reason I should choose one over the other? Thanks!
