### ISSUE TITLE
'react' incompatibility

### ISSUE THREAD

**Issue by amilajack** [gandm/language-babel#209]
I'm getting an error saying that the package 'react' is not compatible with 'language-babel'. This happens after migrating to language-babel@2.29.0.

**Comment by 93html** [comment]
+1

**Comment by 93html** [comment]
![image](https://cloud.githubusercontent.com/assets/8575822/16438672/5e1b6daa-3de4-11e6-8650-afd16bb53fe6.png)
Maybe not need that one?

**Comment by ggamel** [comment]
Receiving same error.

**Comment by gandm** [comment]
It's not an error it's because there is an incompatibility between language-babel and the package named 'react'. It has nothing to do with Facebook react. I would suggest you choose to disable my package and use react or vice versa if you don't want to see the error.

**Comment by amilajack** [comment]
Works like a charm now. Thanks @gandm!
