### ISSUE TITLE
babelrc seems to be ignored

### ISSUE THREAD

**Issue by alex3683** [gandm/language-babel#21]
To prevent from trying to compile `*.js` files, I added a `.babelrc` file with the following contents:
```
{
   "only": [ "*.es6" ]
}
```
This seems to be ignored, as I still get the error message "Transpiled file would overwrite source file. Aborted!" when editing a `*.js` file (in my case the `Gruntfile.js`).
In my setup I want all `*.es6` files to be compiled to `*.js` files located next to their according source file.

I had a look at your source code at differently tagged versions and I saw, that reading the babelrc file was dropped starting with version 0.8.0. How is it supposed to work now?

**Comment by gandm** [comment]
`.babelrc` files aren't ignored. babel-core still reads them as you would expect. The `internal scanner` was dropped in v0.8.0 for other reasons.

The example you gave above is working - the `.babelrc` file is read and no transpile is taking place but I'm not responding correctly. This is a bug and I will fix now.

There is an easier way to do what you want. just turn on the `Disable When No Babelrc In Path` option in the language-babel settings. You don't need any `.babelrc` file at all then.

**Comment by alex3683** [comment]
Ah, okay. Seems I just don't know enough about babel-core :-) Thanks for finding and fixing the real issue.

The `Disable When No Babelrc In Path` option is not really suitable in my case, as some es6 and plain js sources are mixed within my project (one can argue, whether this is a good idea or not, but that's the way it is ;-))

**Comment by gandm** [comment]
Hope that works.

**Comment by alex3683** [comment]
Indeed, it does. Thanks!
