### ISSUE TITLE
JSX indentation improper via  Lines->Auto Indent

### ISSUE THREAD

**Issue by expaand** [gandm/language-babel#214]
I have a file containing many sections of JSX code as returns from render methods, etc. If I "select all" to select the entire file, and go to Lines->Auto Indent, all of the JSX gets re-indented to to be flush, with none of the hierarchy showing. However, if I go and **click** at the bottom of each JSX set, the set immediately indents properly. So I have to go through and click at the bottom of each set in order to have a file with consistent/correct indentation.

**Comment by gandm** [comment]
`Lines->Auto Indent` is an Atom command which I would have to patch to my code. I would have to then parcel up the indentation into multiple blocks. JSX and non JSX and then proceed to indent each individually. Seems like a lot of work particularly as many people use a beautifier to do this.

As you rightly say, if my package has autoIndentJSX turned on then positioning at the bottom of eack block will re-indent it.

I'm not sure of the demand for this? I'll leave this open to gauge the response.

**Comment by gandm** [comment]
Taking a quick look at this it may be easier than I thought.

**Comment by gandm** [comment]
I've just published 2.31.0 that should autoindent jsx when indenting a complete file. It works by letting Atom indent the whole file and then parsing the file again to indent the JSX parts. I tested it with a 5000 line file with about 50 JSX blocks. Let me know how it goes.
