### ISSUE TITLE
Cannot enable tag autoclose

### ISSUE THREAD

**Issue by Stormcore** [gandm/language-babel#216]
Hello, I cannot find where to enable tags auto closing

**Comment by gandm** [comment]
Providing:-
- language-babel is enabled for the file as shown by `Babel ES6 JavaScript` being displayed in the bottom right status bar.
- The Atom provided package [autocomplete-plus](https://github.com/atom/autocomplete-plus) is enabled.
- It is a JSX tag you care closing ( not an XML/HTML tag)

It should be automatic. When a `>` is entered closing a JSX tag, a list of enclosed tags will appear as autocomplete list which, by default, can be selected by pressing arrow/tab.

**Comment by gandm** [comment]
I presume this has answered your question.

**Comment by kentcdodds** [comment]
Any chance this could get reopened and discussed for support in script tags in an HTML file?

![example](https://user-images.githubusercontent.com/1500684/31313856-270c46e4-abad-11e7-8361-1cf439fd98af.gif)

As the gif indicates, the autosuggestions don't appear when in a script tag in an html file. I'm doing this for creating educational material on React and it'd be really nice to get that autocomplete :)

**Comment by kentcdodds** [comment]
Also, I'm not sure whether it's a related issue, but syntax highlighting doesn't quite work the same in this context either :-(

<img width="506" alt="screen shot 2017-10-07 at 10 19 02 pm" src="https://user-images.githubusercontent.com/1500684/31313871-9a1b463a-abad-11e7-92de-dbf22089fdcc.png">

**Comment by gandm** [comment]
@kentcdodds I don't support HTML files. The original opener was asking why tag autoclose wasn't working and as I indicated -

> It is a JSX tag you are closing ( not an XML/HTML tag)

Obviously, the second gif above is HTML and looking at it it isn't language-babel doing the processing of the file. I can tell because the `type` attribute isn't in italics and `function Stopwatch...` is highlighted. I guess you are using language-html. 

The default language-html supports this by passing off to language-javascript. Unfortunately, language-javascript doesn't support  JSX but maybe you can raise a request to have it added?

**Comment by kentcdodds** [comment]
Ah, that's helpful, thank you @gandm. I wonder if perhaps I could have `language-html` pass off javascript to `language-babel` instead of `language-javascript` 🤔 

Thanks again! This is such a needed plugin. Very enabling. Thank you again very much!

**Comment by kentcdodds** [comment]
I tried it with [this commit](https://github.com/kentcdodds/language-html/commit/55d7700a8adeea200e268eb5cde02e393cdb9c49) and pulled it up locally. It seems to be working! Highlighting looks perfect!

<img width="496" alt="screen shot 2017-10-08 at 1 21 04 am" src="https://user-images.githubusercontent.com/1500684/31314801-06a8aac2-abc7-11e7-8242-334bf717570b.png">

Except the autosuggest is not :-(

![auto-suggest-no-working](https://user-images.githubusercontent.com/1500684/31314805-2f2ef41a-abc7-11e7-9898-cc43879c2502.gif)

I'm not seeing any console errors or anything so I'm guessing there's something else missing. Any tips?

Thanks again!

**Comment by gandm** [comment]
@kentcdodds I doubt the Atom team would allow `language-html` to pass control to a non-Atom package. You could fork `language-html` and change this [line](https://github.com/atom/language-html/blob/master/grammars/html.cson#L301) to `"source.js.jsx`". I think that should call my grammar but I don't think the autocomplete of JSX will work. 

Just as I was typing this I saw your latest post. Probably best not change line 279.

**Comment by kentcdodds** [comment]
Sounds good. Anything I can do to make autocomplete work?

**Comment by gandm** [comment]
@kentcdodds I could probably remove this [line](https://github.com/gandm/language-babel/blob/master/lib/auto-complete-jsx.coffee#L23) and then it would work. But it may have some other undesired effects depending on what other packages are installed - not sure.

**Comment by kentcdodds** [comment]
What if I publish `language-html-babel` then we change that line to (the CoffeeScript equivalent of):

```javascript
const pkgName = editor.getGrammar().packageName
if (pkgName !== "language-babel" && pkgName !== "language-html-babel") {
  return
}
```

Would you be open to doing that?

**Comment by kentcdodds** [comment]
I published `language-html-babel`: https://github.com/kentcdodds/language-html-babel

**Comment by gandm** [comment]
I will either remove the line or add the additional language-html-babel check in the next release of `language-babel`

**Comment by gandm** [comment]
Just commited https://github.com/gandm/language-babel/commit/c3641b84cd3a46a5c6cf7aff27337e5396992687

**Comment by kentcdodds** [comment]
Thanks! This is working great :+1:
