### ISSUE TITLE
JSX closing tags styling issue

### ISSUE THREAD

**Issue by roman01la** [gandm/language-babel#217]
When I enable `language-babel` I can see that every closing tag in JSX is being displayed incorrectly. You can see how tag name becomes semi-transparent and pushed out of angular brackets to the right.

<img width="336" alt="screen shot 2016-07-19 at 2 47 40 pm" src="https://cloud.githubusercontent.com/assets/1355501/16948893/0259f306-4dc0-11e6-9cff-6dde73c24e18.png">

**Comment by gandm** [comment]
See https://github.com/gandm/language-babel/issues/141

**Comment by roman01la** [comment]
@gandm oooh, thanks! 👍🏻
