### ISSUE TITLE
Add a whitespace beginning a comment

### ISSUE THREAD

**Issue by zhiquan-yu** [gandm/language-babel#218]
[Requires or disallows a whitespace (space or tab) beginning a comment (spaced-comment)](http://eslint.org/docs/rules/spaced-comment)

**Comment by gandm** [comment]
Not sure what you are saying. The link above is to an eslint rule!

**Comment by gandm** [comment]
I've just published 2.32.1, which adds white space to JSX commenting so as to be consistent with normal JavaScript commenting. However, it doesn't read eslint rules to determine the correct type of spacing to use.
