### ISSUE TITLE
Self-Closing Div

### ISSUE THREAD

**Issue by mcmar** [gandm/language-babel#219]
In JSX, `<div className="foo" />` is totally valid and equivalent to `<div className="foo"></div>`. The latter is recognized by bracket-matcher, but the former is not. I recognize that self-closing divs generally aren't considered "valid" HTML5, but JSX has decided that all tags are self-closing. I would love for either language-babel or bracket-matcher to fix this or you guys can collaborate on a fix. I don't really know if this belongs to your package or theirs, but one way or the other, I'd love to have my perfectly valid JSX be recognized as such. Thanks!

**Comment by gandm** [comment]
I'm not entirely sure what you are saying. My grammar recognises self closing jsx as described above, whether it is HTML5 or a 'real' JSX component. 'Maybe you can provide an example of the issue you are facing?

**Comment by gandm** [comment]
Maybe you are referring to matching brackets, as mentioned in [this issue](https://github.com/gandm/language-babel/issues/84) and [this bracket-matcher issue](https://github.com/atom/bracket-matcher/issues/115)?  If so, the issue should be lodged there.

**Comment by gandm** [comment]
Closing this issue as it appears to be another package. Re-open if you feel the need.
