### ISSUE TITLE
import to vscode

### ISSUE THREAD

**Issue by rickmed** [gandm/language-babel#220]
How easy/hard would it be? Is all the grammar info contained in the tmlanguage file?

**Comment by gandm** [comment]
Looks like someone has already done this [here](https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring). I don't think the author was  aware it was my grammar that he ported.  He has taken the grammar from Facebook's flow extension on vscode. As Facebook's nuclide uses my grammar for JavaScript he got it by default. 

I'm not sure what version of my grammar they used as the starting point but I guess it is quite old. I think the vscode flow extension that Facebook developed is no longer supported.

You can easily create a new vscode extension by using the vscode yeoman generator. My language JSON files should be mostly ok as-is. They are textmate language files, but you may want to review the code where I nest the atom moustache grammar to support angular templates, as this won't be available in vscode.

Why do you want a grammar that supports flow inside vscode? Wouldn't it be better to use [nuclide](https://nuclide.io/docs/quick-start/getting-started/)?

**Comment by rickmed** [comment]
I tested that packaged and it is not quite as your atom package. There are ~300 loc missing on the language JSON -so maybe he is using an old version.

In the meantime, I created an extension (and a modified monokai theme to color a few things) with your new file locally. Do you mind if I upload it to the marketplace? The downside is that all the jsx indenting, commenting, etc will not be there since I don't have time now to learn how to do it in vscode.

**Comment by gandm** [comment]
No I don't have an issue with that. I'm not sure how you will track changes to my grammar.

**Comment by gandm** [comment]
Not sure about tracking changes. I guess you are modifying some parts of my grammar? E.g. names of language, id, removing moustache requirement. As for the best way to do this, I'm not sure there's a simple way of doing it as I never expected anyone to branch to a different editor.  I guess clone as is, branch, remove atom type files, add vscode files and then sync your branch periodically and merge to your code base? 

Good luck. Let me know if you don't understand something or need help with the grammar.

**Comment by rickmed** [comment]
I think I'll put it on hold. No time for it atm. Was trying vscode but will stay with atom atm.

Thanks for the quick responses/help!

**Comment by gandm** [comment]
Ok. If I have some time I may look at doing it as the Facebook flow project for vscode seems to have recent amendments. I had a quick look at the API for vscode and it can do some of things I require but maybe not all. Needs investigating but don't hold your breath.

**Comment by rickmed** [comment]
In the meanwhile, I forked a monokai theme that colors specific scopes of this grammar

https://atom.io/packages/monokai-dark-plus
