### ISSUE TITLE
tsx file comment issue

### ISSUE THREAD

**Issue by silentcloud** [gandm/language-babel#223]
react typescript file (.tsx):

![image](https://cloud.githubusercontent.com/assets/1698185/17430079/e69c5a24-5b24-11e6-8519-47a3542d753b.png)

**Comment by gandm** [comment]
Not quite sure what you are saying. 

You can't comment JSX nested components using `//` commenting as it is treated as literal text, [See this where the comment is compiled a literal string](http://babeljs.io/repl/#?evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=true&loose=false&spec=false&playground=false&code=let%20jsx%20%3D%20(%0A%20%20%3Cdiv%3E%0A%20%20%20%20%2F%2F%20%3Cdiv%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20)%0A)

You must use `/* */`.  This package will choose the correct type of commenting if you use the commenting keybinding `crtl /` or `cmd /`

**Comment by silentcloud** [comment]
@gandm Sorry, my description was not clear. 

I mean `cmd /`  can be used with react typescript file ( file with .tsx suffix )

https://www.typescriptlang.org/docs/handbook/jsx.html

![image](https://cloud.githubusercontent.com/assets/1698185/17431663/abb28038-5b2d-11e6-80ae-5831ceea2091.png)

**Comment by gandm** [comment]
language-babel supports `cmd /` and it works with tsx files. Maybe you don't have my grammar enabled for the file. When editing does the lower right status bat display `Babel ES6 JavaScript`? If not then you are using another grammar.  ![image](https://cloud.githubusercontent.com/assets/2313237/17431848/e736138e-5af3-11e6-83ce-92430eff19c4.png)


The gif shown in  my previous comment is your `.tsx` file toggling `cmd /` and it works.

**Comment by silentcloud** [comment]
![image](https://cloud.githubusercontent.com/assets/1698185/17432054/baa757ce-5b2f-11e6-838e-03af8fa3d994.png)

Thanks, the grammar is wrong

**Comment by gandm** [comment]
No problem, easily done. I don't use typescript but If you are using the atom-typescript package then I'd imagine you'd miss many of it's features by using my grammar.
