### ISSUE TITLE
Diacritics followed by spaces breaks highlighting. 

### ISSUE THREAD

**Issue by wiredmax** [gandm/language-babel#225]
![selection_001](https://cloud.githubusercontent.com/assets/2067331/17737652/f2d8c4fe-645b-11e6-9f0c-f3102d766b09.png)

If I replace the `é` in `Opportunité de vente` by a regular `e` syntax highlighting works again. The word `Opportunité` alone doesn't break the highlighting.

 I'm using the latest version `2.32.2`

**Comment by gandm** [comment]
I have no problem. Are you are sure you are using my grammar `Babel ES6 JavaScript` showing on bottom right statius bar?
![image](https://cloud.githubusercontent.com/assets/2313237/17738532/7d2b4b5e-6489-11e6-89b8-060c64f6d4b7.png)

**Comment by wiredmax** [comment]
Yes, 100% sure.

![selection_002](https://cloud.githubusercontent.com/assets/2067331/17738888/1988ae8e-6461-11e6-9292-680d855a88c3.png)

![selection_003](https://cloud.githubusercontent.com/assets/2067331/17738892/1ce320b4-6461-11e6-9123-fec1bd26746f.png)

**Comment by gandm** [comment]
Can you let me have your source code for this file, or a section that still shows the issue?

**Comment by wiredmax** [comment]
https://gist.github.com/wiredmax/f9326ca54c8ecaffe84077a47ed3d64c

**Comment by gandm** [comment]
No that file works fine for me! See below. 
![image](https://cloud.githubusercontent.com/assets/2313237/17739770/16ad0610-648e-11e6-92f0-dc66fa46cc3b.png)

**Comment by gandm** [comment]
What theme are you using? What packages have you loaded?

**Comment by wiredmax** [comment]
I'm using OneDark, but I have the issue with the default theme also. I've tried on a "vanilla" atom with all the plugin disabled (except the core ones) and I still got the issue. Next step I intend to try on another computer at home later today with a clean installation of Atom.

**Comment by gandm** [comment]
OK thanks. Below is One Dark with your gist, atom 1.9.8 and language-babel 2.32.2
![image](https://cloud.githubusercontent.com/assets/2313237/17741159/07728792-6493-11e6-8acf-0ab648f8c551.png)

**Comment by gandm** [comment]
Maybe you could determine the scope active for the `de` word in the string by positioning the cursor between the `d` and `e` and pressing `cmd-alt-P` or `ctrl-alt-P`  This may give a clue as to what package, if any, is changing the scope of the string.

**Comment by gandm** [comment]
Closing this issue. Add additional information if you wish to re-open.
