### ISSUE TITLE
Flow styling issue

### ISSUE THREAD

**Issue by ooflorent** [gandm/language-babel#227]
When using generics, some patterns cause styling issue:

![flow_styling_issue](https://cloud.githubusercontent.com/assets/168498/17806952/de0ad1cc-6607-11e6-9cfc-f3f3195aa6f2.png)

Enabling `Use Shadow DOM` does not change anything.

**Comment by gandm** [comment]
Um! I'm not expecting the parens!  Any reason for using them? 
This works
```
declare var foo: <T>(x: T) => T;
declare var bar: number;
```

**Comment by ooflorent** [comment]
This (combining types):

```js
declare var foo: ((<T>(x: T) => T) & (<T,U>(x: T, y: U) => U);
```

Since it is valid syntax, `language-babel` should style it right 😉

**Comment by gandm** [comment]
Yeah agreed. It's not the parens causing it but the generic notation <T> that;s doing something weird. I'll take a look at this.

**Comment by gandm** [comment]
Can you check 2.23.4 to see if it solves your problem. Amazed no one other than yourself has picked up on this! Thanks for the report.

**Comment by ooflorent** [comment]
Seems to work now! Thanks
