### ISSUE TITLE
Error update Atom v1.9.9

### ISSUE THREAD

**Issue by tcelestino** [gandm/language-babel#228]
When I will update language-babe packages, happens the error below:

![screen shot 2016-08-21 at 5 56 15 pm](https://cloud.githubusercontent.com/assets/190265/17839763/a3c2d0a6-67c8-11e6-80f5-ea4fc8a997b4.png)

**Comment by gandm** [comment]
Looks like an atom issue of some sort and nothing to do with language-babel. I suggest closing all atom editors and manually removing `/Users/tclestino/.atom/language-babel`, restarting atom and reinstall language-babel using either atom via the GUI for via `apm install language-babel`
