### ISSUE TITLE
Highlighting of uppercase (constant) variable name.

### ISSUE THREAD

**Issue by Moeriki** [gandm/language-babel#229]
I hope I'm in the right location for this report.

![image](https://cloud.githubusercontent.com/assets/38758/17847190/ffe90128-684c-11e6-9555-584209afcb2f.png)

I'm working on a syntax theme.

**As** an uppercase variable declaration gets `.variable.other.constant`, **I expect** an uppercase variable used to call a function on to also get `.variable.other.constant`, **but actually** I get `.variable.other.class` in the above example.

I understand the first uppercase letter and the function call on it marks it as a class, and it would be (kind of) right to do so. But given the all uppercase would it be an option to mark it as a constant as well?

**Comment by gandm** [comment]
Yes I agree. I'll take a look at this, probably at the end of the week. Thanks.

**Comment by gandm** [comment]
Fixed in 2.34.0
