### ISSUE TITLE
language-babel does not appear in package manager

### ISSUE THREAD

**Issue by cperryk** [gandm/language-babel#23]
I'm not sure if this is a language-babel issue or a package manager issue, but `language-babel` does not appear in the package manager, and it seems to be the only package I have that's doing that. I'm using Atom 1.0.2 on OS X 10.11. Right now, the only way I can edit the package settings is by searching for the package on the "install" tab.

**Comment by cperryk** [comment]
Never mind! Uninstalling and reinstalling language-babel fixed this.

**Comment by cperryk** [comment]
Just kidding. After restarting Atom, language-babel fails to appear in package manager.

**Comment by gandm** [comment]
Never heard of this issue. 
Does `apm list` show `language-babel`? 
Can you use `apm uninstall language-babel` and then `apm install language-babel` see if that fixes it? If you load atom and start a chrome inspector window - `developer/toggle developer tools` -  then `reload` atom via menu, do you see any console errors?

**Comment by gandm** [comment]
I suspect it's an issue with https://github.com/atom/settings-view as there is nothing a package can do that can cause this ( I hope :-) )
maybe related to -
https://github.com/atom/settings-view/issues/573 
This is thje reverse of what you see? https://github.com/atom/settings-view/issues/479

**Comment by cperryk** [comment]
Maybe it is related to those issues, but I AM seeing the settings button in the install view. The problem is I'm only seeing the package [appear in the install view](https://www.dropbox.com/s/da00e6aeun1h33b/Screenshot%202015-07-15%2010.34.50.png?dl=0), not the [packages view](https://www.dropbox.com/s/49bin09634x6fo3/Screenshot%202015-07-15%2010.35.34.png?dl=0).

`apm list` shows `language-babel`.

I've reinstalled it with `apm`, but with no luck.

I'll post an issue to settings-view.

**Comment by gandm** [comment]
> but to be clear I AM seeing the settings button in the install view

That's why I said the reverse of your problem.

The stack trace looks to be an issue in the package manager area. As I said there is very little a package can do to display settings, it's pure atom. I'll leave this open until I hear otherwise.

**Comment by gandm** [comment]
You may want to disable or uninstall task-list as it seems to have an issue. 

Seems like this https://github.com/kenwheeler/task-list/issues/18

**Comment by cperryk** [comment]
Ah, uninstalling task-list did the trick. Thanks for the help!
