### ISSUE TITLE
JSX if-else indentation

### ISSUE THREAD

**Issue by kwall2004** [gandm/language-babel#230]
Within JSX, a return statement is not indented properly if it is in an else block:

![image](https://cloud.githubusercontent.com/assets/19229852/17905659/d41fb87a-6941-11e6-998a-1d131bf0d00a.png)

**Comment by gandm** [comment]
Can you let me have the whole jsx block including the outermost jsx?

**Comment by kwall2004** [comment]
![image](https://cloud.githubusercontent.com/assets/19229852/17929370/1bad7f56-69ce-11e6-9738-016342e03672.png)

**Comment by gandm** [comment]
Thanks for that. I have a fix for this that I'll role out before the weekend.

**Comment by gandm** [comment]
Fixed in 2.34.0
