### ISSUE TITLE
Constants declaring an Arrow function are not always highlighted correctly

### ISSUE THREAD

**Issue by leonardfactory** [gandm/language-babel#235]
### Description
When defining a costant that is an arrow function, i.e. like `const fn = () => {};`, `fn` is highlighted correctedly as `function name` an the block as `meta arrow`.

However, if the arguments are provided on **next line**, grammar doesn't recognize the arrow function.

I'm going to fiddle with the grammer trying to find some hints. If I can help in any other way please let me know!

### Versions

- Atom 1.9.9
- `language-babel` 2.34.0

### Screenshot
<img width="228" alt="schermata 2016-08-27 alle 02 38 49" src="https://cloud.githubusercontent.com/assets/1857445/18023877/8b41bdc2-6bff-11e6-9097-3dca591eb364.png">

* Not recognized
  ```html
   <span class="source js jsx">
     <span class="keyword control module js">export</span> 
     <span class="storage type js">const</span> 
     <span class="variable other readwrite js">fn2</span> 
     <span class="keyword operator assignment js">=</span>
   </span>
   ```

* Recognized
   ```html
   ...
   <span class="meta function arrow js">
      <span class="entity name function js">fn</span> 
      <span class="keyword operator assignment js">=</span> 
      <span class="punctuation definition parameters begin js">(</span>
      <span class="punctuation definition parameters end js">)</span> 
      <span class="storage type function arrow js">=&gt;</span>
   </span>
   ```

### Sample

Highlighted correctedly:

```js
export const fn = () => {};
```

Not recognized:

```js
// 1
export const fn =
  () => {};

// 2
export const fn = (arg1,
                   arg2) => {};
```

**Comment by gandm** [comment]
Yes I'm aware of this issue but there is nothing that can be done to fix it. Atom ( TextMate ) grammars process line by line and it is impossible to go backwards to scope a previous line on the discovery of a later token.  I would love it if this were not the case!!

In future Atom may use an [incremental AST parser](https://github.com/tree-sitter) to define grammars, in which case, this would be possible, but I'm afraid this is a way off.

**Comment by leonardfactory** [comment]
Thank you for your fast response! I tought about something like this.. well, we will wait.
PS: Congrats for this awesome package 😄
