### ISSUE TITLE
Improve ES6 shorthanded object literal scope/color

### ISSUE THREAD

**Issue by daltones** [gandm/language-babel#239]
![captura de tela de 2016-08-31 12-39-58](https://cloud.githubusercontent.com/assets/5603632/18135435/4c9e0ebe-6f78-11e6-8094-b8452ac8946c.png)

I don't know if it's just me, but when I see this pattern it looks very weird. `age` is a variable, but it's also an object key. I think the key behavior in this case is "more important" and should be highlighted green too.

![captura de tela de 2016-08-31 12-55-24](https://cloud.githubusercontent.com/assets/5603632/18136010/3b49f388-6f7a-11e6-9e99-61a1fd156e2c.png)

In the example above, green shorthanded object literals would be easier to differentiate an object from an array.

Looking at the scopes, normal keys are:
- `source.js.jsx`
- `constant.other.object.key.js`
- `string.unquoted.js`

And shorthanded object literals are:
- `source.js.jsx`
- `variable.other.readwrite.js`

So thinking about scopes, these shorthanded terms aren't represented good enough.

**Comment by gandm** [comment]
Yes, sounds reasonable. I'll take a look but there may be an issue with destructuring syntax.

**Comment by gandm** [comment]
@daltones @Moeriki  it is syntax like....
```
var { foo, bar } = { foo: "lorem", bar: "ipsum" };
console.log(foo);
// "lorem"
console.log(bar);
// "ipsum"
```
That needs thinking about. I presume we should leave `foo` and `bar` as variables?

**Comment by daltones** [comment]
Yes, I think destructuring is perfect as it is. :+1: 

Including nested destructuring:
![captura de tela de 2016-08-31 20-01-58](https://cloud.githubusercontent.com/assets/5603632/18149307/d14949fc-6fb5-11e6-986a-09061c5718a3.png)

**Comment by Moeriki** [comment]
Destructuring is fine.

<img width="587" alt="screen shot 2016-09-01 at 08 52 28" src="https://cloud.githubusercontent.com/assets/38758/18158121/7b325b00-7021-11e6-89d9-766ca523d7f3.png">

As for object-property shorthands I changed my mind. Though it might be possible the class should be slightly updated. I prefer it to be highlighted as a regular variable.

**Comment by gandm** [comment]
Sorry I wasn't clear. Currently the destructuring and object literal regex grammar use the  same 'code' path. If I change object literal to be highlighted differently this would have to change. In the current code also have to make a distinction for how the flow type of an object literal is presented.

E.g let a: {foo: string} ={foo: 'i am a string'}

I think this proposed change would make things more difficult, although not impossible.

**Comment by daltones** [comment]
Okay, I didn't know the patterns work and I understand these limitations.
But a more specific scope for those literals would be a nice improvement, and then people could change the highlighting as they want. So maybe some time in the future… =)

Thanks!

**Comment by gandm** [comment]
In 2.37.0 I have scoped object literal shorthand properties with an additional css class id of `shorthandpropertyname` This allows the current themes to work unchanged but also allows users who prefer to add a scope to the styles.less file with any styling they require. I think this should be acceptable.

**Comment by daltones** [comment]
Thanks a lot! =)
