### ISSUE TITLE
Highlighting GraqphQL queries

### ISSUE THREAD

**Issue by tonyxiao** [gandm/language-babel#242]
For es6 tagged strings starting with `Relay.QL` or `gql`, 
Related
* https://github.com/atom/language-javascript/pull/362 
* https://github.com/rmosolgo/language-graphql/issues/2

PS: Is there a way to highlight SQL queries already?

**Comment by gandm** [comment]
I'll add a Relay.QL and gql tag`` option to the grammar. 

No way to highlight sql queries. I could add another template sql`` and call `language-sql` to highlight it but it would mean adding a sql function that passes back the ddl/query string. But using this tag name makes a big assumption that the template contains sql.

**Comment by tonyxiao** [comment]
There are a few relatively [unknown libraries ](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=es6%20sql%20tag) trying to add tagged sql strings but they don't have much attention at all relative to `Relay.QL` or `gql`. Ideally there's a way for users to specify which language plugin they want to use for syntax highlighting for any given tag.

**Comment by tonyxiao** [comment]
Is that possible in Atom?

**Comment by gandm** [comment]
No it's not really possible to make it configurable as it would mean dynamically patching the grammar, and that has other attendant issues, such as running the specs.

**Comment by gandm** [comment]
I've added support for Relay.QL and gql template strings which uses `language-graphql` but it seems to have a problem!

I tested using the following code.
```
var node = Relay.QL`
  node(123) {
      ${Relay.QL`
      name: User {
        address {
          ${fragment},
        },
      }
    `}
  }
`;
```

This nests a Relay.QL template, but `language-graphql` doesn't support the `${}` interpolation, and also it doesn't give me control back so that I can support it.
This is what it shows me - Is this all you would expect?
![image](https://cloud.githubusercontent.com/assets/2313237/18254337/a2c7259e-7394-11e6-80c6-17214d008ccd.png)
or in One Dark theme
![image](https://cloud.githubusercontent.com/assets/2313237/18254352/ce830e64-7394-11e6-94fd-2f487ce65523.png)

**Comment by tonyxiao** [comment]
I think you're actually expected to use query variables rather than directly do string interpolation. http://docs.apollostack.com/apollo-client/core.html#query So yea not supporting `${}` interpolation isn't ideal but probably isn't gonna matter too much in practice.

**Comment by gandm** [comment]
Just rolled out 2.37.0 that has support for `Relay.QL` and `gql` tagged templates. Also comments code inside these templates with a `#` style comment.

**Comment by jquense** [comment]
👋  hi there, It seems like this update actively makes these queries less readable. My interpolations are now blending in completely to the rest of the string template, whereas before it correctly did normal js syntax highlighting inside the `${}` like a normal template literal. Am i correct that this edit is the cause or am I in the wrong place, and if it is right can we please get highlighting back inside the expression?

**Comment by jquense** [comment]
> I think you're actually expected to use query variables rather than directly do string interpolation. 

that's not quite right, relay requires you do interpolation here for composing fragments:

```js
Relay.QL`
      fragment on AnalysisImage @relay(plural: true) {
        ${AnalysisImagePlot.getFragment('image')}
        extension
        href
      }
    `,
```

**Comment by tonyxiao** [comment]
Hmm maybe we should either disable syntax highlighting for `Relay.QL` or figure out how to support the string interpolation syntax inside [language-graphql](https://github.com/rmosolgo/language-graphql)?

**Comment by gandm** [comment]
Ok, I'm not a relay user but I would agree that the language-graphql package doesn't seem to add much in the way of syntax highlighting and also means I loose control over interpolation. There are no sensible ways to support an embedded language inside a template literal unless it is done natively inside language-babel.  I could do a or against the language-graphql grammar so that when a ${} is found he passes control back to me. That would work, but I doubt the author would accept that PR.

I need a view as to what I should do. Revert back to normal template highlighting or follow on this course

**Comment by gandm** [comment]
I just took a look a the graphql spec and it is pretty simple. I've decided I'll support it directly inside my grammar. I'll then support interpolation and nested queries. Hopefully, I'll release this by the weekend.

**Comment by gandm** [comment]
@tonyxiao @jquense @jonboiser 2.39.0 has native support for GraphQL inside Relay.QL and gql tagged template strings.  Also supports interpolation and the correct commenting using the Atom keyboard shortcut. I'm not sure on the scopes of the various components - should some bits be function, variables, types,, being unfamiliar with GraphQL. I'm also a bit hazy on some of the grammar as it seems to be a work in progress as far as the [spec](http://facebook.github.io/graphql/) is concerned.

**Comment by jquense** [comment]
looks great! so far it's working nicely for me :) thanks!

**Comment by tonyxiao** [comment]
This is wild @gandm!

**Comment by gandm** [comment]
Just tweaked the grammar and added a /* Graph QL /* as a template prefix. See https://github.com/gandm/language-babel#graphql-code-highlighting

**Comment by tonyxiao** [comment]
Wow that's awesome. Thank you @gandm !

**Comment by gandm** [comment]
@tonyxiao @jquense FYI, for consistency I've just published a new package, language-graphql-lb, which is the grammar graohql from inside language-babel, but it supports `.graphql` and `.gql` files. I.e. without JavaScript and flow.

**Comment by gre** [comment]
How modular is this feature? I was wishing to work on something similar soon and I wish I can write a plugin that can extend support for it.
I can see that there are still some reference of "graphql" in the language-babel plugin: https://github.com/gandm/language-babel/search?q=graphql&utf8=%E2%9C%93 , does that mean I will have to do the same and PR to this lib? (but will it get accepted?)

my need:

```glsl
// js code here...
// then...
var fragmentShader = GLSL`
precision highp float;
varying vec2 uv;
void main () {
  gl_FragColor = vec4(uv.x, uv.y, 0.5, 1.0);
}
`
```

**Comment by gandm** [comment]
@gre Quite simple to do this - Look at the [this section of the readme](https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions)

e.g.
![image](https://cloud.githubusercontent.com/assets/2313237/19685340/ee16b9b0-9ab3-11e6-8fc5-dbfc651c0dd1.png)

Gives
![image](https://cloud.githubusercontent.com/assets/2313237/19685349/f760c51a-9ab3-11e6-82a4-f26ad7e3f03e.png)

**Comment by gre** [comment]
@gandm thanks, awesome!

**Comment by gre** [comment]
@gandm it works great in your own config, but it does not seems to work in a project `.languagebabel`, should I create an issue?

```
{
  {"taggedTemplateGrammar":["GLSL:source.glsl"]}
}
```

**Comment by gre** [comment]
oops hold on

**Comment by gandm** [comment]
Look at this section of the readme https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions

Sent from my Windows Phone
________________________________
