### ISSUE TITLE
When attempting to compile my es6 code

### ISSUE THREAD

**Issue by neekon91** [gandm/language-babel#243]
Atom gives me the error  :
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall babel
    npm install babel-cli

See http://babeljs.io/docs/usage/cli/ for setup instructions.

I have followed the steps and still get the same error back

**Comment by gandm** [comment]
I'm not sure what you are saying? My package doesn't use either `babel` or `babel-cl`i, it uses `babel-core`. You say Atom is giving you this error, how and when? How are you trying to compile code?

**Comment by gandm** [comment]
I'll close this issue as it doesn't appear related to `language-babel`.
