### ISSUE TITLE
JSX indentation

### ISSUE THREAD

**Issue by kwall2004** [gandm/language-babel#246]
I'm not sure if this changed in the most recent update or what.  It had been working.  But I'm getting inconsistent indentation in return statements now:

![image](https://cloud.githubusercontent.com/assets/19229852/18274011/4dc83162-740e-11e6-91b1-f59fe0e10e8e.png)

**Comment by gandm** [comment]
I'm expecting an `else` clause on the second return shown above. It's never worked without an explicit `else` as a means of resetting the language indentation.

**Comment by kwall2004** [comment]
Ahhh, yes.  Ok, thanks.

**Comment by gandm** [comment]
Is this case something you want supported?

**Comment by kwall2004** [comment]
I actually put the else back in and that's fine with me.  I could see it coming up in some other case though.

**Comment by gandm** [comment]
Yeah!  I've actually just made a commit https://github.com/gandm/language-babel/commit/01db126882dac7fb9cb023d72859588d5c39f296 with a change to support this. Not sure when I'll publish as I know people get annoyed when I update frequently.

**Comment by kwall2004** [comment]
:-)

(FWIW, frequent updates don't bother me...)
