### ISSUE TITLE
ES6 classes: flowtype-annotated members not highlighted if following non-annotated members

### ISSUE THREAD

**Issue by jonboiser** [gandm/language-babel#248]
<img width="461" alt="screen shot 2016-09-10 at 10 42 30 pm" src="https://cloud.githubusercontent.com/assets/10248067/18415008/f6bce24e-77a7-11e6-8fcf-249e4e196249.png">

**Comment by gandm** [comment]
Thanks for the report. 2.37.1 fixes this issues.
