### ISSUE TITLE
Flowtype highlighting off in Classes with @-decorators and assigned members

### ISSUE THREAD

**Issue by jonboiser** [gandm/language-babel#249]
Thanks for getting a fix to #248 out so quickly!

Version 3.7.1 does fix the example I posted, but I've noticed that the bug persists with a very specific arrangement using decorators and assigned class members. I can't describe it exactly, so hopefully the screenshot makes sense. (I'm working on a project using mobx, which provides a `@observable` decorator):

<img width="497" alt="screen shot 2016-09-11 at 11 26 56 am" src="https://cloud.githubusercontent.com/assets/10248067/18418797/af8878fa-7812-11e6-838e-e4d3fc713edc.png">

**Comment by gandm** [comment]
Ok i'll take a look. It's quite tricky when the code is using ASI as I have to determine when a new statement starts without having a nice semi-colon to let me know. Not an issue when using an AST based parser but difficult when using textmate grammars as used in Atom. It looks straightforward though.

**Comment by jonboiser** [comment]
You're right that there isn't a problem when you put the semi-colons in,
which is what I normally do. My ESlint config apparently doesn't require
them inside of classes.

**Comment by gandm** [comment]
This should be fixed in 2.38.0
