### ISSUE TITLE
How do I configure snippets?

### ISSUE THREAD

**Issue by hnordt** [gandm/language-babel#250]
Hello.

How do I configure snippets? Here's what I'm trying:

```coffee
".source.js.jsx":
  "JSX Debug":
    "prefix": "jsxd"
    "body": "<pre>{JSON.stringify($1, null, 2)}</pre>"
```

It's not working :(

**Comment by gandm** [comment]
It works for me. Do you have the correct grammar selected?
![snippet](https://cloud.githubusercontent.com/assets/2313237/18420747/9cb10cce-7871-11e6-84c3-8c26f43e658c.gif)

**Comment by hnordt** [comment]
Wierd... I do have selected the correct grammar :/

**Comment by gandm** [comment]
Maybe you have the same scope twice in your snippets file, as in this https://discuss.atom.io/t/why-isnt-doesnt-this-snippet-work/15922/2

**Comment by hnordt** [comment]
That's my full snippets.cson file:

```cjson
'.source.jsx.jsx':
  'JSX Debug':
    prefix: 'jsxd'
    body: """<pre>{JSON.stringify($1, null, 2)}</pre>"""
```

**Comment by gandm** [comment]
Ah. Your scope is `.source.jsx.jsx` rather than `.source.js.jsx`

**Comment by hnordt** [comment]
Err, sorry, I changed to `.source.js.jsx`, same problem, but probably it's my Atom config...

**Comment by hnordt** [comment]
@gandm I had to restart Atom to make it work lol

Thank you!

**Comment by gandm** [comment]
That's strange, it's all dynamic for me; no need to restart/reload. Anyway, glad it's working.
