### ISSUE TITLE
Division on new line breaks highlighting, content below slash shown as regex.

### ISSUE THREAD

**Issue by geksilla** [gandm/language-babel#255]
language-babel version 2.42.0. Please look on screenshot
![atom-lang-babel](https://cloud.githubusercontent.com/assets/3911882/18923287/60ddaf54-85b4-11e6-83aa-a2b59f1d8505.png)

**Comment by gandm** [comment]
Released in 2.42.2

**Comment by geksilla** [comment]
@gandm, thanks a lot!
