### ISSUE TITLE
`source.js.jsx` scope set even when not in a JSX block

### ISSUE THREAD

**Issue by awilkins** [gandm/language-babel#259]
AFAICT from reading the source language-babel only emits the `source.js.jsx` scope for Javascript, and not the `source.js` scope. This means that linters that don't grok JSX like JSHint will refuse to lint any of the buffer.

Would it be possible to set the scope `source.js` outside of JSX blocks?

**Comment by gandm** [comment]
I doubt I'll change this. I use eslint but I believe you can toggle on 'Lint JSX files' and then jshnt will work with my grammar.
