### ISSUE TITLE
grammar support for flowtype is missing

### ISSUE THREAD

**Issue by vith** [gandm/language-babel#26]
I've got a very small start towards this in [this branch](https://github.com/gandm/language-babel/compare/master...vith:flowtype) that only supports type annotations in argument lists. Return type annotations break things:

![screenshot from 2015-07-18 03 08 47](https://cloud.githubusercontent.com/assets/3265539/8760925/91361d9c-2cfc-11e5-83c8-46fc9f53957d.png)

Should the return types be added to the `end` patterns of all the varieties of function literals or is there a better way to accomplish that without so much repetition?

**Comment by gandm** [comment]
On holiday at the moment. I will review this when back.

**Comment by nmn** [comment]
+1

**Comment by gandm** [comment]
I've just committed a grammar change ( but not published) that I think gives you flowtype on functions/fat arrows. No support for let/const/var as this need thinking about. Let me know if it creates problems?

**Comment by gandm** [comment]
Strike that!! I seemed to have regressed!

**Comment by nmn** [comment]
should I not update to latest version then??

**Comment by gandm** [comment]
Yes try it - When I just tested it again I was using someone else's grammar - Doh!! Now I've set it to mine it seems OK. 

Don't forget the published version is still the old one. You will have to pull the one from github.

**Comment by nmn** [comment]
hmm.. Ok let me try

**Comment by nmn** [comment]
Hey, use this file for flow-tests: https://gist.github.com/kastermester/ad79da3e48064effd82e
That with  the React source code is probably the best test possible.

(i'm still trying on my own code-base, will report back shortly)

**Comment by nmn** [comment]
Ok, so I just tried it and it's not fixed. The colour has changed though.

I don't know how grammars work, but here's the problem:
```
(array: Array<V>): IndexedIterable<V>;
```
That is a valid declaration for flow. However language-babel interprets that as JSX and everything after the first `<V>` becomes one colour. (kind of like the colour of text in a JSX block).
 Putting this comment at the end of the line seems to fix the problem:
```
// </> </>
```
(one closing tag for each angular bracket used in the line)
Which re-inforces my guess that it is being interpreted as JSX.

**Comment by gandm** [comment]
Yeah it's definitely showing as JSX. Thanks for the flow test file above. I think this is going to be pretty difficult with the current grammar. I thought that templates may be an issue. Leave it with me.

**Comment by nmn** [comment]
Thanks!

**Comment by gandm** [comment]
@nmn, @vith - Just rolled out 0.11.0 with support for flowtype. See https://github.com/gandm/language-babel/issues/39 and https://github.com/gandm/language-babel/issues/40 for known problems.

Let me know if you have any issues.
