### ISSUE TITLE
Syntax highlighting breaks inside square brackets in `v2.43.0`

### ISSUE THREAD

**Issue by markuso** [gandm/language-babel#261]
When using statements inside an array (square brackets), like using `if` or `while` statements within an array of functions, then the syntax highlighting breaks.

Here's how this sample example should look:

![image](https://cloud.githubusercontent.com/assets/56903/19215723/fedb0f50-8d73-11e6-8fc9-f7886d096ed8.png)

But when the same function is part of an array, syntax highlighting breaks at the `if` statement:

![image](https://cloud.githubusercontent.com/assets/56903/19215734/30d80314-8d74-11e6-89bc-1fa37456f33a.png)

Look what happens if I remove the left angle bracket from the `if` statement below:

![image](https://cloud.githubusercontent.com/assets/56903/19215738/4a1cc7d8-8d74-11e6-8b1e-b027e483b46d.png)

Even in **ES6** syntax version it breaks:

![image](https://cloud.githubusercontent.com/assets/56903/19215741/5687f86c-8d74-11e6-927b-eb9f9423e963.png)

Here's the sample code for quick test:

```js
var arrayOfFunctions = [
  function (callback) {
    var num = 0;
    if (num <= 0) {
      return callback(null);
    }
    return callback(num);
  },
  function (callback) {
    var num = 0;
    if (num <= 0) {
      return callback(null);
    }
    return callback(num);
  }
];
```

**Comment by gandm** [comment]
Thanks. It is a regression caused by the recent change. I'll take a look.

**Comment by gandm** [comment]
Try 2.44.0

**Comment by markuso** [comment]
Works great now and all the syntax highlighting is back. Thank you so much @gandm 👍
