### ISSUE TITLE
Broken JSX Syntax Highlighting in 2.44.0

### ISSUE THREAD

**Issue by dperetti** [gandm/language-babel#262]
An picture is worth a thousand words :
![image](https://cloud.githubusercontent.com/assets/845612/19230230/c0799ebe-8ed3-11e6-8434-926785c72776.png)

Now if I add a pair of parentheses, the right colouring is back :

![image](https://cloud.githubusercontent.com/assets/845612/19230274/fb97ad9c-8ed3-11e6-9d56-06ea5bb3427c.png)

**Comment by gandm** [comment]
Can you let me have a code snippet showing thew issue. I can't see the context in which the above is used.

**Comment by dperetti** [comment]
Issue arises with something like that :
`const someComponent = ({ onClick }) => <div onClick={onClick}>Blah</div>`

![image](https://cloud.githubusercontent.com/assets/845612/19230937/700844f4-8ed7-11e6-9bdc-dd04a1865349.png)

**Comment by gandm** [comment]
Whoops, stupid regex!. Yes I'll just fix and run specs to ensure it's OK and roll out a fix.
