### ISSUE TITLE
FlowType comment syntax "flow-include" causes weird syntax highlighting

### ISSUE THREAD

**Issue by jokeyrhyme** [gandm/language-babel#263]
I quite like FlowType, but I prefer to maintain ECMAScript-compatible syntax and instead use FlowType via its comment syntax:
- https://flowtype.org/blog/2015/02/20/Flow-Comments.html

Adding simple type annotations such as `/* : string */` works terrifically. Everything is highlighted as expected.

However, as soon as I use the "flow-include" comment syntax, such as `/* :: ... */` or `/* flow-include ... */`, the rest of the code in the file is highlighted incorrectly.

Here is a reduced sample of code that triggers the issue: https://gist.github.com/jokeyrhyme/4f1a7580deb9f4727bd35f0e7953291a

Here is what it looks like in my Atom:
![screen shot 2016-10-11 at 13 49 39](https://cloud.githubusercontent.com/assets/479816/19257221/94a18d88-8fb9-11e6-80cf-0aeb8c00ce01.png)

Any ideas? Is this the appropriate forum to discuss this issue? Or is this an upstream thing?

**Comment by gandm** [comment]
OK thanks for this report. I'll have to fix this but as a work around put a semi-colon at the end of the type statement.

**Comment by jokeyrhyme** [comment]
Oh, I hadn't even noticed that all of the FlowType examples on the website use semi-colons, but I own code does not. Thanks for that. Adding in the semi-colons fixes this.

If FlowType is supposed to work without semi-colons, then this might still be worth fixing, but otherwise you could consider this user-error. Up to you. :) /shrug

**Comment by gandm** [comment]
@jokeyrhyme flow comments without semi's should be fixed in the latest release.

**Comment by jokeyrhyme** [comment]
@gandm thanks! I can confirm that this is working for me. Yay!
