### ISSUE TITLE
Javascript files are marked as JSX

### ISSUE THREAD

**Issue by Arcanemagus** [gandm/language-babel#266]
It seems that for some reason this language package is marking _all_ Javascript (`source.js`) files as JSX (`source.js.jsx`) files.

This is causing problems with Javascript linters as they "don't work" on Javascript files since they aren't marked as being compatible with JSX, see https://github.com/AtomLinter/linter-jshint/issues/348 for some examples of users having issues with this.

**Comment by gandm** [comment]
I can't see reason to change this. My grammar supports flowtype,, ES2015, ES2016, tc39 features  JSX, etc. I can't tell from the filename what the file contents are. The vast majority of people name their JSX files as `.js`  See https://github.com/airbnb/javascript/pull/985#issuecomment-239145468 

As most of my user base are likely using React/JSX it's a hint that if you don't support JSX you'd best not apply it to files that my grammar supports. I could just scope the JSX bit as jsx and the global scope as `source.js` but this wouldn't help as it you'd still fail when linting some file that had JSX inside it, believing it to be a pure JS file.

Also, lots of snippets use the JSX scope to trigger them and historically I matched the `react` atom package which used this scope.

**Comment by Arcanemagus** [comment]
I had no idea people wrote JSX files as `.js`... isn't it a templating language?!?

I'm not sure what I would do here myself, I suppose leaving it as putting all Javascript files as JSX is probably best for your audience so I'll go ahead and close this.

**Comment by gandm** [comment]
> I had no idea people wrote JSX files as  .js ... isn't it a templating language?!?

No Facebook react (JSX) extends JavaScript and has to have a compile phase to turn it back
 into spec compliant JavaScript - hence why my product is named Babel, after the transpiler. Simarlarly, flowtype is like Typescript and also needs a compile phase. Both significantly extend the syntax of JavaScript.
