### ISSUE TITLE
CSS language in Styled Components template string

### ISSUE THREAD

**Issue by EmilTholin** [gandm/language-babel#267]
Thank you for your great work on getting syntax highlighting to work on [styled-components](https://github.com/styled-components/styled-components)! 

Would it be possible to add CSS language support within the styled components template strings? Would be great to be able to use CSS snippets, etc.  

I'm sorry if this is a naive question and outside the scope of this great package.

**Comment by gandm** [comment]
the current css templating/interpolation for styled-components was a quick hack but I am rewriting the css grammar parsing and will roll that out sometime soon. At that point, I will rename the scope to be Css and then packages like https://atom.io/packages/css-snippets and language-css snippets should work. Is this what you need?

**Comment by EmilTholin** [comment]
That's exactly it. Looking forward to it. Thanks a bunch!
