### ISSUE TITLE
Highlight styled-components when component is passed literally

### ISSUE THREAD

**Issue by diegohaz** [gandm/language-babel#268]
Would it be possible to consider the following syntax? (I'm using `language-babel` in this file)

![image](https://cloud.githubusercontent.com/assets/3068563/19404765/019b2054-9247-11e6-8550-0762287d09cb.png)

Thank you for the package.

**Comment by gandm** [comment]
I need to know that the open back-tick is styledCSS and Atom's (TextMate's) grammar features don't allow me to do this. But you could do this.
Go to my package settings and enter:
![image](https://cloud.githubusercontent.com/assets/2313237/19408486/3ef5fea0-92b6-11e6-9629-a545c3b763a3.png)
And then use a prefix comment before the back-tick:
![image](https://cloud.githubusercontent.com/assets/2313237/19408480/1f7d73aa-92b6-11e6-9cda-2c710f772d2f.png)
I am changing the grammar for styled-components and may add another way to do this - maybe look for a comment inside the template?
