### ISSUE TITLE
No way to show invisibles

### ISSUE THREAD

**Issue by tomocchino** [gandm/language-babel#270]
My Atom "Show Invisibles" setting isn't respected with language-babel. Switching back to JavaScript makes invisibles work properly. I also can't seem to override the setting in my local styles.less.

I tried to dig into the source here a bit to figure out how this could be getting overridden, but didn't have much luck (and ran out of time), so I figured I'd file an issue in case it's a quick fix.

JavaScript
![screenshot 2016-10-17 16 32 16](https://cloud.githubusercontent.com/assets/13947/19459401/772d6682-9487-11e6-8572-c913b9636d57.png)

Babel ES6 JavaScript
![screenshot 2016-10-17 16 30 45](https://cloud.githubusercontent.com/assets/13947/19459412/8b6c87ea-9487-11e6-8e2a-8582e961cd85.png)

**Comment by gandm** [comment]
Packages don't control invisibles and I have no issue with showing them. What does  Atom's config.cson look like?

**Comment by tomocchino** [comment]
Wow, I totally had an override buried in my config.cson for some reason. I have no idea how it got there. Possibly Nuclide related.

```cson
".js.jsx.source":
  editor:
    showInvisibles: false
```

Thanks for pointing me at that!
