### ISSUE TITLE
No color for Intl global variable

### ISSUE THREAD

**Issue by ulrik59** [gandm/language-babel#273]
Intl is a standard built-in object in JavaScript and should be colored the same way as Math object for example.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
![Not colored Intl object](https://cloud.githubusercontent.com/assets/6003644/19519772/9ba8940a-960d-11e6-9070-da196d5d89a7.png)

**Comment by gandm** [comment]
Thanks. I'll add this at the next release.

**Comment by gandm** [comment]
Unsure when I'll publish this small change. Use the current GitHub master if needed.
