### ISSUE TITLE
Syntax highlighting for template literal expressions?

### ISSUE THREAD

**Issue by philraj** [gandm/language-babel#274]
Hi,

I was wondering how you'd feel about adding syntax highlighting to expression markers within template literals, i.e. the `$`, `{`, and `}` in:
```
`my template literal has an ${expression}`
```
I find when using more complicated template literals with lots of embedded expressions, in the context of URLs for example where there's lots of visual noise from other symbols, it can take a bit more effort to spot the parts that are being interpolated and the parts that are literal.

In the LESS grammar highlighting, using string interpolation looks like this:
![Imgur](http://i.imgur.com/HJyPQkG.png?1)
I think it works pretty well. Obviously in JavaScript the expression itself wouldn't be colorized, but how about colorizing the surrounding symbols? Got any thoughts?

**[edit]** Come to think of it, when the expressions themselves have lots of moving parts (meaning lots of colors), adding an extra color to the expression markers might make things look worse, even though it might look good when sticking in a simple variable name. Not too sure about this one.

**Comment by gandm** [comment]
Sorry If I misunderstand you but anything inside the `${}` altready gets highlighted as  JavaScript
![image](https://cloud.githubusercontent.com/assets/2313237/19546682/b9272efc-9689-11e6-9d65-806de4bd482b.png)
Am i missing something?

**Comment by philraj** [comment]
Yes sorry if I was unclear, I meant the symbols surrounding the expression (the `${}` themselves). In that screenshot they're green, the same color as text in the template literal.

**Comment by gandm** [comment]
Having re-read the issue you were perfectly clear,  I was just dumb!

I could scope it the same as language-javascript, which in the example above would display `${}` as red. But as you say, this would merge into the calc variable. Obviously, I can't control the colour used but i could add a unique scope (class name) that would enable you to style it how you wanted.

**Comment by gandm** [comment]
Actually, I give it a unique name anyway `${` is `punctuation.quasi.element.begin.js` and `}` is `punctuation.quasi.element.end.js` So you could add scopes to styles.cson to give it any colour you want. I'll close this. Feel free to add any comments you may have.

**Comment by philraj** [comment]
Works for me. I'm not super familiar with how to style something like that -- are you talking about my user stylesheet (`styles.less`)? I tried adding `.punctuation.quasi.element.begin.js { ... }` to no avail, so I'm probably misunderstanding you.

**Comment by gandm** [comment]
Add some CSS to Atom's styles.less ( accessed from the file menu)
![image](https://cloud.githubusercontent.com/assets/2313237/19566548/a452eca6-96e2-11e6-9a44-33b7643e3d0f.png)
Gives
![image](https://cloud.githubusercontent.com/assets/2313237/19566568/b50b5196-96e2-11e6-82e8-c78eb9f86280.png)

**Comment by philraj** [comment]
Oh right I forgot to add the `atom-text-editor::shadow` bit. Thanks!

**Comment by philraj** [comment]
So I noticed that the `<span>` of class `entity.quasi.element.js` is including all the whitespace between the `${...}` and the previous word.

Is that anything you have control over? I was playing around with some styles but this makes it a bit impossible to style only the interpolation part as a whole.

![image](https://cloud.githubusercontent.com/assets/16470658/19610255/7762fe80-97a9-11e6-8df8-8d17dbaec696.png)

**Comment by gandm** [comment]
Just pushed a fix for this to GitHub master. Not published but you can try it and let me know if it's OK.

**Comment by philraj** [comment]
Yep, works great. By the way, somewhat unrelated but was there an easier way than manually copying and pasting the changes into the package's files (I'm pretty new to this)? Could I just clone the repo inside the package's folder or something along those lines?

**Comment by gandm** [comment]
Easiest way is to `apm unistall language-babel` and then `apm install gandm/language-babel` This clones the repo and then install from the clone into ~.atom/packages
