### ISSUE TITLE
No syntax highlight for require('async')

### ISSUE THREAD

**Issue by jaypanares** [gandm/language-babel#275]
Hi, currently experiencing no/inconsistent syntax highlighting when requiring the async npm module:

![capture](https://cloud.githubusercontent.com/assets/7044596/19635435/e3cce930-99f4-11e6-91d7-4cfd5bac71fe.PNG)

On Windows 10, Atom 1.11.2, language-babel 2.45.0

Thanks!

**Comment by gandm** [comment]
I won't publish this fix for a while. If you wish to use it please `apm uninstall language-babel` and then `apm install gandm/language-babel` to get this mater branch.
