### ISSUE TITLE
could JS template grammar extensions be styled as "dark block"

### ISSUE THREAD

**Issue by gre** [gandm/language-babel#277]
I find the JS template grammar extensions feature awesome, thanks for this :)

I think it would be interesting to emphasis a bit more the fact it's another language in your JS
and here is my proposal:

<img width="510" alt="screen shot 2016-10-26 at 22 43 14" src="https://cloud.githubusercontent.com/assets/211411/19744387/a0ebe0c8-9bcd-11e6-8e2c-f2c158bd539c.png">

Do you know if it's possible to do this?

I think it have a great value because it's very confusing for my eye to see the highlighting of different collocated languages like that:

<img width="523" alt="screen shot 2016-10-26 at 22 44 35" src="https://cloud.githubusercontent.com/assets/211411/19744464/ebbc90e8-9bcd-11e6-93a8-f5c0f331a13b.png">

The problem it it seems there is still the "host language class" in the editor, so i'm not sure if it's easy to do.

<img width="488" alt="screen shot 2016-10-26 at 22 35 48" src="https://cloud.githubusercontent.com/assets/211411/19744316/4b271c16-9bcd-11e6-8c25-8123536bc5d3.png">

Thanks

**Comment by gandm** [comment]
I've just pushed a mod to the master branch that adds a class to the inner content of a tagged template string. The inside should now be marked `meta.ttl-grammar.js`, which should allow you to customise your Atoms styles.less to colour the background how you choose.

Until I publish this you can `apm uninstall language-babel` and `apm install gandm/language-babel` to get the mod.

**Comment by gre** [comment]
cool :)

```
atom-text-editor::shadow .line .ttl-grammar {
  background-color: rgba(0,0,0,0.2);
}
atom-text-editor::shadow .line .ttl-grammar:first-child:last-child {
  display: block; // if ttl-grammar is alone in the line, we display block to force the background to take full width
}
```

produces

<img width="576" alt="screen shot 2016-10-27 at 08 24 51" src="https://cloud.githubusercontent.com/assets/211411/19756725/ecc1b62a-9c1e-11e6-8d9c-edc57b7900b0.png">

I have this hack to use `display:block` ONLY if the line only contains this ttl-grammar (otherwise it would create create misalignement).

if it isn't "alone" in the line, it won't display as block:
<img width="490" alt="screen shot 2016-10-27 at 08 30 49" src="https://cloud.githubusercontent.com/assets/211411/19756890/03679b28-9c20-11e6-8c7d-d3d1e2b9eb4d.png">


I wish I could also find a way to do padding around this block, but it is probably too much to ask without Atom to provide ways to do this^^

**Comment by gre** [comment]
my approach don't support empty line though:

<img width="520" alt="screen shot 2016-10-27 at 11 07 26" src="https://cloud.githubusercontent.com/assets/211411/19761309/9ea9795c-9c35-11e6-8729-1135d0d7ff38.png">

**Comment by gandm** [comment]
Probably impossible without resorting to coding and using decoration markers and marker layers. https://atom.io/docs/api/v1.11.2/Decoration 
https://atom.io/docs/api/v1.11.2/DisplayMarkerLayer

**Comment by gandm** [comment]
I think I'll close this as coding seems a bit heavy handed to achieve this.

**Comment by jniac** [comment]
arf... now `::shadow` is no more supported.
Any way to achieve this ? i agree `gre`, background highlighting is really convenient to read files containing more than one language (JS + GLSL)
