### ISSUE TITLE
Word operators with operands surrounded by parenthesis

### ISSUE THREAD

**Issue by daltones** [gandm/language-babel#278]
Unary operators `void` and `delete` are being resolved as function calls if the operand is surrounded by parenthesis (with or without spaces before).

![captura de tela de 2016-10-31 20-14-33](https://cloud.githubusercontent.com/assets/5603632/19873558/d4481c98-9fa6-11e6-9321-d5d1ecf6fb61.png)

**Comment by gandm** [comment]
In what context? Inside a class delete() is allowed to be a method name.

**Comment by gandm** [comment]
Also inside object literal http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=let%20a%20%20%3D%20%7B%0A%20%20delete()%7B%7D%0A%7D%0A%0Aclass%20b%20%7B%0A%20%20void()%7B%7D%0A%7D

**Comment by daltones** [comment]
I mean in every “normal” context of statements, where `delete` (or `void`) as unary operator is allowed.

```js
// top level
void (0); // bad meta.function-call.with-arguments.js

// or function (or if, else, for etc.) body:
function foo() {
  void 0; // good keyword.operator.js
  void (0); // bad meta.function-call.with-arguments.js
}
```

**Comment by gandm** [comment]
Ok I will take a look. I thought I only allowed those scopes inside classes and obi literals.

**Comment by daltones** [comment]
Actually it seems like a general problem with operators that are words, not only unary ones. When these operators have the right operand surrounded by parenthesis, they are resolved as function calls.

```js
if (foo instanceof Date) return;
if (foo instanceof (Date)) return;
```

Okay, those parenthesis on second line are weird, but they are valid. And then `instanceof` is resolved as `meta.function-call.with-arguments.js`.

This problem affects also `in` and `of` of `for...(in|of)`… I can't remember right now if there's more, but it's a problem with word operators.
