### ISSUE TITLE
Variables that contains a function has a wrong color

### ISSUE THREAD

**Issue by LucianoGraziani** [gandm/language-babel#281]
When you create a function like this:

```jsx
const helloWorld = () => 'hello world';
```
It paints `helloWorld` variable with blue. That's ok. But if you sets a return type, like this:

```jsx
const helloWorld = (): string => 'hello world';
```

It paints `helloWorld` variable with the scarlet red for variables that aren't functions.

![image](https://cloud.githubusercontent.com/assets/15050200/19953887/b8005d14-a151-11e6-9327-1b1b4c2073eb.png)

## Information

- Atom: `v1.11.2`.
- language-babel: `v2.46.0`.

**Comment by gandm** [comment]
Thanks for the report. I think I made a change to support the new Flow %checks predicate quite a while ago but it looks like it's screwed things. I'll look at fixing.
