### ISSUE TITLE
language-babel conflict with atom-beautify

### ISSUE THREAD

**Issue by PapyElGringo** [gandm/language-babel#282]
When I have language-babel active the beautify on save from atom-beautify stop to work.

Do you have an idea of why this is happening?

**Comment by gandm** [comment]
No idea. Have you raised an issue at atom-beautify?  As far as I know it should work of you have prettydiff enabled as the  beautifier but I don't use it.

-----Original Message-----

**Comment by gandm** [comment]
One thing you might want to try, if you haven't already,  is enabling format on save for jsx files as well as js. Also just double check that prettydiff is the default beautifier, for jsx files.
