### ISSUE TITLE
Template literal causes indentation breakage

### ISSUE THREAD

**Issue by GreenAsJade** [gandm/language-babel#284]
Everything following the first template literal tries to indent one level too far... (only the first one shown here, I left the rest at it's original indentation)

![screenshot 2016-11-05 10 11 25](https://cloud.githubusercontent.com/assets/61894/20025833/6da4729e-a342-11e6-8b69-5ebcfa7e78db.png)

**Comment by gandm** [comment]
That is how Atom is designed to work. The same happens in Atom's own `language-javascript` package as well. Atom will align all code based on the previous non-blank lines indentation. In your case, the trailing line of the first template is used for all following lines. The only time this doesn't happen is when a languages indent/outdent regex is found. This is how lines starting `{` and ending `}` manage to auto indent/outdent.

The only code I indent is inside JSX, and only if my packages `auitoIndentJSX` is turned on.

**Comment by GreenAsJade** [comment]
Thanks!   Now I know why people end these literal strings with the backtick in the first column of the next row!
