### ISSUE TITLE
Incorrect Auto-indentation

### ISSUE THREAD

**Issue by mrtnbroder** [gandm/language-babel#286]
![wrrrrrriiiiiiii](https://cloud.githubusercontent.com/assets/1118826/20074772/f43ddef8-a531-11e6-8623-e5f24ed14e02.gif)

updated the package today, now I have this.

just..no. don't do this.

EDIT: just noticed that I can disable it, but from reading the description it should consider the eslint config, and you can clearly see here that it doesn't do that.

![](http://s2.quickmeme.com/img/7f/7f5212c4008d98cd5eadd27fe33aad8b01a976c5b33f2acfba14ad7e50eb9159.jpg)

**Comment by gandm** [comment]
It was turned on by default at the request of facebook developers. You can disable it but it should read the .eslintrc file if present to determine the alignment type. It won't, as stated in the readme, read from other files such as extends, package.json etc. Either disable it or let me have the contents of your .eslintrc file.

**Comment by gandm** [comment]
I'm guessing you have a closing bracket setting of props-aligned inside a file other than a .eslintrc file. Anyway, until I can get around to supporting all the various hierarchies of eslint file types, I'll close this as you can easily disable autoIndentJSX which was the previous default behaviour.

**Comment by szimek** [comment]
@gandm How can it be disabled? It's super annoying, especially when I move a cursor to an empty line, it indents it with spaces and eslint starts complaining about trailing spaces :/

**Comment by gandm** [comment]
It works fine for me and countless others using eslint. Anyway just go to the package settings and toggle off 
![image](https://cloud.githubusercontent.com/assets/2313237/20103273/357056b4-a5c1-11e6-982d-b5d212d05947.png)

**Comment by szimek** [comment]
@gandm Just to be clear - this setting is supposed to auto-indent a line *when a cursor is moved to it*? I'm completely fine with auto-indentation that is triggered by a key press (e.g. if a new line is auto-indented after I press Enter etc.), but somehow I can't get used to it.

I'll give it a try thought ;) Thanks!

**Comment by gandm** [comment]
@szimek when a cursor is positioned inside a jsx block that line and all proceeding lines are auto indented. If that line is a blank line then I will add hard tabs or soft tabs (depending on the atom settings) in preparation for a new line but if no data is entered and the cursor is moved away then the spaces are removed to satisfy eslint.

**Comment by gandm** [comment]
@szimek oh it also is used when you are typing inside a jsx block; so not just on cursor positioning.

**Comment by szimek** [comment]
@gandm Thanks for the explanation and sorry if I sounded too harsh. This package is one of the most useful ones I use. Thanks 😉
