### ISSUE TITLE
Indentation issues in JSX

### ISSUE THREAD

**Issue by ffxsam** [gandm/language-babel#287]
There's some unpredictable behavior going on with auto indent (see below).

![licecap](https://cloud.githubusercontent.com/assets/12532733/20121377/eb8cdcac-a5c5-11e6-8a7b-546efa5a04af.gif)

**Comment by ffxsam** [comment]
Furthermore, despite disabling every auto-indent option in the package settings, this still happens. I have to disable the plugin altogether in order to turn off auto indent.

**Comment by gandm** [comment]
That's expected. The default [eslint](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md) behaviour for closing brackets is `tag-aligned` therefore the closing `>` is aligned under the opening `<' . The above passes the eslint rule OK.

**Comment by gandm** [comment]
3 options:
- diable autoIndentJSX in my package ( the old default behaviour)
- You could change/add an .eslintrc rule to `line-aligned`
- You can wrap the return in parens ( better practice in my opinion)
```
return (
   <div
   >
   </div>
)
```
