### ISSUE TITLE
styled-components indentation

### ISSUE THREAD

**Issue by mxstbr** [gandm/language-babel#291]
It would be awesome if the `styled-components` syntax had the same indentation support as the JSX stuff!

I.e. at this state in the editor:

```JS
const Box = styled.div`
```

pressing `ENTER` could put me in this state, with the cursor (`|`) being correctly one unit indented:

```JS
const Box = styled.div`
  |
`
```

That'd be awesome!

**Comment by gandm** [comment]
Yes i'll do it sometime soon. Quite trivial.

**Comment by gandm** [comment]
I've just added a branch https://github.com/gandm/language-babel/tree/indentStyledComponents that does this. I'm not sure if this is what you wanted. Maybe you could experiment with it and let me know?

**Comment by gandm** [comment]
Try the latest version.

**Comment by mxstbr** [comment]
Oh sorry, I totally missed your comment, my bad! It's absolutely perfect, thanks so much!
