### ISSUE TITLE
Status of language-babel support/maintenance

### ISSUE THREAD

**Issue by jasrusable** [gandm/language-babel#292]
I see `Please note that this package is no longer supported.` was added to the projects readme a few days ago (in https://github.com/gandm/language-babel/commit/552261cef7c3735382bf162ead540cf7052e6c5c), but I have since seen some commits and releases.

What is the status of this package? Is it still supported? Are you looking for contributors/maintainers?

PS: Thanks for the great package :)

**Comment by gandm** [comment]
I'm in two minds about this. I recently got some issues raised that I thought weren't very appropriate. Some people complain about things but seem incapable of checking the README. This package isn't exactly mission critical so I can't see why people get wound up! I normally respond to issues and fix them quickly.

Also see https://github.com/gandm/language-babel/pull/289

**Comment by jjstrat3** [comment]
@gandm I'm sorry that you've had to deal with folks like that.  The increasing amount of entitlement I've seen is a really frustrating trend in open-source these days :(

I really appreciate all your had work you've done, and I hope those experiences won't prevent you from offering more great contributions to the open-source community in the future!

**Comment by philraj** [comment]
For what it's worth, I've always found you to be very open to discussion and very helpful. I'm sorry for the bad attitudes you've had to deal with. Great package.

**Comment by gandm** [comment]
@jjstrat3 @philraj Thanks for your support. It is appreciated.
