### ISSUE TITLE
Add html highlighting for html tagged template strings 

### ISSUE THREAD

**Issue by bcomnes** [gandm/language-babel#293]
Would you be open to adding html highlighting to tagged template strings that have a tag function named `html` ?  The package currently has this feature for `css` tagged template strings with css.  The default atom JS highlighter used to have both, but they couldn't get css to work correctly.  You have css working, but not html.

Here is how the default highlighter does it.  https://github.com/atom/language-javascript/blob/d59666cab4275033d15d938d9d60a6ee99905924/grammars/javascript.cson#L1378-L1425

**Comment by gandm** [comment]
See https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions

**Comment by bcomnes** [comment]
Fantastic.  Missed this feature all together.
