### ISSUE TITLE
Styled components highlighting for wrapped components

### ISSUE THREAD

**Issue by vdanchenkov** [gandm/language-babel#294]
Highlighting breaks for this case:
![image](https://cloud.githubusercontent.com/assets/2461813/20296842/83a5b044-ab26-11e6-92ba-5f5732a16b57.png)

**Comment by Fabiantjoeaon** [comment]
Same for me, breaks at:

<img width="643" alt="schermafbeelding 2016-11-15 om 13 21 26" src="https://cloud.githubusercontent.com/assets/4189340/20305569/7ac51d7e-ab36-11e6-88ea-11aae0b925a1.png">
