### ISSUE TITLE
styled-components still broken in 2.49.2

### ISSUE THREAD

**Issue by Pyrolistical** [gandm/language-babel#296]
#294 was tagged as released in 2.49.2

I updated to it manually using `apm install language-babel@2.49.2` and see that version in my atom settings, but I still get this:

<img width="357" alt="screen shot 2016-11-16 at 12 45 05 am" src="https://cloud.githubusercontent.com/assets/463642/20340367/0ced6f8a-ab96-11e6-98c8-4ad649baa369.png">

**Comment by gandm** [comment]
You aren't terminating the css props with semi-colons.

**Comment by gandm** [comment]
Also please note that 2.49.2 is for atom versions 1.13 and above 2.48.x is for atom versions <1.13. They are both the same apart for some theme style changes due to removal of shadow dom. Just installing using the default should install the correct version.

**Comment by gandm** [comment]
Oh! Also, I will do a fix for props on the last line that aren't terminated by a semi colon but terminate with a back-tick, sometime this week I have no idea if that is allowed in styled-components as I don't use it.

**Comment by gandm** [comment]
Try the latest version.

**Comment by Pyrolistical** [comment]
looks good, thank you.
