### ISSUE TITLE
Ternary condition inside for...of or for...in

### ISSUE THREAD

**Issue by daltones** [gandm/language-babel#297]
I'm sorry if I'm doing wrong reporting this here, but I saw that some other issues are being answered.

So here's the bug I encountered:
![captura de tela de 2016-11-18 17-43-51](https://cloud.githubusercontent.com/assets/5603632/20444043/a0c64872-adb6-11e6-8871-91f102c4ed6d.png)

There's something breaking the scopes inside ternary conditions in `for...of` or `for...in` statements.

I also want to thank you @gandm for all the work on this package, it's really very helpful for the community. And I'm very sorry for this situation (if I understood correctly) that some people don't have the conduct that the community needs.

Thanks in advance!

**Comment by gandm** [comment]
Yes no problems and thanks for the support. I'll take a look.

**Comment by gandm** [comment]
Try the latest version.
