### ISSUE TITLE
Destructuring more then two arguments in a function results in inconsistent highlighting

### ISSUE THREAD

**Issue by malbernaz** [gandm/language-babel#299]
Destructuring more then two arguments in a function, only the first argument properties span gets the `shorthandpropertyname` css class.

![example](https://cloud.githubusercontent.com/assets/10574149/21146898/68c1d922-c13a-11e6-849f-1e895168e15a.png)

**Comment by gandm** [comment]
Actually, the first argument shouldn't have the shorthandpropertname css class as it is a destructured object variable, and not a real object property.

**Comment by gandm** [comment]
I've added a commit that fixes this as per you original issue report. I will publish when Atom 1.13 is out of beta.

**Comment by gandm** [comment]
Published in 2.49.4

**Comment by dodekeract** [comment]
@malbernaz Unrelated, but can you explain what `<Icon.Cart/>` does (notation-wise) and how to create a component with a dot?

**Comment by malbernaz** [comment]
@dodekeract `Icon` is not a component, is just a simple object. The components `MenuIcon` and `Cart` are both keys of it.
