### ISSUE TITLE
Change content/class names of space inside JSX tags?

### ISSUE THREAD

**Issue by rosston** [gandm/language-babel#30]
The space within JSX tags currently has a class string of `.markup.raw.jsx` when rendered in Atom. This causes a problem for any theme expecting `.markup.raw` to be used for raw HTML within a Markdown document (https://github.com/wesbos/cobalt2-atom/issues/2).

`.markup.raw` (and `.markup` in general) seems to be mostly used for Markdown rather than XML/HTML. See [atom/language-gfm/grammars/gfm.cson#L717](https://github.com/atom/language-gfm/blob/v0.79.0/grammars/gfm.cson#L717). [language-xml](https://github.com/atom/language-xml) and [language-html](https://github.com/atom/language-html) appear to have no reference to `.markup` at all.

I'm not sure what class string would be best for your project (which is why this isn't a PR), but for what it's worth, language-html and language-xml both fall back to their base scope names (`.text.html.basic` and `.text.xml`) for content within tags.

**Comment by gandm** [comment]
No able to get test this until Friday. I'm not sure why I decided to use markup as a scope. I'll take a look on Friday.
