### ISSUE TITLE
Differentiate object literal braces with other braces

### ISSUE THREAD

**Issue by pveyes** [gandm/language-babel#301]
Currently the grammar only mark switch case braces with `switchStart` and `switchEnd`. Is it possible to do this for other type of braces?

Here's the list that's not currently supported:
 - function / arrow fn braces
 - conditional braces
 - for and while loop braces
 - object literal braces

**Comment by gandm** [comment]
Probably, but why do you need this? The reason I tag the switch statements is to support my JSX auto indentation.

**Comment by pveyes** [comment]
I see, I'm creating atom syntax theme and I want to dim all braces and punctuation colors, except when for object literal (because it's not block statement).

Can you help me guide which part I should learn. I'll try to contribute if this is something that you think it's okay

**Comment by gandm** [comment]
Added litobj class to object braces. Needs Atom ^1.13.0 & language-babel 2.49.4
