### ISSUE TITLE
Making React suggestions in a Python file!?!

### ISSUE THREAD

**Issue by Hum4n01d** [gandm/language-babel#305]
![screen shot 2017-01-06 at 9 02 23 pm](https://cloud.githubusercontent.com/assets/17228477/21739606/0f9e98d0-d454-11e6-9030-bddba84a5efc.png)

I don’t think this should be happening.

**Comment by dodekeract** [comment]
Quite sure that this isn't related. It's just suggesting words that are found in files that you currently have opened.

**Comment by Hum4n01d** [comment]
But it's still an issue

**Comment by Hum4n01d** [comment]
It shouldn't be suggesting that in the Python file @dodekeract

**Comment by gandm** [comment]
This has nothing to do with this package; Atom or another package is doing this. I only provide suggestions for JSX and always indicate they come from language-babel. e.g. below the circle suggestion comes from language babel as shown in the bottom line of the pop-up.
**
![image](https://cloud.githubusercontent.com/assets/2313237/21739949/894643c0-d4a1-11e6-8b0f-ac77a08c9f1c.png)
**

**Comment by dodekeract** [comment]
@Hum4n01d whether it should or not is opinionated. I personally like that words are suggested everywhere, since you'll e.g. need your css classes in JSX. If you want this to be changed find out which package really causes this and ask them to add an option to disable this feature.

**Comment by Hum4n01d** [comment]
:(

**Comment by gandm** [comment]
@Hum4n01d Just to be clear, language-babel only provides auto complete suggestions inside JavaScript files when it is the chosen grammar processor, and only for JSX. It does not provide suggestions inside any other file type. E.g Python, HTML,....  Atom provides suggestions for text but has settings that control the scope. See [here](http://flight-manual.atom.io/using-atom/sections/autocomplete/) for more info. Also, many packages provide suggestions.
