### ISSUE TITLE
Tab key no longer works with this package installed.

### ISSUE THREAD

**Issue by sergiotapia** [gandm/language-babel#306]
Atom version: 1.12.9
language-babel version: 2.48.5

---

With just this package installed, I can no longer tab indent code, empty lines or even selected code. Pretty easy to reproduce. Hope this helps and the fix is easy. 👍

**Comment by gandm** [comment]
I'm not sure what you mean as I have no issues with tab as you describe. Fairly sure someone would have pointed this out before now.
