### ISSUE TITLE
Deprecated selector in `language-babel/styles/language-babel.less`

### ISSUE THREAD

**Issue by hendrikeng** [gandm/language-babel#307]
In `language-babel/styles/language-babel.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .source.js.jsx .graphql .alias` => `atom-text-editor.editor .syntax--source.syntax--js.syntax--jsx .syntax--graphql .syntax--alias`

* `atom-text-editor::shadow .source.js.jsx .graphql .support.type.builtin` => `atom-text-editor.editor .syntax--source.syntax--js.syntax--jsx .syntax--graphql .syntax--support.syntax--type.syntax--builtin`

* `atom-text-editor::shadow .source.js.jsx .jsx .entity.other.attribute-name` => `atom-text-editor.editor .syntax--source.syntax--js.syntax--jsx .syntax--jsx .syntax--entity.syntax--other.syntax--attribute-name`

* `atom-text-editor::shadow .source.js.jsx .jsx .constant.character.entity` => `atom-text-editor.editor .syntax--source.syntax--js.syntax--jsx .syntax--jsx .syntax--constant.syntax--character.syntax--entity`

* `atom-text-editor::shadow .source.css.styled .support.type.property-name.unknown` => `atom-text-editor.editor .syntax--source.syntax--css.styled .syntax--support.syntax--type.syntax--property-name.syntax--unknown`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by gandm** [comment]
Atom 1.13 has been supported for months. Just update the language-babel package.

**Comment by spearmootz** [comment]
i updated and i get the same issues

**Comment by gandm** [comment]
@spearmootz Atom >1.13 needs language-babel 2.49.x and Atom <1.13 needs language-babel <=2.48.x
Please check and maybe re-start Atom.
