### ISSUE TITLE
'no longer supported' in README needs clarification

### ISSUE THREAD

**Issue by patrickmclaren** [gandm/language-babel#309]
As a follow-up to #302, I think the README.md needs an update to clarify what 'no longer supported' means. Similar to https://github.com/gandm/language-babel/issues/302#issuecomment-271912058 I read
> Please note that this package is no longer supported.

while viewing the package in Atom and initially thought this may imply certain reliability + compatibility issues. After reading your replies https://github.com/gandm/language-babel/issues/302#issuecomment-268799720 and https://github.com/gandm/language-babel/pull/289#issuecomment-259816842, I've come to understand the situation a little better. Perhaps it would be more appropriate to change to something along the lines of
> NOTE: This package is no longer under active development in lieu of several upcoming grammar changes, see [here](https://github.com/babel/babel-sublime/issues/293) for more details.

**Comment by gandm** [comment]
@patrickmclaren Thanks for your thoughts. The intent behind my statement is really to ensure that new users look elsewhere for a package that highlight JavaScript. Existing users will likely be unaware of this 'note' and of course I will attempt to fix issues should they arise. As I said in the comments you mentioned above, it is not clear if a new grammar will be developed. What is certain is that it will only be grammar and not support some of the other features of this package.

**Comment by patrickmclaren** [comment]
@gandm Gotcha, that makes sense. Thanks for clarifying.
