### ISSUE TITLE
classes permeate their scopes causing syntax highlighting to vary based on whether or not something is in a class

### ISSUE THREAD

**Issue by aaronjensen** [gandm/language-babel#31]
![optgropu](https://cloud.githubusercontent.com/assets/8588/8837939/09d81226-307e-11e5-83bd-8a46f7095b08.gif)
![aduro - atom 2015-07-22 14-30-04](https://cloud.githubusercontent.com/assets/8588/8837944/13a402f6-307e-11e5-83c5-d844ea72ad84.png)

**Comment by gandm** [comment]
What theme is this?

**Comment by aaronjensen** [comment]
One Dark. I'm thinking that the bug may be w/ that syntax, as `entity.name.class.js` seems to be the only thing pertaining to a class that should be colored.

**Comment by aaronjensen** [comment]
Actually, I wonder if it should be marked w/ .meta.class.body instead. That is colored correctly

**Comment by aaronjensen** [comment]
https://github.com/gandm/language-babel/commit/9276ad6f46932e4e0fb701d1e6e6d43e0420334b and https://github.com/gandm/language-babel/commit/5f7889cf265f1a8aa6f159e47011d95c5cc289eb seem to fix this. 

Could you release a new version when you get a chance please? Thanks!

**Comment by gandm** [comment]
Yes. Planning to publish this weekend.

**Comment by gandm** [comment]
0.10.3 released
