### ISSUE TITLE
Syntax highlight tagged SQL queries

### ISSUE THREAD

**Issue by ForbesLindesay** [gandm/language-babel#310]
I am writing quite a lot of SQL queries inside JavaScript lately.  I would ideally like to be able to have SQL keywords highlighted inside tagged template literals.  e.g.

```js
db.query(
  sql`SELECT * FROM MyTable`,
);
```

Ideally, I'd also like to add other languages after that.  Do you think this is something we could make pluggable?  Ideally it would be possible to write a separate package that just defines how tagged template literals are highlighted when they have a given tag.

**Comment by ForbesLindesay** [comment]
Just found out there are docs for how to do this, reading them now.

**Comment by gajus** [comment]
The relevant documentation is here, https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions.

**Comment by christiaanwesterbeek** [comment]
For months I had highlighting of sql code inside template literals in my js file working without language-babel installed, but with language-sql installed in Atom. Exactly like this:

```javascript
const sql = String.raw;
db.query(
  sql`SELECT * FROM MyTable`,
);
```

Today I updated Atom to 1.32.0 and now, no more sql hightlighting inside template literals.

Still trying to find out why. Installing language-babel and adding `"(?:css\.(?:[a-z])+)":source.css, /* @html */:text.html.basic, sql:source.sql` this inside the settings of language-babel did not help. Restarting Atom did not help.

**Comment by christiaanwesterbeek** [comment]
https://stackoverflow.com/questions/53072389/what-changed-about-syntax-highlighting-in-template-literals-since-atom-1-32-0
