### ISSUE TITLE
Shorthand bind(this) error

### ISSUE THREAD

**Issue by rohmanhm** [gandm/language-babel#311]
`React 15.*` support new shorthand `::this.functionName` overwrite `this.functionName.bind(this)`.
But `language-babel` not supported for it.

![image](https://cloud.githubusercontent.com/assets/7524911/22169045/c73f63d4-dfa3-11e6-8347-1eef01644754.png)

**Comment by gandm** [comment]
language-babel supports the :: bind syntax. The error above is from ESLint.

**Comment by gandm** [comment]
you may want to try [babel-eslint](https://github.com/babel/babel-eslint)
