### ISSUE TITLE
Could variables defined with `const`  have `constant` scope?

### ISSUE THREAD

**Issue by jwhitmarsh** [gandm/language-babel#315]
This was useful for syntax highlighting and quickly seeing the difference between variables set with `let` or `const`. 

Atom default is:
![screen shot 2017-01-25 at 15 18 18](https://cloud.githubusercontent.com/assets/8026009/22296330/b8282f04-e311-11e6-8d58-7b1b5eadfe82.png)

With language-babel in play:
![screen shot 2017-01-25 at 15 19 14](https://cloud.githubusercontent.com/assets/8026009/22296329/b80e848c-e311-11e6-926f-b621d6506917.png)

**Comment by gandm** [comment]
I need to be aware of multiple assignments. e.g. The standard Atom JavaScript language breaks on bar below. 
![image](https://cloud.githubusercontent.com/assets/2313237/22297442/2d489e6a-e315-11e6-96f9-d82bb5f6c316.png)
I also need to color code const funct=function correctly + support flow types etc. I could be done but would mean duplicating quite a lot of the grammar and that doesn't seem worthwhile. Also, const doesn't strictly mean non-writable.

**Comment by dodekeract** [comment]
Well, but is strictly means non-reassignable.

**Comment by gandm** [comment]
@dodekeract Yes agreed it can't be reassigned. I still think that it is better to use the convention of upper case names for immutable vars. e.g. `const FOO=1` as this becomes clear in the actual code body. 

In any case, to do this would require duplicating quite a lot of grammar for what,  IMHO, is of very little benefit.

**Comment by jwhitmarsh** [comment]
Ok, understood. Thanks for the reply, anyway. 

Also, should've said in the OP, thank you for hard work with this package - it's an excellent expansion of what Atom offers.
