### ISSUE TITLE
Bad indentation with lambda expressions.

### ISSUE THREAD

**Issue by saidmoya12** [gandm/language-babel#316]
When i use auto indent for a jsx or js document with lamda expressions this this indent wrong

var lambdaFunc = () => {
     }

    var badIndent = 1
....

Thanks

**Comment by gandm** [comment]
Sorry, but could you give me an code example of where this fails? I only do auto indentation inside JSX.

**Comment by gandm** [comment]
I don't have enough information to understand the problem. I'll close until further info is provided.

**Comment by saidmoya12** [comment]
The problem has been solved,
It seems to be a general atom problem since after the last update it works correctly.

Thanks!!!
