### ISSUE TITLE
Repeating quotes in parenthesis crashes the editor

### ISSUE THREAD

**Issue by TomCaserta** [gandm/language-babel#317]
Okay so I think I have finally found the package that is causing this issue, essentially I have disabled all other extensions and have updated to latest:

Atom 1.13.1
Language Babel 2.50.0
Mac OSX Sierra 

Typing the following in a file defined as Babel ES6 will cause the editor to eventually crash if you continue repeating `'',`

```
('','','','','','','','','','','','','','','','','','')
```

If you have an alphabetical character before the first ( it will not crash. 

I noticed this when pasting a large SQL insert statement into one of my files. 

If there is any other information you require or steps you would like me to take please let me know. Again I am only 90% certain its this package thats causing the issue.

**Comment by gandm** [comment]
Thanks for the report. 2.50.1 should fix this.

**Comment by TomCaserta** [comment]
Perfect, thank you for the very quick fix. Will give it a try now!
