### ISSUE TITLE
How to disable automatic re-write of curly brace indentation?

### ISSUE THREAD

**Issue by derwaldgeist** [gandm/language-babel#318]
If I enable the ```language-babel```plugin, it automatically rewrites:

```js
const test = {
    a:1,
    b:2
};
```
to 
```js
const test = {a: 1, b:2};
```
How can I disable this behavior?

If this is not possible: Is there a way to restrict ```language-babel``` to .jsx files only, and let .js files untouched?

**Comment by gandm** [comment]
I don't rewrite any code in language-babel. Are you sure it isn't another package?

**Comment by derwaldgeist** [comment]
Sorry, you're right, it was caused by atom-beautify.
