### ISSUE TITLE
Is it possible to highlight an HTML template tag?

### ISSUE THREAD

**Issue by Angarsk8** [gandm/language-babel#321]
Hi guys,

Is it possible to highligh the text of a template literal behind an `html` template tag, like this:

```javascript
function TodoForm() {
  return html`
    <input
      type="text"
      id="todo-input"
      onkeydown="
        if(event.keyCode === 13) {
          onSubmitTodo()
        }
      "
    />
    <button onclick="onSubmitTodo()">Add</button>
  `
}
```

**Comment by gandm** [comment]
You need to set the package setting as below 
![image](https://cloud.githubusercontent.com/assets/2313237/22476769/7b64e7d2-e7db-11e6-97ca-f3d90a8d5e2b.png)
[Readme has more info](https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions)

**Comment by Angarsk8** [comment]
Thanks! :+1:

**Comment by dodekeract** [comment]
This is amazing. Thank you so much @gandm.
