### ISSUE TITLE
2 syntax highlighting issues

### ISSUE THREAD

**Issue by Overload119** [gandm/language-babel#322]
```js
class Test() {
   nonBound() { 
   }
    _boundMethod = () => {
    };
}
```

The _boundMethod is rendered slightly differenty.

There's also an issue with elements like this:

```js
<test>
 This has an apostrophe '
</test>

<now everything is highligted like string below>
```

**Comment by gandm** [comment]
I think your using the react package to highlight not mine. `Babel ES6 JavaScript` should be displayed in the bottom status bar.

**Comment by gandm** [comment]
This is my package
![image](https://cloud.githubusercontent.com/assets/2313237/22570970/94c8f068-e995-11e6-913c-54be5d3a6d5f.png)
