### ISSUE TITLE
Tips For Working With HyperX/HyperApp?

### ISSUE THREAD

**Issue by dodekeract** [gandm/language-babel#323]
I recently fell in love with [hyperapp](https://github.com/hyperapp/hyperapp), following a recommendation I found in these issues I added `html:text.html.basic` to my `JavaScript Tagged Template Literal Grammar Extensions`. Only thing is that this **seems to destroy the highlighting of `${regular('javascript').example}` parts**.

I also tried out to use [js-hyperx](https://github.com/mappum/js-hyperx) via `html:source.hx`, but that didn't work well.

Is it possible that this is a `language-babel` bug? IMO it should highlight `${}` parts while giving control of all the other parts to the syntax highlighter chosen.

**Comment by dodekeract** [comment]
![screen shot 2017-02-03 at 00 36 32](https://cloud.githubusercontent.com/assets/1133858/22573350/dfcc958e-e9a8-11e6-97c3-64cde04ca99b.png)

**Comment by gandm** [comment]
Looks like this could be partially fixed inside language-html.

The package's [readme](https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions) has a bit at the bottom that explains why this occurs.
> Please note: As language-babel passes off highlighting of the template to another grammar, it cannot highlight any interpolated code. Actually, that's not strictly correct, as it does highlight interpolated JavaScript code but only at the top most rule stack of the embedded grammar, but this is unlikely to be useful with most grammars. 

In the image below interpolation works until the language-html rules pushes a new context onto the rules stack which appears to happen inside the tag attributes. 

e.g.

1. When language-html finds an open tag it pushed a new rule stack named [tag-stuff](https://github.com/atom/language-html/blob/master/grammars/html.cson#L310) onto the grammar stack and my rules are susspended.
2. [tag-stuff](https://github.com/atom/language-html/blob/master/grammars/html.cson#L506) includes a number of rules including one named `embedded-code` 
3. [embedded-code](https://github.com/atom/language-html/blob/master/grammars/html.cson#L354) only seems to use interpolations from smarty and python. 
4. FIX: If [embedded-code](https://github.com/atom/language-html/blob/master/grammars/html.cson#L354) included interpolations from source.js then the standard atom language-javascript would interpolate that code. If it had an include for source.js.jsx then I would get some form of control back. Maybe an issue should be raised at the [atom repo](https://github.com/atom/language-html)

![image](https://cloud.githubusercontent.com/assets/2313237/22581154/f68d4976-e9d5-11e6-9c0e-7ae986c94bed.png)

**Comment by gandm** [comment]
Just had a thought. My JSX parser is close enough to be used as a replacement parser for HTML in most cases. I just tried using `html:source.js.jsx#jsx` as a template config and it shows as. 
![image](https://cloud.githubusercontent.com/assets/2313237/22582785/de2fb5ca-e9e0-11e6-9fe2-db22666a36e1.png)

**Comment by dodekeract** [comment]
@gandm JSX works well enough for now. Would be awesome if you could duplicate it in a way that properly highlights the `$` part of the escaped expressions though. Oh, and the first line is buggy if you don't do a line-break after

```javascript
html`
```

**Comment by gandm** [comment]
I can't parse `${` inside JSX as it maybe a valid dollar symbol followed by some interpolated value. Also, it would be difficult to fix the requirement of a well known prefix to JSX, in this case starting on a new line, without causing issues. The emmet thing is because they are detecting we're inside a JSX scope, again not much I can do.

I could develop a new subset grammar that handles HTML, and probably Angular, Vue, etc. I'll see if that is trivial or not?

**Comment by dodekeract** [comment]
@gandm never wrote a grammar, but I'd think it'd be trivial to copy-paste the `jsx` grammar to create a `hyperx` one. Changes appear to be minor.

I'd really appreciate it when you have time to do that. No pressure though since `jsx` is close enough.

**Comment by gandm** [comment]
Html is simple enough, it's trying to have a single parser that handles Angular and Vue as well. E.g. Html could have ${{interpolated: object}} Angular and Vue could have ${{avariable}} - a dollar sign  followed by the contents of a variable. Look similar but have quite different effects and parsing required.

You could always ask for language-html to add an option to have embedded JavaScript, as I mentioned earlier. 

I will think about it when I have time.
