### ISSUE TITLE
Any plan to support Styled Jsx syntax highlighting?

### ISSUE THREAD

**Issue by bassbump** [gandm/language-babel#324]
https://github.com/zeit/styled-jsx

**Comment by gandm** [comment]
Not directly, but you can add the string below to one of my package settings (Please update to v2.54.0 first). Having added it. wait 10 seconds and you should see a new extension grammar being created that will do what you want. For more info see [the readme](https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions)

`"(?<=<style jsx>{)|(?<=<style jsx global>{)":source.css`

![image](https://cloud.githubusercontent.com/assets/2313237/22627258/6c97cb68-ebb7-11e6-82e1-60205f8b31e7.png)

should give you something like

![image](https://cloud.githubusercontent.com/assets/2313237/22627288/5d6d3f0a-ebb8-11e6-828f-b1d8b945a229.png)

**Comment by gandm** [comment]
If you also need to embed interpolations like `${something => something}` then you may want to use my css grammar instead. This is used by styled-components.

e.g.
`"(?<=<style jsx>{)|(?<=<style jsx global>{)":source.css.styled`

**Comment by bassbump** [comment]
Thanks that works perfectly

**Comment by oleole90** [comment]
@gandm Noob here. Can't seem to find the 'settings' tab. Closest i got it this:
<img width="1087" alt="screen shot 2017-06-05 at 2 59 48 pm" src="https://cloud.githubusercontent.com/assets/4123376/26777628/c683e638-49ff-11e7-8a7b-8b4f4b75d84c.png">

**Comment by gandm** [comment]
@oleole90 Atom settings for the editor itself as well as all package options are available via the settings menu option or via the shortcut `ctrl+,` From there goto to the packages and select language-babel.

**Comment by oleole90** [comment]
@gandm There is just a Readme file there.
<img width="923" alt="screen shot 2017-06-05 at 4 12 28 pm" src="https://cloud.githubusercontent.com/assets/4123376/26780067/d1ba50a0-4a09-11e7-9140-62dad3327a61.png">


**No editable input field** found like yours
<img width="923" alt="screen shot 2017-06-05 at 4 12 28 pm" src="https://cloud.githubusercontent.com/assets/2313237/22627258/6c97cb68-ebb7-11e6-82e1-60205f8b31e7.png">

Another thing is confusing me is that:
inside:
`packages/language-babel/grammars/Babel Language.json` there is a valid json there but `"(?<=<style jsx>{)|(?<=<style jsx global>{)":source.css` looks like a reverse json to me! How can I even put something like this inside a json (as mentioned [here](https://atom.io/packages/language-babel#javascript-tagged-template-literal-grammar-extensions)) about `scopeName`?


<img width="768" alt="screen shot 2017-06-05 at 5 13 28 pm" src="https://cloud.githubusercontent.com/assets/4123376/26781841/5d37df3c-4a12-11e7-8466-5994aa67d4b4.png">

**Comment by gandm** [comment]
@oleole90  If you don't see any settings it looks like the package isn't installed correctly. Uninstall it and re-install & restart Atom and try again. Please do not attempt to change any of the language-babel JSON files directly.
You should see:-
![image](https://cloud.githubusercontent.com/assets/2313237/26782408/6b0b2a3c-49eb-11e7-9def-4ed907e34415.png)

The setting you mention actually creates a new grammar file.  language-babel changes the setting provided to a valid JSON grammar file. Also, use `"(?<=<style jsx>{)|(?<=<style jsx global>{)":source.css.styled` as this allow for syntax, interpolation and auto-completion of styled CSS.

The grammar file created byt the above would look something like.
![image](https://cloud.githubusercontent.com/assets/2313237/26782446/90d70baa-49eb-11e7-992b-197a9f049967.png)

**Comment by oleole90** [comment]
Yayyy! It's working after uninstall>Restart>Install!
Thank you so much dude! **You're awesome!**
<img width="229" alt="screen shot 2017-06-05 at 5 51 51 pm" src="https://cloud.githubusercontent.com/assets/4123376/26782963/b47c6664-4a17-11e7-982f-7c04bc3ca8fc.png">

**Comment by kudorori** [comment]
If i need to let him support 
```
export default `div {display: inline-block}`
```
How do i do it

**Comment by gandm** [comment]
@kudorori The tagged template literal could contain any type of data. In your case it is CSS but it could easily be SQL, GraphQL,.... and I have no way of knowing. You could do:-
```js
export default /*css*/`div {display: inline-block}`
```
and then in my [tagged template grammar configuration option](https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions) add the following
```
/*sc*/:source.css.styled
```

If you are using [Zeit's styled JSX](https://github.com/zeit/styled-jsx) then the string in this config will look like

```"(?<=<style jsx>{)|(?<=<style jsx global>{)":source.css.styled,/*sc*/:source.css.styled```

**Comment by kudorori** [comment]
@gandm It works for me, great!

**Comment by ArtyomResh** [comment]
Can't make it work with nuclide atom IDE, before nuclide it works great
