### ISSUE TITLE
Prevent backtick autoinsertion after ENTER press 

### ISSUE THREAD

**Issue by mqklin** [gandm/language-babel#328]
What I want is to prevent backtick autoinsertion (especially when closing backtick is already exist), but leave autoindent as is. 
![babel-language](https://cloud.githubusercontent.com/assets/9456433/23092200/7e89d55c-f5e7-11e6-826c-22d149008599.gif)

**Comment by gandm** [comment]
I don't auto insert that backtick. It is done by [Atom's bracket-matcher](https://github.com/atom/bracket-matcher)

**Comment by gandm** [comment]
I did notice that bracket-matcher doesn't add a backtick when it is preceded by a tagname. I have fixed this issue by doing it in my code and a side effect of this is that I can be more consistent when handling non tagged templates. I think that will cure the issue you see.  I'll roll that out sometime this week.

**Comment by mqklin** [comment]
Thank you very much for the fix!
