### ISSUE TITLE
Backticks added in pairs since the last release

### ISSUE THREAD

**Issue by garth** [gandm/language-babel#330]
Even when disabled in bracket matcher, bacticks are now always entered in pairs when language-babel is enabled.

**Comment by gandm** [comment]
Yes. bracket-manager closed isolated backticks but never closed a backtick when entered after a tagname which was annoying and inconsistent. I added this to language-babel to fix that. I actually made a config option to disable this but didn't roll with it. Does it annoy you?

**Comment by garth** [comment]
I have auto close turned off for everything, so having language-babel appear to ignore the setting is not great. An option would be ok, but if you could read the option from bracket-manager that would be even better.

**Comment by garth** [comment]
Thanks @gandm, very much appreciated!

**Comment by gandm** [comment]
Whoops! that was a mess! Try 2.55.4

**Comment by garth** [comment]
tested, works great!

**Comment by cusxio** [comment]
Thank you ! @gandm
