### ISSUE TITLE
Destructuring const { variable: COOLUPPERCASENAME } = object;

### ISSUE THREAD

**Issue by persocon** [gandm/language-babel#332]
When I do that:
![screen shot 2017-02-23 at 7 04 11 pm](https://cloud.githubusercontent.com/assets/1276067/23281152/e73f0560-f9fa-11e6-861c-c86f34c1bcce.png)

the ABC is set for another color that is not for variables 🤔 
am I doing something wrong or broke the thing?

**Comment by dodekeract** [comment]
I think that's just because `UPPERCASE` is usually a constant and that overwrites the variable highlighting.

**Comment by persocon** [comment]
Damn, true, forgot about constants :/ that's sad, and no way to know if it's a variable whatsoever right? :(

**Comment by persocon** [comment]
it's kinda the same color if you don't use as shorthand 🤔  if I do what I'm doing but without the shorthand it colors alright:

![screen shot 2017-02-24 at 1 00 29 pm](https://cloud.githubusercontent.com/assets/1276067/23310422/3f2ee056-fa91-11e6-8f8c-cfb254144259.png)

**Comment by gandm** [comment]
Yes that's why I need t make the change so that shorthand constant properties are the same color as a constant var.

**Comment by gandm** [comment]
e.g.
![image](https://cloud.githubusercontent.com/assets/2313237/23310636/1bf16aea-faab-11e6-9f0b-b4388537e5e0.png)
