### ISSUE TITLE
Fix tagged template extensions so `template:custom-scope` can be used

### ISSUE THREAD

**Issue by jwhitmarsh** [gandm/language-babel#338]
See #200 for initial conversation.

The tagged template extension `"(?<=template\:\s)"` doesn't work. 
> It's because template: is being matched inside my grammar and uses moustache as per the original request of the OP. This was before I implemented tagged template extensions as an option and it has precedence over any regex supplied. Can you open a new issue and I'll look at changing the precedence so that it will work.

**Comment by gandm** [comment]
Please use the following regex format
`template::text.html.angular, "(?<=template\s=\s)":text.html.angular`

as for commenting inside language-mustache, someone at Atom appears to have forgotten to add the commenting used by this language so it defaults.
