### ISSUE TITLE
Can't manually change language to babel

### ISSUE THREAD

**Issue by dodekeract** [gandm/language-babel#341]
Recently (I think after the fix for very long lines) my atom stopped accepting `Babel ES6 JavaScript` when setting it manually (via the language selection dialog). It works perfectly fine when opening files but most of the times I can't get it to load via said dialog.

What happens instead is that it doesn't change the language at all. It just stays at whatever I selected before that. No errors are shown in the console.

---

**Atom**: `1.15.0`
**language-babel**: `2.57.0`
**OS**: `macOS Sierra 10.12.3 (16D32)`
**atom-react-native-autocomplete issue**: TOP-Chao/atom-react-native-autocomplete#12

**Comment by gandm** [comment]
I have seen this behaviour but only when also running the  atom `react` grammar package as well. Are you running that?

**Comment by dodekeract** [comment]
![screen shot 2017-03-22 at 20 58 13](https://cloud.githubusercontent.com/assets/1133858/24218091/48892e16-0f42-11e7-9d80-daae9c006e56.png)

**Comment by gandm** [comment]
can you let me have the output from `apm list`. Thanks

**Comment by dodekeract** [comment]
Sure.

<details>
<summary>`app list`</summary>
```
[36mBuilt-in Atom Packages[39m (89)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.9.1
├── one-light-ui@1.9.1
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.2
├── archive-view@0.62.2
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.15.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.34.2
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.0
├── background-tips@0.26.1
├── bookmarks@0.44.1
├── bracket-matcher@0.85.2
├── command-palette@0.40.1
├── deprecation-cop@0.56.2
├── dev-live-reload@0.47.0
├── encoding-selector@0.23.1
├── exception-reporting@0.41.0
├── find-and-replace@0.206.3
├── fuzzy-finder@1.4.1
├── git-diff@1.3.1
├── go-to-line@0.32.0
├── grammar-selector@0.49.1
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.36.1
├── line-ending-selector@0.6.1
├── link@0.31.2
├── markdown-preview@0.159.6
├── metrics@1.1.3
├── notifications@0.66.2
├── open-on-github@1.2.1
├── package-generator@1.1.0
├── settings-view@0.247.0
├── snippets@1.0.5
├── spell-check@0.70.2
├── status-bar@1.8.1
├── styleguide@0.49.2
├── symbols-view@0.114.0
├── tabs@0.104.1
├── timecop@0.34.0
├── tree-view@0.214.1
├── update-package-dependencies@0.10.0
├── welcome@0.36.0
├── whitespace@0.36.2
├── wrap-guide@0.39.0
├── language-c@0.56.0
├── language-clojure@0.22.2
├── language-coffee-script@0.48.5
├── language-csharp@0.14.2
├── language-css@0.42.0
├── language-gfm@0.88.1
├── language-git@0.19.0
├── language-go@0.43.1
├── language-html@0.47.2
├── language-hyperlink@0.16.1
├── language-java@0.26.0
├── language-javascript@0.126.1
├── language-json@0.18.3
├── language-less@0.30.1
├── language-make@0.22.3
├── language-mustache@0.13.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.4
├── language-property-list@0.9.0
├── language-python@0.45.2
├── language-ruby@0.70.5
├── language-ruby-on-rails@0.25.2
├── language-sass@0.57.1
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.3
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.16
└── language-yaml@0.28.0

[36mCommunity Packages (91)[39m /Users/dodekeract/.atom/packages
├── Atom-Syntax-highlighting-for-Sass@0.5.0
├── advanced-open-file@0.16.6
├── ascii-hex@0.2.0
├── atom-alignment@0.12.1
├── atom-clock@0.1.6
├── atom-itunes@0.5.0
├── atom-react-native-autocomplete@0.0.27
├── atom-reverser@2.6.0
├── atom-sort-sass@0.2.1
├── atom-ternjs@0.18.2
├── autocomplete-js-import@1.4.0
├── autocomplete-json@5.4.0
├── autoupdate-packages@1.3.1
├── base64@0.3.0
├── caniuse@0.9.0
├── change-case@0.6.3
├── change-tabs@0.2.0
├── color-picker@2.2.5
├── count@1.1.3
├── custom-folds@1.9.3
├── dash@1.7.1
├── edit-in-new-tab@0.9.1
├── emmet@2.4.3
├── es-identifier-highlight@0.4.3
├── file-icons@2.1.1
├── flex-tool-bar@0.12.0
├── git-control@0.8.2
├── git-diff-details@1.4.0
├── git-time-machine@1.5.6
├── github-issues@0.8.3
├── glacier-dark-syntax@0.7.0
├── hex@0.6.2
├── highlight-bad-chars@1.0.5
├── highlight-column@0.5.2
├── http-status-codes@1.0.4
├── intentions@1.1.2
├── js-hyperx@1.1.0
├── language-assembly@0.7.1
├── language-babel@2.57.0
├── language-docker@1.1.7
├── language-dotenv@1.0.0
├── language-gitignore@0.3.0
├── language-glsl@2.0.1
├── language-haskell@1.12.1
├── language-ini@1.19.0
├── language-latex@1.0.0
├── language-nginx@0.6.2
├── language-pfm@0.82.0
├── language-prolog@0.10.0
├── language-swift@0.5.0
├── linter@2.1.0
├── linter-gcc@0.7.1
├── linter-ui-default@1.2.1
├── linter-write-good@0.8.0
├── markdown-preview-plus@2.4.9
├── markdown-table-formatter@2.9.0
├── markdown-toc@0.4.2
├── min-ui@0.0.4
├── minimap@4.26.8
├── minimap-bookmarks@0.4.2
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.5.0
├── minimap-pigments@0.2.2
├── minimap-selection@4.4.0
├── multi-cursor@2.1.5
├── native-ui@0.20.4
├── new-fast-duplicate@2.0.0
├── node-debugger@1.10.1
├── open-path@0.3.6
├── pane-split-moves-tab@0.1.0
├── pdf-view@0.56.0
├── pigments@0.39.1
├── processing@0.13.0
├── processing-language@0.2.0
├── project-jump@0.3.0
├── project-plus@0.9.0
├── sorter@1.1.0
├── source-preview@0.5.0
├── source-preview-markdown@0.1.1
├── source-preview-sass@0.1.6
├── svg-preview@0.11.0
├── sync-settings@0.8.1
├── toggle-markdown-task@0.6.0
├── tool-bar@1.1.0
├── trailing-spaces@0.4.0
├── tree-view-git-status@1.3.1
├── url-open@0.1.0
├── wakatime@6.0.13
└── zentabs@0.8.8
```
</details>

**Comment by dodekeract** [comment]
Let me know when you need more information. I'm quite familiar with the debugger too, so I'll be able to send you further information if you tell me "set a breakpoint on this line, etc.".

**Comment by gandm** [comment]
I loaded those packages apart from 3 that didn't work on my system but it all seemed OK. I don't do anything to support the switching of languages as Atom does it all. Can you let me have your config.cson file?

If you want to run a debugger. Search for the keyword setGrammar and inside the Atom text-editor.js file set a breakpoint at the end of the function TextEditor.prototype.setGrammar as below. This is fired when Atom detects a language change and hovering over the grammar variable on a break should show which grammar is being asked for,

![image](https://cloud.githubusercontent.com/assets/2313237/24235448/45ac8e92-0f95-11e7-986a-1d193139b59c.png)

**Comment by dodekeract** [comment]
@gandm The debugger thing actually helped in an unexpected way. I saw some references to `language-javascript-jsx`. Disabling this package and reloading fixed the issue. Weird.

I think this is related to the order in which both packages are installed/loaded. When I first enable `language-babel` and then enable `language-javascript-jsx` I can only switch to `JavaScript with JSX`. If I do it the other way around I can only switch to `Babel`.

I'd assume it's related to both using the same language scope. Probably an upstream/atom bug then.

**Comment by dodekeract** [comment]
Mystery solved: 
![screen shot 2017-03-23 at 16 50 18](https://cloud.githubusercontent.com/assets/1133858/24256586/d9b53c62-0fe8-11e7-8dd7-79e3b665fc01.png)

**Comment by gandm** [comment]
@dodekeract thanks for the feedback. One of your packages, `atom-react-native-autocomplete` - notified me to install language-javascript-jsx but as it wasn't in your apm list I didn't bother. I guess this is the issue I see when I enable the react package. I'll do some investigation time permitting. I'll close this issue but feel free to re-open if needed. 😄  🥇
