### ISSUE TITLE
JSX comments

### ISSUE THREAD

**Issue by mxstbr** [gandm/language-babel#345]
<img width="941" alt="screen shot 2017-03-30 at 14 13 58" src="https://cloud.githubusercontent.com/assets/7525670/24503623/25831c58-1553-11e7-89c0-c3f1b02d9056.png">

Newlines (and spaces, for that matter) between `*/` and `}` break comment highlighting in JSX horribly eventhough the compiler still treats them as expected. `prettier` (the JS formatter) will format comments that way, so there's no way for me to avoid that :cry:

**Comment by gandm** [comment]
Just pushed a fix 2.57.2  It needs Atom.1.15.0  due to a bump in depends.

**Comment by mxstbr** [comment]
Uhh, I'd check if that fixed it but Atom apparently doesn't want me to 😅 

<img width="743" alt="screen shot 2017-03-30 at 17 21 38" src="https://cloud.githubusercontent.com/assets/7525670/24512203/39a128cc-156e-11e7-8ee3-1533a2b6deb9.png">

Going to assume this is fixed, closing!

**Comment by gandm** [comment]
Only hits I can find ref that error are to do with seti-syntax See https://github.com/atom/apm/issues/620 & https://github.com/atom/atom/issues/14057

I just installed 2.57.2 with on Atom 1.15 with no issues.

**Comment by mxstbr** [comment]
No worries, I assume this is an issue with my setup. Thanks!
