### ISSUE TITLE
Highlighting of Pure React Components

### ISSUE THREAD

**Issue by prescottprue** [gandm/language-babel#346]
The highlighting of Pure React components just changed with todays release:

![image](https://cloud.githubusercontent.com/assets/2992224/24518584/56f5211c-1537-11e7-91ed-5530c79d1bcf.png)

**Used To Be:**

![image](https://cloud.githubusercontent.com/assets/2992224/24518458/f217fd1e-1536-11e7-9110-42f1ef265f07.png)

Was this intentional? Is there a way to switch it back?

**Comment by gandm** [comment]
Nothing has changed that would cause this to my knowledge. Are you sure you are using language-babel? Maybe it wasn't updated correctly? Below is one-dark, not sure what your theme is.

![image](https://cloud.githubusercontent.com/assets/2313237/24519111/0ae8b99c-157c-11e7-825d-c620ab168e67.png)

**Comment by prescottprue** [comment]
Thanks for the quick response!

It is the Monokai theme, but it was also happening with OneDark.

Rebooting my computer and atom made it go back to normal? Either way, it is fixed now.
