### ISSUE TITLE
Forward tabs not working.

### ISSUE THREAD

**Issue by admmasters** [gandm/language-babel#347]
STR:
Try and indent some code by using tab.

Expected:
Tab indents the code as expected.

Actual:
Tab does not do anything. This is working on the standard JS grammar that Atom ships with.

**Comment by gandm** [comment]
This is an Atom issue but I don't know what causes it. Probably something to do with a partial install of the package. e.g. https://github.com/gandm/language-babel/issues/325

**Comment by admmasters** [comment]
How weird, ok thanks - I'll try and look into it further.

**Comment by admmasters** [comment]
Yep its exactly as you said. Thanks for the speedy reply anyway!
