### ISSUE TITLE
Is there a way to automatically rename transpiled file on save?

### ISSUE THREAD

**Issue by pingshunhuangalex** [gandm/language-babel#350]
Hi @gandm 

Sorry I'm really new to this. When I saw babel, the first thing that jumps into my head is SASS which leads me to the below questions.

1. Is there a way to automatically rename files with a suffix after transpiling, let's say from *.es6.js to *.js? (I know .es6 file can be automatically converted to .js files, but I don't know how to let them follow a naming pattern)

2. Is there any chance `language-babel` can also integrate minify/uglify features right after transpiling?

3. Also, I'm having troubling finding the difference among .js, .es6, .es, .babel. Some explanation would be nice. Thanks.

**Comment by gandm** [comment]
@pingshunhuangalex 

For most large applications I would suggest using Webpack to build an app. If you app is small and relatively simple then by all means use the transpile features of this package.

In general you would use different directories for the source files (normally source) and transpiled files (normally named dist). I would suggest you only use `.js` suffixes for any file - including JSX, flow etc.  If you look at the language-babel repo you will see that the package has a single js file in the `src` directory that gets transpiled into the `lib` directory when saved.  In the `src` directory the transpile is controlled via the `.babelrc` and `.languagebabel` files [here](https://github.com/gandm/language-babel/tree/master/src)

To minify you could use a specail babel-preset [Babili)(https://github.com/babel/babili) that minifies the output.

Their is no difference between the use of any file suffixes. Some people prefer to have different suffixes as these highlight that some transpile is required. e.g. Some use `.jsx` to indicate that a file contains JSX and needs to be transpiled.

**Comment by pingshunhuangalex** [comment]
Thanks for clearing things out @gandm :)

**Comment by pingshunhuangalex** [comment]
Sorry @gandm one more question.
Is there a way to set the transpile path to a relative path based on the source file. I know if I leave both fields empty, it'll just create the transpiled file in the same folder which is actually relative path already. Thanks.

**Comment by gandm** [comment]
@pingshunhuangalex Not sure exactly what you mean but if babelSourcePath is source and babelTranspilePath is dist and your project is at /usr/fred/proj, then files in /usr/fred/source/anydir/anyotherdir will end up in /usr/fred/proj/dist/anydir/anyotherdir.

Is this what you mean?

**Comment by pingshunhuangalex** [comment]
@gandm Thanks for the reply.
I understand what you explained, but what I mean is it would be nice to set transpiled path to something like ../test/js. In this case, regardless the file structure of the project, I'll always have my transpiled files waiting in a separate "test" folder outside the source file folder.
The reason for this is I use Django, and pages are created in different folders in the form of apps. With this feature, I can easily put one rule in the package.json instead of having individual .languagebabel file in each app. Thanks.

**Comment by gandm** [comment]
@pingshunhuangalex the paths are based upon the `projectRoot` either implicitly as opened in Atom, or explicitly by using the `projectRoot` property in .languagebabel. If you don't want to use a .languagebabel file then your options are limited. `projectRoot` forces  .. and . on that directory rather than the Atom opened directory.

You could always have babel files using a `.babel` or `.es6` suffix and transpile these into the same directory using the .babelrc `only` option. Something like [here](https://github.com/gandm/example-language-babel/tree/master/Source%20Files/Transpile%20In%20Place) but without a .languagebabel file.

**Comment by pingshunhuangalex** [comment]
Thanks for the example. That's the approach I'm using now. Thanks.
