### ISSUE TITLE
Feature request: transform to clipboard

### ISSUE THREAD

**Issue by thornomad** [gandm/language-babel#352]
I wanted to setup an action that would transform the active editor window and save it to the clipboard.  For example:

```coffee
babel = require('babel-core')

atom.commands.add 'atom-text-editor',
  'language-babel:copy-to-clipboard': (event) ->
    editor = atom.workspace.getActiveTextEditor()
    editorText = editor.getText()
    transpiledText = babel.transform(editorText).code
    atom.clipboard.write transpiledText
```

Is that something that could be added as a feature?  I'm still trying to figure out how to do it on my own machine because I can't seem to `require()` a package from inside `init.coffee` as it is.  But it works in the terminal.  Thanks.

**Comment by gandm** [comment]
language-babel has a [Provider Service](http://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/)  that can be used for transpiling code. Maybe that would be the best way of doing this? The code is [here](https://github.com/gandm/language-babel/blob/master/lib/transpiler.coffee#L55-L88) the provider def is [here](https://github.com/gandm/language-babel/blob/master/lib/transpiler.coffee#L55-L88) and returns a Promise that resolves to the transpiled code. It is used by [atom-source-preview](https://github.com/aki77/atom-source-preview) and the associated code used by that package is [here](https://github.com/aki77/atom-source-preview/blob/master/lib/preview-view.coffee#L91-L103)

The filename must be a real path as the transpiler looks for `.babelrc`, `package.json` files in the directory path. Also, babel resolves any presets/plugins in the node-modules directories of that path.

**Comment by gandm** [comment]
Something like this might work 
```js
atom.packages.serviceHub.consume('preview.provider','0.1.0', (t) => 
   t.transform('my code',{filePath: '\\x.js', sourceMap: false}));
```

**Comment by thornomad** [comment]
Awesome! Thank you for that quick tip!  

Did this quickly but it seems to work in `init.coffee`:

```coffee
'language-babel:copy-to-clipboard': (event) ->
  editor = atom.workspace.getActiveTextEditor()
  editorText = editor.getText()
  atom.packages.serviceHub.consume 'preview.provider', '0.1.0', (t) ->
    transformPromise = t.transform editorText, {filePath: editor.getPath(), sourceMap: false}
    transformPromise.done ({code}) ->
      atom.clipboard.write code
```

I'm all set for my purposes.  If you wanted to add this to the plugin I'd be happy to create a pull request.

**Comment by gandm** [comment]
@thornomad Glad it worked. Not sure if it should be in the core package. I would think not.
