### ISSUE TITLE
Shorthands for key:value are being printed as constants

### ISSUE THREAD

**Issue by gustavoalfaro** [gandm/language-babel#353]

**Comment by dodekeract** [comment]
Can't really reproduce. They get rendered differently, but not as a constant.

![screen shot 2017-04-20 at 19 57 46](https://cloud.githubusercontent.com/assets/1133858/25245126/a4a850fa-2603-11e7-8b00-42e12e5f25af.png)

**Comment by gustavoalfaro** [comment]
![image](https://cloud.githubusercontent.com/assets/21284308/25245234/fff200c0-25c0-11e7-8b50-00357b6e0192.png)

not constant?

**Comment by gustavoalfaro** [comment]
![image](https://cloud.githubusercontent.com/assets/21284308/25245307/385bbfa0-25c1-11e7-98c0-e6298c9b996f.png)
not constant?

**Comment by dodekeract** [comment]
@gustavoalfaro That's your theme then. As you can see mine doesn't render them *the same*.

**Comment by gandm** [comment]
I think it's a change I made yesterday. I spotted a mistake in the grammar and fixed it but the way it originally worked meant lowercase shorthand props were shown as vars. This was the change https://github.com/gandm/language-babel/commit/6db89e3c13415a17382962fe1aa5064a271725c7

I'll remove the ref to constant as it probably shouldn't be there at all.

**Comment by gandm** [comment]
@gustavoalfaro Should be fixed in 2.57.5.

**Comment by gustavoalfaro** [comment]
Thanks!
