### ISSUE TITLE
Highlight for switch case not displaying properly

### ISSUE THREAD

**Issue by atilacamurca** [gandm/language-babel#354]
Consider the following code:

```js
const value = 'a'
switch (value) {
    case 'a':
        console.log('a')
        var c = 4
        break
    case 'b':
        console.log('b')
        break
    default:
        return `Value ${value} not supported`
}
```

The image bellow shows `case 'b':` not properly highlighted.

![babel-highlight](https://cloud.githubusercontent.com/assets/508624/25304739/bc091af4-2743-11e7-93ba-d05c066d473c.png)

The Syntax Theme is Monokai, but even with other themes the same happens.

Hint: if I remove the declaration `var c = 4` the problem does not appear.

**Comment by gandm** [comment]
Try 2.57.6

**Comment by atilacamurca** [comment]
Works great!

Thanks for taking your time to work on this package.
