### ISSUE TITLE
Preserve line breaks?

### ISSUE THREAD

**Issue by JeffML** [gandm/language-babel#355]
this packages seems to want to push chained functions onto one line:

```
f("foo")
.then(result => {...})
.then(data => {...})
.catch(e => {console.error(e)})
```

becomes:
`
f("foo").then(result={...}).then(data => {...}).catch(...`

I hate that. Can I turn that off with "Preserve Line Breaks" or something?

**Comment by gandm** [comment]
Nothing to do with my package. I don't merge lines. Maybe another package such as atom beutify.

Sent from my Windows Phone
________________________________

**Comment by gandm** [comment]
I know that prettier does that type of formatting.

**Comment by JeffML** [comment]
It was atom-beautify that was doing it, thanks for the info.
