### ISSUE TITLE
Styled Components Highlighting with differently-named import

### ISSUE THREAD

**Issue by scottluptowski** [gandm/language-babel#358]
Hi,

I notice that the syntax highlighting only works correctly when styled components are defined with `styled`, as in:

```jsx
const Foo = styled.div`
  color: blue;
`
```

Many of the files in my project `import s from 'styled-components'` and creating a component with ``` s.div`` ``` does not trigger the syntax highlighting.

Is there planned support for this behavior? I tried looking through the source but couldn't see where I would make this change 😄 

Thanks

**Comment by gandm** [comment]
I won't make this change in the core product as everyone is likely to use a different namespace name. Also, this is likely to break the babel parsers coming in V2 of styled components.

However, the current language babel settings allow you to configure this change. 

Use the following
```"(?:\bs\.\s*\w+)|(?:\bs\s*(\((?:(?>[^()]+)|\g<-1>)*\))*)":source.css.styled```
in the package settings as below
![image](https://cloud.githubusercontent.com/assets/2313237/25491701/ae45e946-2b68-11e7-81a9-81e9856335db.png)
and after 10 seconds a new extension grammar will be created that does what you want.
