### ISSUE TITLE
Change styled-components comments to match prettier

### ISSUE THREAD

**Issue by k15a** [gandm/language-babel#365]
Hey,

is there a way to support Prettiers comment style in styled-components tagged template strings?
Prettier is actually formatting the styled-components comments to `${/* border-top: 4px; */ ''}` while language-babel uses `${''/* border-top: 4px; */}`.

I've opened an issue at https://github.com/prettier/prettier/issues/1589 and they said that they could move the empty string to the front but they wont remove the space. This would then look like `${'' /* border-top: 4px; */}`. Is it possible that language-babel adds the ability uncomment both styles with the shortcuts?

It seems to me that atom only support one syntax so it would be great if both sides could meet in the middle :)

**Comment by gandm** [comment]
Atom only supports a single key binding for comments. In order to use another I'd have to program it.

I could make my code match Prettier's syntax. I guess people who have already commented some lines and want to uncomment after I change the code might be a bit annoyed. Also, I don't think it is as nice, as the Babel transform makes it look strange with the argument after the comment and the space stripped off. Makes it hard to read - something like 
```js
styled.div(_templateObject, /* color: inherit;
                            margin: auto;   */'');
```
I'd prefer `${'' /* border-top: 4px; */}` as it at least looks better after transpilling.

**Comment by k15a** [comment]
I agree with you that people would be annoyed right after the change.
Adding the space would be totally sufficient so prettier could move the empty string to the front.

Thank you for considering it. (:

**Comment by gandm** [comment]
@k15a Just pushed a commit that adds the space. If prettier changes the format can you plese check this change against prettier? If it works I'll publish.

**Comment by k15a** [comment]
Thank you very much. I will report back to you once prettier changed the behaviour.

**Comment by k15a** [comment]
The changes at prettier landed on master and it's working in combination with the language-babel changes.

**Comment by gandm** [comment]
@k15a There appears to be some debate on the Prettier PR you did on whether this is a good idea. I'll refrain from publishing this change until it is resolved.

**Comment by MrLoh** [comment]
I'm really confused as to what the state of this is, but it is crucial to get this fixed for using babel and prettier together, which are both such amazing projects. What can be done to move this forward?

**Comment by gandm** [comment]
@MrLoh A couple of things. I was waiting on the outcome of https://github.com/prettier/prettier/pull/1713/ to see if that made any material changes to template comments and although prettier has the new form of commenting syntax but prettier-atom doesn't, as it is using an older master.

I will re-instate this change soon but I also need to make some changes to support styled-components V2.
