### ISSUE TITLE
green underline indicating enclosing JSX tags overflowed

### ISSUE THREAD

**Issue by wangxd18** [gandm/language-babel#367]
Code:
```
<Foo
  bar="baz">
</Foo>
```

Expected: ![image](https://cloud.githubusercontent.com/assets/1212320/26104307/289814be-3a35-11e7-8ae5-31e4cd2a4e40.png)

Actual outcome: ![image](https://cloud.githubusercontent.com/assets/1212320/26104293/19c6f86a-3a35-11e7-8a9e-ce26de32d951.png)

**Comment by gandm** [comment]
Nothing to do with language-babel, more likely another package. Atom's bracket-matcher does the underlining of tags matches not language-babel. I tried it with Oceanic-Next; think that's what you used; seems OK.

![image](https://cloud.githubusercontent.com/assets/2313237/26104686/e698f9d2-3a36-11e7-9c1c-e0083a148358.png)

**Comment by gandm** [comment]
Found an issue here that matches your problem https://github.com/atom/bracket-matcher/issues/208 so closing.

**Comment by wangxd18** [comment]
Oh, sorry for the noise. Thanks for the quick reply.
