### ISSUE TITLE
Correctly indent ternary statements in JSX

### ISSUE THREAD

**Issue by peterjacobson** [gandm/language-babel#369]
Current auto-indentation
```
trainerProfile.backgroundImageLink
  ? <Image style={styles.video} source={{uri: `${AppConfig.apiURL}${trainerProfile.backgroundImageLink}`}} />
: <Image style={styles.video} source={{uri: `https://placehold.it/375x140`}} />
```

desired auto-indentation
```
trainerProfile.backgroundImageLink
  ? <Image style={styles.video} source={{uri: `${AppConfig.apiURL}${trainerProfile.backgroundImageLink}`}} />
  : <Image style={styles.video} source={{uri: `https://placehold.it/375x140`}} />
```

**Comment by gandm** [comment]
Just tried it and It seems to auto-indent correctly for me,  i.e. as in your 'desired' indentation. 
Can you let me have any surrounding JSX code as well?

**Comment by gandm** [comment]
closing issue. post some more more info if you want to reopen.

**Comment by irrvrsl** [comment]
Hello! I have a similar issue with ternary statements. 
![image](https://user-images.githubusercontent.com/10095366/27080185-9f71eb0e-505c-11e7-9c46-16166723452c.png)

**Comment by gandm** [comment]
@irrvrsl thanks for that. I will do something to fix auto indentation of ternaries as it seems to be a contentious area. I've been looking at the issues raised on the prettier repo and everyone has a different idea. Anyway leave it with me.

**Comment by irrvrsl** [comment]
Thanks for a quick response! Let me know if you need my configuration or any other information related to this question.

**Comment by gandm** [comment]
@peterjacobson @irrvrsl I hope the latest release fixes your issues.
