### ISSUE TITLE
backtick-matcher surround disabled with backticks

### ISSUE THREAD

**Issue by Kalcode** [gandm/language-babel#370]
bracket-matcher allows you to highlight text and hit ``(, {, [, ', ", or ` `` to surround the highlighted text with said brackets or backticks or quotes. 

But this lines of code 

```
insertBackTick: () ->
    return true unless @bracketMatcherBackticks()
    cursorBufferPosition = @editor.getCursorBufferPosition()
    return true if 'punctuation.definition.quasi.begin.js' is @editor.scopeDescriptorForBufferPosition(cursorBufferPosition).getScopesArray().slice(-1).toString()
    @editor.insertText("``")
    @editor.moveLeft()
    false
```
https://github.com/gandm/language-babel/blob/master/lib/did-insert-text.coffee#L60-L69 

Replaces the text in the cursors with two backticks instead of a surround. 

I added the following myself and it seems to work solve both cases, doubletick after word and preserve the surround. But I am not an atom expert and I am not sure of the consequences of it.

```
insertBackTick: () ->
    selectedText = @editor.getSelectedText()
    ...
    @editor.insertText("`" + selectedText + "`")
```

Either way I am hoping this can be remedied as I like having the ability to highlight and surround. But this package of yours is a must for me. Also thanks for the hard work of providing this to the community.

**Comment by gandm** [comment]
Looks sensible. I don't think it will cause any issues so I will look at doing this change.
