### ISSUE TITLE
Fix Styled Components highlighting for v2

### ISSUE THREAD

**Issue by philpl** [gandm/language-babel#371]
In v2 (which will be officially released shortly, and is currently in RC) we have a few new methods which will need to be added to the syntax highlighting. The three methods are:

### `.extend`

```js
const Comp = styled.div`color: red;`

const NewComp = Comp.extend`
  color: green;
`
```

### `.extendWith()`

```js
const Comp = styled.div`color: red;`

const NewComp = Comp.extendWith('span')`
  color: green;
`
```

### `SC.attrs({})`

```js
const Link = styled.a.attrs({
  target: '_blank'
})`
  color: red;
`
```

I hope this isn't too much trouble :)

**Comment by gandm** [comment]
Are these documented anywhere?

**Comment by philpl** [comment]
The upcoming docs (will be released in tandem with v2) have an API section: https://sc-next-docs.philpl.com/docs/api

**Comment by mxstbr** [comment]
`.extendWith` is now called `.withComponent`, that's the last change we'll do though!

**Comment by gandm** [comment]
@mxstbr @philpl OK, will make the changes asap. On other things at the moment.

**Comment by mxstbr** [comment]
Awesome, thanks @gandm. (we're releasing sometime today! 🚢  exiting)

**Comment by mxstbr** [comment]
You're the best @gandm, thanks so much! :tada:

**Comment by DJTB** [comment]
The new api is all looking good (extend, withComponent, attrs), except one use-case slipped through:

![image](https://cloud.githubusercontent.com/assets/5353151/26495426/cbce34c4-4223-11e7-86df-559eb4f8cadf.png)
