### ISSUE TITLE
VS Code

### ISSUE THREAD

**Issue by svipben** [gandm/language-babel#374]
Hello,

this plugin is really awesome. Any chance to make it available for VS Code? I really like colored Flow comments.

**Comment by gandm** [comment]
People have ported this grammar to vscode in the past but never seem to have maintained it.  I guess most people use  VScode's new TypeScript grammar that also works pretty well with most flow constructs. Microsoft seem to support this grammar very well so I would suspect another similar grammar wouldn't get much traction and wouldn't be worth the support overhead. Also, i don't believe many people use the commenting form of flow syntax, but maybe I'm wrong.

**Comment by svipben** [comment]
@gandm stylelint is using flow syntax in comments, I'm using it. I believe there's more repos/people using it. VS Code syntax coloring is very good, but I miss the flow comments syntax coloring. The current babel plugins for VS Code is unmaintained or even reduce syntax coloring in VS Code. So I believe there's will be traction or even better is to include it inside existing flow plugin for VS Code.

P.S. Thanks for this plugin, if nobody will take traction for flow syntax coloring in VS Code I think I will try to search through your source code to implement same thing in VS Code.

**Comment by mgmcdermott** [comment]
FYI: I have released a "Babel JavaScript" port [here](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) and plan on maintaining it!

Thanks again for all your hard work @gandm!

**Comment by gandm** [comment]
@mgmcdermott Good to know. I just downloaded it and it seems great.
