### ISSUE TITLE
arrow functions containing `<` or `<=` in body as non-first argument in function breaks syntax highlighting

### ISSUE THREAD

**Issue by transcranial** [gandm/language-babel#376]
![image](https://cloud.githubusercontent.com/assets/6182852/26690926/33e79e2a-46c9-11e7-9217-e5d776ee51e2.png)

Not sure what's going on here. Any ideas?

Edit: here is the same code with the language-javascript grammar, which is fine:

![image](https://cloud.githubusercontent.com/assets/6182852/26693105/04e705ea-46d1-11e7-9b22-a5fd331f7021.png)

**Comment by gandm** [comment]
I tested and it looks fine. See screenshot below.
Are you sure you are using my Grammar (Babel on the status bar)? What version of language-babel are you using? What theme is that?
![image](https://cloud.githubusercontent.com/assets/2313237/26691772/45029372-46f6-11e7-81c1-ce5458b38f08.png)

**Comment by gandm** [comment]
@transcranial Sorry I thought you were using comparisons not arrows ( should read the title!) I'll take a look.

**Comment by transcranial** [comment]
v2.65.0

The theme is oceanic next. I added a second screenshot of the same code with the language-javascript grammar, which is fine, above.

**Comment by gandm** [comment]
Yeah I made some changes in 2.64.0 that has caused this issue. You can roll back to 2.63.0 until I can fix. 

`apm install language-babel@2.63.0`

**Comment by gandm** [comment]
Should be fixed in 2.65.1

**Comment by transcranial** [comment]
@gandm looks good, thanks!
