### ISSUE TITLE
Incompatible Package Detected

### ISSUE THREAD

**Issue by xiahao90s** [gandm/language-babel#377]
language-babel has detected the presence of an incompatible Atom package named 'react'. 
 
It is recommended that you disable either 'react' or language-babel 
 
Reason:
 
The Atom community package 'react' (not to be confused 
with Facebook React) monkey patches the atom methods 
that provide autoindent features for JSX. 
As it detects JSX scopes without regard to the grammar being used, 
it tries to auto indent JSX that is highlighted by language-babel. 
As language-babel also attempts to do auto indentation using 
standard atom API's, this creates a potential conflict.

**Comment by gandm** [comment]
Yes then either remove the [react](https://atom.io/packages/react) pacakge or stop using `language-babel`

**Comment by xiahao90s** [comment]
How do I remove the react pacakge?

**Comment by gandm** [comment]
Go to the Atom settings via the menu or Win/Linux `Ctrl+,` or Mac `Cmd+`. Go to packages and then find `react` in the community packages list and click uninstall.
