### ISSUE TITLE
Incorrect syntax highlighting for arrow functions returning arrow functions.

### ISSUE THREAD

**Issue by conartist6** [gandm/language-babel#378]
I have the following block of code:

```
const setDefaultFilterValues = (
  defaultFilterValues?: TDefaultFilterValues,
): Function => (dispatch: Function, getState: Function): void => {
}
```

Here is how the syntax highlighting is showing it: http://imgur.com/a/HUFNU

There are actually two _function definitions_ here, the second definition being the body of the first. The highlighting only identifies the first definition, instead coloring the second definition as if it were instead a _function type definition_.

Perhaps this alteration of the code makes it a little more clear what's actually going on, however to my surprise it is still highlighted the same (incorrect) way.

```
const setDefaultFilterValues = (
  defaultFilterValues?: TDefaultFilterValues,
): Function => {
  return (dispatch: Function, getState: Function): void => {
  }
}
```

**Comment by gandm** [comment]
I've had a quick look and as far as I can see the second defintion is correct but the outer (first) definition isn't. However there is nothing I can do about the outer as I don't know it is an arrow function until I've parsed the paren body and TextMate grammars only allow me to process line at a time and I can't go backwards.

In this image I've slightly modified your code to show the different highlighting of a variable that holds a Function vs. a variable that holds some other object. Also, I've shown what it looks like on a single line. 
![image](https://user-images.githubusercontent.com/2313237/27003460-cf6897ce-4dee-11e7-85cc-e14c2684583d.png)

**Comment by conartist6** [comment]
Ah, I see. I'll have to think a bit ways we could work around this limitation.
