### ISSUE TITLE
detecting es6 classes and constants

### ISSUE THREAD

**Issue by deostroll** [gandm/language-babel#379]
Hi,

First off, I appreciate the good work. Not sure if my requirement is in scope of this package.

I was expecting if this package provided support for detecting es6 class definitions and constants in code. Usually we can hit CTRL+R and type the name of "the stuff" we want to find. (When working with JavaScript files of course). However, here I don't get the aforesaid two things...

Is this something that could be baked-in to the plugin? Or is there some other package that does this?

**Comment by gandm** [comment]
Sounds like you need something like [atom-ternjs](https://atom.io/packages/atom-ternjs) to create a ctags file or you could use [nuclide](https://nuclide.io/)
