### ISSUE TITLE
Upgrade to 0.10.5 causes 'Script: Run' (ctrl-shift-B) command (in the script package) to fail

### ISSUE THREAD

**Issue by MexieAndCo** [gandm/language-babel#38]
As soon as I reverted to 0.10.4, Script: Run worked properly again. No other changes were made (by me).

**Comment by gandm** [comment]
This is related to a change of script scope name in my grammar. I have raised an issue at Atom-script and hopefully it will be resolved. If not I will do a PR on it and see if it will be accepted. In the meantime you can change either my grammar  file or atom-script config file so they both have the same string. 






From: MexieAndCo
Sent: ‎Friday‎, ‎7‎ ‎August‎ ‎2015 ‎20‎:‎37
To: gandm/language-babel





As soon as I reverted to 0.10.4, Script: Run worked properly again. No other changes were made (by me).

**Comment by MexieAndCo** [comment]
Thanks. I made the change to the atom-script lib/grammars.coffee file and updated language-babel to 0.10.5. The Script: Run command is working again.
