### ISSUE TITLE
[HowTo] JSX styled components CSS highlighting

### ISSUE THREAD

**Issue by Jones-S** [gandm/language-babel#380]
Hi there

I know that your nice work already implemented part of my request: to have proper syntax highlighting. 

I am currently using styled components (actually [vue-styled-components](https://github.com/styled-components/vue-styled-components)) for a project and within style.js files the syntax highlighting works.

<img width="552" alt="screen shot 2017-06-12 at 14 07 11" src="https://user-images.githubusercontent.com/7059580/27033183-887d0ecc-4f78-11e7-9f89-a718e160d6a4.png">

But I am also writing sass-like mixins for mediaqueries.
By using the css function of styled components, the syntax highlighting works too (check image)
If I use it nested the highlighting does not work anymore though (all of the rules are green):

<img width="803" alt="screen shot 2017-06-12 at 13 45 26" src="https://user-images.githubusercontent.com/7059580/27033218-af13a640-4f78-11e7-8c29-b2fa2bcefc0a.png">

Any idea how to solve this problem?
Maybe with something from here:
https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions

I am not quite sure if I could use this, but I assume I could define, that
if a pattern like this `${media.medium` comes up, the code will be formatted like css as well.
Am I right?

I guess I would have to adapt this example
`"(?:css\.(?:[a-z])+)":source.css, /* @html */:text.html.basic, sql:source.sql`
But I don't really know how, and I also do not know how to put it into my .languagebabel config file. The atom settings are missing any section about _JavaScript Tagged Template Literal Grammar Extensions_

My guess would be
`"REGULAR EXPRESSION TO FIND PATTERN ${media.xyz":source.css`

Thanks for the help here.

EDIT: It was the first setting on the settings page. I'll keep trying

**Comment by Jones-S** [comment]
I thought entering something like this into the language-babel settings of atom:
`\${media\.([^\s]+):source.css`
Should actually work...?
The [regex tester](https://regex101.com/) the pattern above would match for example ```${media.handheld````

<img width="838" alt="screen shot 2017-06-12 at 15 04 49" src="https://user-images.githubusercontent.com/7059580/27035132-81b2a112-4f80-11e7-8e68-93132b239907.png">

But somehow I think I am missing something, because it does not work.
Also I would like to know how to set this setting within the projects `.languagebabel` config file only.

**Comment by gandm** [comment]
You just need a simple string match so no need to use a regex as such.
All you need is  `media.handheld:source.css.styled`

**Comment by gandm** [comment]
![image](https://user-images.githubusercontent.com/2313237/27036921-55ec34be-4f7e-11e7-8339-312894ef3315.png)

**Comment by Jones-S** [comment]
Thanks gandm,
I tried your suggestion, but somehow it still does not work like I want it to.
Do I have to define the end of a template literal somehow?

<img width="574" alt="screen shot 2017-06-12 at 16 04 35" src="https://user-images.githubusercontent.com/7059580/27037643-e4d7dd9a-4f88-11e7-87b7-6c49c713ecb8.png">
<img width="651" alt="screen shot 2017-06-12 at 16 05 11" src="https://user-images.githubusercontent.com/7059580/27037666-f1b9fbce-4f88-11e7-9a3a-a759d01b5d60.png">

Also: how would I use this in the .languagebabel config file?

**Comment by gandm** [comment]
It works for me.
![image](https://user-images.githubusercontent.com/2313237/27038790-e95cca2e-4f83-11e7-89bd-a701e782d19f.png)

It should have ceated a new grammar file `ttl-74ad33e45d1d9dc1ebdb2558ca9da40f71a4061f1f36d44caa995f6105273af2.json` inside my package. 
![image](https://user-images.githubusercontent.com/2313237/27038716-afa9b94a-4f83-11e7-90d6-89c2edafa710.png)

You can't use this inside a .languagebabel file. This is because grammars are global inside Atom and .languagebabel settings are project based. e.g. you couldn't have two projects open with different tagged template grammars referenced.

**Comment by Jones-S** [comment]
Thanks for your comment on the languagebabel file. I wanted to have everyone on the project automatically enjoying the syntax highlighting.

Anyway. 👍 for the working example at your side. But I still don't get your appearance.
Do I have to set another setting?
Or do I always have to restart atom (although this did not help)?
And which syntax setting do you use (in the bottom right corner)?
I use `Babel ES6 Javascript`.
Anything else you could think of? I double checked that the settings are right: 
`media.medium:source.css.styled`.

I also tried different syntaxes. But I think it really messes up with those backticks...

<img width="743" alt="screen shot 2017-06-12 at 17 01 44" src="https://user-images.githubusercontent.com/7059580/27040291-dd8409c6-4f90-11e7-9179-d6055273a413.png">

**Comment by gandm** [comment]
No it's just that setting. You shouldn't have to restart Atom to get this to work as it is dynamic.

Once you enter the tagged template grammar string into the config the system waits for 10 seconds to ensure that more changes are made to the string (Atom limitation) and then creates the grammar extension and loads it. You should see a notification as shown below.
![ttl](https://user-images.githubusercontent.com/2313237/27041492-0d3faf8a-4f8c-11e7-97d3-74020ff31d33.gif)

**Comment by Jones-S** [comment]
Oh I see... That blue box did never pop up. So I disabled and enabled the package and I got error messages:
<img width="494" alt="screen shot 2017-06-12 at 17 34 39" src="https://user-images.githubusercontent.com/7059580/27041859-8cf58494-4f95-11e7-8bb8-94430deec7f6.png">

```
Failed to activate the language-babel package
Maximum call stack size exceeded
Show Stack Trace
The error was thrown from the language-babel package. This issue has already been reported.
View Issue

```

```
Uncaught RangeError: Maximum call stack size exceeded
/Applications/Atom.app/Contents/Resources/app/node_modules/underscore/underscore.js:219
Show Stack Trace
This is likely a bug in Atom. This issue has already been reported.
```

I had some of them before, but did not realize that this probably intervened with the babel package. I don't really know how to solve this though. Hints are welcome. :)
But I'll keep trying

**Comment by gandm** [comment]
Could you uninstall language-babel, stop Atom, clear the `~/.atom/compile-cache` (it gets rebuilt at start), restart Atom and then re-install and see if that fixes it?

**Comment by Jones-S** [comment]
So fresh and so clean! 🎉 
![image](https://user-images.githubusercontent.com/7059580/27043819-b500d2c6-4f9b-11e7-9780-2138db84983b.png)

**Comment by gandm** [comment]
Glad it worked. Atom does get issues like this more often than it should!

**Comment by Jones-S** [comment]
It does indeed. I just had to redo everything. I tried to add a regex expression instead of media.medium. Because I have 5-6 breakpoints I am using, so I wanted
a regex to target all of this:
`media.small:source.css.styled, media.medium:source.css.styled, media.large:source.css.styled etc.`
So I got back to my regex, but atom crashed again because of the stack size thing...
So as a last question:
Would I use `"\${media\.([^\s]+)":source.css.styled` or something else? It keeps crashing when I enter this into my babel settings...

**Comment by gandm** [comment]
I have no idea why Atom is crashing the stack trace seems to be some form of recursion inside Atom when enabling the grammar! . I'm using Atom 1.18 Beta and it seems fine. 

If you want a catchall regex then `"media\.\w\w*":source.css.styled`

**Comment by Jones-S** [comment]
Thank you a lot @gandm 
Your help has been awesome. Hope it helps at least some other people trying to get the styled components highlights right.
I will try the regex soon. Right now atom seems to give me the blue update box anymore. I will have to repeat the cache clearing steps... 😢

**Comment by joaoreynolds** [comment]
I know this is closed. But since `media.{size}` seems to be a best practice and is suggested on the styled-components docs, would it be bad if `"media\.\w+":source.css.styled` was a default behavior? I just wonder how many users are adding this grammar extension anyway?
