### ISSUE TITLE
Targeting property of a `type` in Flow?

### ISSUE THREAD

**Issue by saadq** [gandm/language-babel#382]
Firstly, thanks for this great package.

I'm trying to change the syntax highlighting from the keys that have a type of function here:
<img width="249" alt="screen shot 2017-06-15 at 5 36 20 pm" src="https://user-images.githubusercontent.com/5678694/27202907-77384bf6-51f1-11e7-966e-eefcb18c7470.png">

EDIT: Here is the code in case you want to copy/paste it to try it out:

```js
type Props = {
  isOn: boolean,
  startTime?: number,
  stopTime?: number,
  startTimer: Function,
  stopTimer: Function,
  resetTimer: Function
}
```

I can do that by doing something like:

```less
.syntax--type.syntax--function.syntax--storage {
  color: white;
}
```

which yields:
<img width="262" alt="screen shot 2017-06-15 at 5 37 28 pm" src="https://user-images.githubusercontent.com/5678694/27202969-b7d8efe4-51f1-11e7-9180-b47107ec705a.png">

This is the result I'm looking for, however this also messes up the syntax highlighting for normal usage of the `function` keyword:
<img width="324" alt="screen shot 2017-06-15 at 5 37 37 pm" src="https://user-images.githubusercontent.com/5678694/27202984-c53ee7f6-51f1-11e7-941f-dea005c67d1c.png">

It doesn't look like there is any `flowtype` specific selector on the `type` example I posted above. Is this expected behavior?

**Comment by gandm** [comment]
No it doesn't. Maybe I should use a meta flowtype for object flowtype defs. Would that do the trick?

**Comment by saadq** [comment]
Thanks for the quick reply. I believe that should work.

**Comment by gandm** [comment]
OK leave it with me.

**Comment by gandm** [comment]
@saadq Can you try the latest master version in this git repo? If it does the trick I will publish.

**Comment by saadq** [comment]
<img width="252" alt="screen shot 2017-06-16 at 5 04 38 am" src="https://user-images.githubusercontent.com/5678694/27219922-535e2dc6-5251-11e7-81e2-11a560982ed0.png">

Everything looking good! Thanks very much.

**Comment by gandm** [comment]
published
