### ISSUE TITLE
styled-components with inline component doesn't fit supported sytnax

### ISSUE THREAD

**Issue by pkrawc** [gandm/language-babel#386]
Hey there,

I was looking for a way to consolidate some of the components that we write for our UI library, and realized I could just inline the component in the `styled`  call. Anyway, that works as expected but the styling syntax is dropped. Is there a recommendation to get around this or is it just to build a custom rc file?

Below is an example of a react component that loses the syntax

```javascript
const Random = styled((props) => (
  <div className={props.className}>
    <div className="inner"></div>
    <div className="inner"></div>
  </div>
))`
  padding: 1em;
  background: red;
  .inner {
    margin: 1em;
    background: blue;
    height: 200px;
  }
`
```

**Comment by gandm** [comment]
Not much one can do about this. The best I can suggest is use a comment prefix to the template.
```js
const Random = styled((props) => (
  <div className={props.className}>
    <div className="inner"></div>
    <div className="inner"></div>
  </div>
))/*sc*/`
  padding: 1em;
  background: red;
  .inner {
    margin: 1em;
    background: blue;
    height: 200px;
  }
`
````
and then use a [tagged template extension](https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions) to do this.

e.g.
add `/*sc*/:source.css.styled` to the package setttings.

**Comment by pkrawc** [comment]
Thanks for the response. I'll use the tagged template extension for now then.
