### ISSUE TITLE
Bad function bind operator colouring

### ISSUE THREAD

**Issue by robertrossmann** [gandm/language-babel#389]
Hello!

It looks like the function bind operator (`::`) is incorrectly syntax-highlighted when between the receiver and the function; the columns have different colouring. See the screenshot.

![bad-double-colon-colouring](https://user-images.githubusercontent.com/3058150/28272741-addd5a1e-6b0c-11e7-87d3-a366e653f2d3.png)

On the other hand, it appears to work when the operator is part of an assignment:

![bind-operator-assignment](https://user-images.githubusercontent.com/3058150/28272934-38ff95a8-6b0d-11e7-9e42-b0aa16f0a4fe.png)

**Comment by robertrossmann** [comment]
Another problem with the function bind operator colouring I have noticed - the colouring of `this` and the bind operator `::` changes in this particular situation when a semicolon is inserted to the preceding expression:

**Without semicolon:**
![colouring-without-semi](https://user-images.githubusercontent.com/3058150/28309916-20e5a928-6bab-11e7-8159-071be2b1f9ab.png)

**With semicolon:**
![colouring-with-semi](https://user-images.githubusercontent.com/3058150/28309937-2db9440c-6bab-11e7-8fce-31a6b9ce3436.png)

**Comment by gandm** [comment]
thanks. I'll try to fix this before the weekend.

**Comment by gandm** [comment]
Please try 2.67.1

**Comment by robertrossmann** [comment]
Works perfectly! Thank you for taking the time to fix this! ❤️
