### ISSUE TITLE
Followup on #389: bind operator still sometimes appears incorrectly

### ISSUE THREAD

**Issue by robertrossmann** [gandm/language-babel#390]
Hello! This is a follow-up on a previous issue #389. I closed the ticket as I saw the bind operator appear correctly in most places - however, today I stumbled upon another situation where the bind operator still appears incorrectly. Screenshots follow.

![bind-operator-wrong](https://user-images.githubusercontent.com/3058150/28459045-33ff4722-6e0c-11e7-8a0c-422a7d3506e4.png)

Inserting a semicolon after the first line fixes the highlight:

![bind-operator-fixed](https://user-images.githubusercontent.com/3058150/28459049-387ae8ce-6e0c-11e7-9ba7-b6a3e9bd3eb6.png)

Thanks for looking into this!

**Comment by gandm** [comment]
Fixed in 2.67.2 Shame this is still a Stage 0 proposal. Wish they used another character pair -  colons appear everywhere in JS!

**Comment by robertrossmann** [comment]
Heh, yeah! Thanks, I scanned my codez and the bind operator looks awesome everywhere now! 🍻
