### ISSUE TITLE
Autoformat breaks code for comments

### ISSUE THREAD

**Issue by derwaldgeist** [gandm/language-babel#391]
I am using `language-babel` in combination with `atom-beautify`.

In adapter.js, there is the following lines:
```
  // add promise support
  ['createOffer', 'createAnswer'].forEach(function(method) {
  ...
```

If I enable `language-babel`, this is auto-beautified on save to:

```
  // add promise support['createOffer', 'createAnswer'].forEach(function(method) {
  ...
```

effectively breaking the code.

**Comment by gandm** [comment]
You should raise this issue at the beautify repo as I don't forget code.
________________________________

**Comment by derwaldgeist** [comment]
So you think it's not related to the babel package? Strange thing is: it works if I disable this package.

**Comment by gandm** [comment]
Yes I think it is the beautifier.  The actual beautifier used depends on the scope of the grammar used.  My scope is source.js.jsx therefore a jsx beutifuer is used. If you use the atom JavaScript grammar it uses source..js and maybe another beautifier.
________________________________

**Comment by gandm** [comment]
From the atom-beautify readme that shows the default beautifiers used..
![image](https://user-images.githubusercontent.com/2313237/28754600-60aacbd0-7540-11e7-8d5d-52a7fc302295.png)

**Comment by derwaldgeist** [comment]
Ok, thanks, I filed an issue there.
