### ISSUE TITLE
Template string highlighting issue in object literals

### ISSUE THREAD

**Issue by ooflorent** [gandm/language-babel#393]
The syntax highlighting of the `template` key of an object literal seems to be broken if the value is a template string when the object if encapsulated by parens.

<img width="367" alt="template" src="https://user-images.githubusercontent.com/168498/28824940-a2199db4-76c4-11e7-9d28-e9da5d53b8fe.png">

**Comment by ooflorent** [comment]
Actually it is an extract of a webpack config. I've reduced it to the bare minimum to hightligh the issue. I'll post the full gist in an hour.

**Comment by ooflorent** [comment]
Here are two more (valid) examples:

```js
bar = {
  pre_template: `foo`,
  template: `foo`,
  post_template: `foo`,
}

foo({
  pre_template: `foo`,
  template: `foo`,
  post_template: `foo`,
})
```

![atom_babel](https://user-images.githubusercontent.com/168498/28841146-89915d9c-76f9-11e7-8d57-57d5939ec5d6.png)

The word `template` seems to be the issue.

**Comment by gandm** [comment]
As I mentioned, this is expected as I use a object property of template as a signal that any template literal following is Angular/Vue HTML. This is hardcoded in the grammar. 

![image](https://user-images.githubusercontent.com/2313237/28843740-2ea833c8-76fa-11e7-8772-78c0bdc3b6eb.png)

**Comment by ooflorent** [comment]
Alright! I missed that.
