### ISSUE TITLE
Opaque type syntax highlighting

### ISSUE THREAD

**Issue by ooflorent** [gandm/language-babel#395]
Flow's [opaque types](https://flow.org/en/docs/types/opaque-types/) are not properly highlighted. I think the `opaque` keyword should also be considered a keyword! Moreover, there is an issue with semicolon-less code.

![opaque](https://user-images.githubusercontent.com/168498/29042519-7c25ffec-7bb7-11e7-936a-f6d291811e0b.png)

**Comment by gandm** [comment]
2.69.0 supports opaque.

**Comment by ooflorent** [comment]
Damn, my editor hasn't updated yet. Sorry for the inconvenience!
Thank you for your work!
