### ISSUE TITLE
Support ligatures for the pipeline operator

### ISSUE THREAD

**Issue by k15a** [gandm/language-babel#397]
There is a proposal for the [pipeline operator](https://github.com/tc39/proposal-pipeline-operator) for JavaScript. Currently this is highlighted as bitwise operator followed by a comparison operator.

![screen shot 2017-08-10 at 11 22 40](https://user-images.githubusercontent.com/20357450/29164027-7b29474e-7dbe-11e7-9182-952e21d378f5.jpg)

Unfortunately, this [disables ligatures for the pipeline operator](https://jsbin.com/bulebohapa/edit?html,css,output) because Blink doesn't render it.

![screen shot 2017-08-10 at 11 28 38](https://user-images.githubusercontent.com/20357450/29164240-1699206e-7dbf-11e7-90f6-1894f72dc63f.jpg)

It would be great if you could support the pipeline operator as a separate operator.

**Comment by gandm** [comment]
Yes I was thinking of adding this but last I looked it seemed to be having some problem getting to stage 0 of TC39. Seems as though it might have a couple of champions now, so it's promising. I also need to add #private class fields so I may try to do this at the same time.

**Comment by k15a** [comment]
Yeah, as far as I know Kent C Dodds is the champion of this proposal now.

**Comment by gandm** [comment]
@k15a Please try 2.70.0

**Comment by k15a** [comment]
Awesome thanks 🎉
