### ISSUE TITLE
"No symbols found" in .jsx files

### ISSUE THREAD

**Issue by rgrove** [gandm/language-babel#4]
When editing a `.jsx` file, the symbols view (Cmd-R) is empty and displays the message "No symbols found". If I rename the same file to `.js`, the symbols view displays all the symbols I would expect it to. I've tried a variety of files, and it doesn't seem to be related to the contents at all; just the extension.

(Other than this minor issue, I'm really loving this syntax! Thanks for putting it together.)

**Comment by gandm** [comment]
I will change the grammar to scope to .jsx. This should allow the builtin Atom symbols for JavaScript to work. The symbols regex provided with Atom needs to be updated to see ES6 structures so it may be of limited use!

**Comment by rgrove** [comment]
Hmm. This fixed the symbols view, but broke the linter-eslint package, which will only run ESLint on `source.js`, `source.js.jsx`, or `source.babel`.

**Comment by gandm** [comment]
OK I've just looked at the source for linter-eslint. Yes It seems they changed it to accommodate source.babel - very kind of them. But they don't support .jsx which is one of the options the Atom symbols package supports. I'll modify my code to change the scopeName to .js.jsx. That should make everyone happy unless someone else is using source.babel!!!!

**Comment by gandm** [comment]
@rgrove. Just changed the scopeName to .js.jsx. This is supported by linter so can you check this and the symbols still work.

**Comment by rgrove** [comment]
Thanks! Works great now.
