### ISSUE TITLE
Infinity keyword coloring

### ISSUE THREAD

**Issue by ooflorent** [gandm/language-babel#401]
Is there any reason that `Infinity` is no longer _yellow_ when prefixed by `-` or `+`? Also the prefix isn't _white_. Note: it works as expected with `NaN`.

![infinity](https://user-images.githubusercontent.com/168498/29426808-1efabf8c-8388-11e7-9bcb-155d9a877822.png)

![nan](https://user-images.githubusercontent.com/168498/29426941-728ae870-8388-11e7-90de-aecdb3c5489f.png)

**Comment by gandm** [comment]
It was being detected by an old regex that should have been removed.

**Comment by gandm** [comment]
Thanks
