### ISSUE TITLE
Function identifiers not colored properly when args on multiple lines

### ISSUE THREAD

**Issue by ooflorent** [gandm/language-babel#402]
Arrow function identifiers are not properly highlighted when the arguments are defined on multiple lines.

<img width="188" alt="multiline_arrow" src="https://user-images.githubusercontent.com/168498/29448884-dc5bb9d0-83f8-11e7-9f68-34b758aeecd4.png">

Real world example:
```js
export const createCanvas = (
  width: number,
  height: number,
  pixelRatio: number
): HTMLCanvasElement => {
  const canvas = document.createElement("canvas")
  canvas.width = width * pixelRatio
  canvas.height = height * pixelRatio
  canvas.style.width = width + "px"
  canvas.style.height = height + "px"
  return canvas
}
```

**Comment by gandm** [comment]
Yes it should be but it is impossible to do. It's a limitation of TextMate Grammars that they are only allowed to look at a single line and may not look forwards nor go backwards. I don't know it's an arrow function until the function name has passed. Sorry.

**Comment by ooflorent** [comment]
That's too bad 😞
