### ISSUE TITLE
Support Ligatures for Optional Chaining

### ISSUE THREAD

**Issue by k15a** [gandm/language-babel#407]
Hey,

thank you very much for the plugin! 🎉

The optional chaining syntax is at stage-1 right now and will soon land in Babel so it would be great to support ligatures for it as well. I think the problem currently is the same as https://github.com/gandm/language-babel/issues/397.

![screen shot 2017-08-28 at 21 02 28](https://user-images.githubusercontent.com/20357450/29788818-3cd6a516-8c34-11e7-81da-10e4e63ac70e.jpg)

![screen shot 2017-08-28 at 21 01 48](https://user-images.githubusercontent.com/20357450/29788787-2307fe32-8c34-11e7-8fa5-4e6c76fd1845.jpg)

It's not that much of a deal because the ligatures aren't very different but it would be great to have though.

**Comment by gandm** [comment]
The ligature seems almost the same as two sep chars but I've made the change anyway.
