### ISSUE TITLE
HTML highligting

### ISSUE THREAD

**Issue by ooflorent** [gandm/language-babel#410]
Frameworks like `choo` uses `html` tag template function to define DOM. It would be awesome if this plugin would trigger syntax coloring just like `css`.

```js
function mainView (state, emit) {
  return html`
    <body>
      <h1>count is ${state.count}</h1>
      <button onclick=${onclick}>Increment</button>
    </body>
  `
}
```

**Note:** GitHub does the highlighting of `html`

**Comment by gandm** [comment]
You could use https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions

**Comment by ooflorent** [comment]
I'm sorry, I don't understand the link section. I can't see what to do the enable HTML highlighting. Could you further elaborate the point?

> As language-babel passes off highlighting of the template to another grammar, it cannot highlight any interpolated code.

That's too bad. `choo`, `bel` and `yo-yo` are widely spread and the requested feature would vastly improve the DX of working on these frameworks.

**Comment by gandm** [comment]
![image](https://user-images.githubusercontent.com/2313237/30160945-9e55286e-93c6-11e7-9654-aa13a71e7104.png)
gives
![image](https://user-images.githubusercontent.com/2313237/30160968-b0006344-93c6-11e7-88ef-1d81893acc0c.png)

**Comment by ooflorent** [comment]
Thanks! I still hope this functionality will be implemented. Feel free to close this issue if not 😉

**Comment by gandm** [comment]
Github which uses Atom's language-javascript uses exactly the same technique to highlight html as the above config setting employs. 
See https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L1378-L1401 and compare with the generated code used by the above config setting and you will see it is similar. 
```json
{
  "name": "language-babel-extension",
  "comment": "Auto generated Tag Extensions for language-babel",
  "comment": "Please do not edit this file directly",
  "scopeName": "languagebabel.ttlextension",
  "fileTypes": [],
  "patterns": [
    {
      "contentName": "text.html.basic",
      "begin": "\\s*+(html)\\s*(`)",
      "beginCaptures": {
        "1": { "name": "entity.name.tag.js" },
        "2": { "name": "punctuation.definition.quasi.begin.js" }
      },
      "end": "\\s*(?<=[^\\\\]\\\\\\\\|[^\\\\]|^\\\\\\\\|^)((`))",
      "endCaptures": {
        "1": { "name": "punctuation.definition.quasi.end.js" }
      },
      "patterns": [
        { "include": "source.js.jsx#literal-quasi-embedded" },
        { "include": "text.html.basic" }
      ]
    }
  ]
}
```
The benefit of using a configuration setting is that the user can decide what grammar to use for highlighting - e.g. handlebars, mustache, angular,.....etc.
