### ISSUE TITLE
Issue with syntax highlighting components that take functions as props.

### ISSUE THREAD

**Issue by jackfranklin** [gandm/language-babel#412]
Firstly, thank you so much for your work on this plugin. It's made working in Atom an absolute dream!

I've just come across what I think might be a very edge case syntax highlighting issue. It occurs when you have a component that you're passing in a function as a prop, and that function is an arrow function that returns another JSX element via an implicit return.

It's hard to describe, so I took screenshots! Here's the broken version - note that the `children` prop is an arrow function with an implicit return, and note that the syntax highlighting is off.

<img width="544" alt="screen shot 2017-09-13 at 18 22 45" src="https://user-images.githubusercontent.com/193238/30391328-dd76f0c4-98b0-11e7-99bb-70119bb5bab5.png">

Here's a version where the arrow function is an explicitly returning one - it has a body wrapped in braces, and you can see the syntax highlighting is working correctly:

<img width="533" alt="screen shot 2017-09-13 at 18 22 31" src="https://user-images.githubusercontent.com/193238/30391349-f0c097a2-98b0-11e7-90e5-beab8ebe421b.png">

Additionally, if I take the broken first example and put the `children` prop onto its own line, that fixes the highlighting too:

<img width="535" alt="screen shot 2017-09-13 at 18 25 45" src="https://user-images.githubusercontent.com/193238/30391382-0b6ee28e-98b1-11e7-9357-ffc29b02819b.png">

It's a very edge case and easily avoided, but thought I'd raise the issue :)

**Comment by gandm** [comment]
Thanks for the report and kind words.

**Comment by jackfranklin** [comment]
Thank you so much for such a quick response!
