### ISSUE TITLE
Styled-components syntax highlighting is broken

### ISSUE THREAD

**Issue by krabbypattified** [gandm/language-babel#413]
Why Does my syntax highlighting look like this? I just updated language-babel to version 2.74.2 and I'm in Babel ES6 JavaScript mode. My JSX renders fine.
![screen shot 2017-09-17 at 7 57 23 pm](https://user-images.githubusercontent.com/13423815/30526099-9e0b9e8c-9be2-11e7-83a1-dbf8f92d6a54.png)

**Comment by gandm** [comment]
I can't explain this as it works for me. I would suggest uninstalling `language-babel` and then stopping it and removing the `~/atom/compile-cache`,  re-install using  `apm install language-babel` and then restarting atom.

**Comment by ghengeveld** [comment]
Re-installing `language-babel` fixed it for me. Also make sure you have no conflicting plugins (e.g. `language-javascript-jsx`).

**Comment by gandm** [comment]
Pretty sure this is an Atom system/package update problem. I'll close this. Please post back here if you cannot solve this issue.

**Comment by krabbypattified** [comment]
Confirming that this solved my issue. Thanks @gandm !
![screen shot 2017-09-30 at 11 20 36 am](https://user-images.githubusercontent.com/13423815/31047040-6af9c976-a5d1-11e7-8ac9-5bc494db17e7.png)
