### ISSUE TITLE
styled-components syntax highlighting breaks when calling attrs functions on components

### ISSUE THREAD

**Issue by jjant** [gandm/language-babel#416]
The following code:

```javascript
const RoleCheckbox = styled.input.attrs({ type: 'checkbox' })`
  appearance: none;
  background-color: #ffffff;
  background-position: center center;
  background-repeat: no-repeat;
  border-color: #babbc1;
  cursor: pointer;
`;
```

Doesn't get correctly highlighted (string looks green, as a regular JS string), while removing the `.attrs(...)` call makes the syntax highlight work correctly.

With `.attrs(...)` call: https://puu.sh/xFmZv/2e9fba17b4.png
Without `.attrs(...)` call: https://puu.sh/xFn14/2b7570f739.png

**Comment by gandm** [comment]
Seems OK for me 
![image](https://user-images.githubusercontent.com/2313237/30710681-3dcca966-9efe-11e7-8282-913afd40726c.png)

**Comment by jjant** [comment]
@gandm That's really _really_ weird. I wonder why it doesn't work for me.

**Comment by gandm** [comment]
I've had reports before where people have some curious issues, normally associated with a recent update.  I would suggest uninstalling `language-babel`, stopping atom, removing the `~/atom/compile-cache`, re-install using `apm install language-babel` and then restarting atom. Obviously, ensure that Babel is showing on the bottoms status bar.

**Comment by gandm** [comment]
Pretty sure this is an Atom system/package update problem. I'll close this. Please post back here if you cannot solve this issue.
