### ISSUE TITLE
Incorrect highlight on await in object rest spread operator

### ISSUE THREAD

**Issue by robertrossmann** [gandm/language-babel#417]
Hello,

In the following code snippet, the `await` keyword is treated as object property instead of a keyword, resulting in the keyword to have colour like object properties. 😱

```js
class Boilerplate extends Generator {
  async prompting() {
    this.options = {
      ...this.options,
      ...await this.prompt({ // <--
        type: 'input',
        name: 'extension',
        default: '.es',
        message: 'File extension to use for project files:',
      }),
    }
  }
}
```

Obligatory screenshot:

![babel rest spread with await](https://user-images.githubusercontent.com/3058150/30770563-7152428c-a034-11e7-8d19-b53ab7da0cb4.png)

Thank you for your help!

**Comment by gandm** [comment]
fixed in 2.74.3
