### ISSUE TITLE
Unwanted "class" attribute on autocomplete

### ISSUE THREAD

**Issue by Igor10k** [gandm/language-babel#418]
Is there a reason why `language-babel` suggests `class` as an attribute? React doesn't allow that.

<img width="253" alt="screen shot 2017-09-25 at 15 57 18" src="https://user-images.githubusercontent.com/1244342/30809395-41f7b36e-a20a-11e7-8e26-8b38a7137fcc.png">

**Comment by gandm** [comment]
Preact uses class in preference to className.

**Comment by Igor10k** [comment]
I see. I just find it very annoying having to press `down` every time I want to add a `className` attribute. It seems I'll just have to find a way to make `className` take the first row somehow. Thanks for the answer.

**Comment by gandm** [comment]
@Igor10k Yes I can see that. Just typing cln brings up the classname complete which isn't too bad?

**Comment by Igor10k** [comment]
@gandm now why didn't I think of it :D Yeah, that works, thanks!
