### ISSUE TITLE
No syntax highlighting inside styled-components media template

### ISSUE THREAD

**Issue by ghengeveld** [gandm/language-babel#419]
![schermafbeelding 2017-09-25 om 17 03 17](https://user-images.githubusercontent.com/321738/30815437-8145cbec-a213-11e7-881d-c8bd67d879cc.png)
Syntax highlighting inside the `phoneOnly` block is missing.

`media.phoneOnly` is defined as follows:
```js
import { css } from "styled-components";

export const media = {
  phoneOnly: (...args) => css`
    @media (max-width: 767px) {
      ${css(...args)};
    }
  `,
  // ...
}
```

Here's the docs on media templates: https://www.styled-components.com/docs/advanced#media-templates

**Comment by gandm** [comment]
It's not a styled-component API just best practice. See workaround here https://github.com/gandm/language-babel/issues/380#issuecomment-307794998 and modify for your use case.

**Comment by ghengeveld** [comment]
Great. I added `"media\.\w+":source.css.styled` to the grammar extensions.

Thanks a lot for your help, you are awesome ❤️
