### ISSUE TITLE
Option to disable Auto Completion of JSX tags, elements and attributes

### ISSUE THREAD

**Issue by aHxShUM** [gandm/language-babel#420]
Is there any option/config which can disable the auto completion?

**Comment by gandm** [comment]
No I'm afraid not. Any reason you want to disable this?

**Comment by aHxShUM** [comment]
Just for personal preference, I prefer using hotkey to auto-close tag (like `ALT+.` in Sublime), as which is much general for editing other languages with XML format. So most of the times when I am going to a newline, a close tag is inserted instead and this just made me difficult to get used to it.

**Comment by gandm** [comment]
Oh I see. You can disable this via a setting in the autocomplete-plus package provided with Atom. I'm not sure if this is what you want as it will also disable all auto-completions inside a JSX block including JavaScript.
![image](https://user-images.githubusercontent.com/2313237/30950637-199c0dda-a416-11e7-9706-938e45495fbf.png)

![image](https://user-images.githubusercontent.com/2313237/30950607-ec532818-a415-11e7-921f-225e53ab4cc4.png)

**Comment by gandm** [comment]
Also in the same package thi setting may be useful
![image](https://user-images.githubusercontent.com/2313237/30950758-d62531e8-a416-11e7-8eb0-089d92b3bd7a.png)
