### ISSUE TITLE
React.js ES6 highlight issue

### ISSUE THREAD

**Issue by nakeeon** [gandm/language-babel#421]
Hello!
Thanks for your cool plugin for atom. Although, I have one issue with React.js highlighting.

![861ff49c5c](https://user-images.githubusercontent.com/17749002/30971026-8140f80c-a46f-11e7-8045-c9cfa539a2ab.jpg)

I found that this piece of code causes the issue:

![5f0d439178](https://user-images.githubusercontent.com/17749002/30971135-c8f98042-a46f-11e7-9488-1f4deeb0c085.jpg)

When I deleted the return a function, it become okay:

![ba80f8a39c](https://user-images.githubusercontent.com/17749002/30971305-30c63f62-a470-11e7-9e92-e98616a4ace6.jpg)

**Comment by gandm** [comment]
Should be fixed in 2.74.4
