### ISSUE TITLE
Different coloring of undeclared variables

### ISSUE THREAD

**Issue by Martinsos** [gandm/language-babel#422]
Hi,
first of all thank you for this great package!

I recently switched from Emacs to Atom for the purpose of working on React project, since Atom has better support regarding the available packages for React (language-babel).

One thing I find missing in language-babel and really love it in Emacs is that symbols that have been declared before are colored differently than those that were not. This helps a lot while coding, because it makes you aware that you just declared a new variable are not assigning to existing variable -> it saved me from typos many times.

Here is a screenshot of how js2-mode from emacs does it:
![emacscoloring](https://user-images.githubusercontent.com/1536647/31022765-b28d0ef6-a531-11e7-9e09-696530368949.png)

1. In first line, declaration of apple it colored because it was not declared before (obviously :))
2. In second line, apple is already declared so no coloring.
3. In third line, orange is colored since it is declared for the first time, but pear is also colored because it was never declared (which is nice, because it warns me I might be using unexisting variable).
4. In forth line it recognizes window as global object so it does not color it.
5. In fifth line I made a typo, and again the coloring warns me of that.

The thing is, js2-mode in emacs actually implements its own javascript interpreter (in elisp) so I am guessing that is what supports this feature. I don't know how language-babel works -> is it possible to implement similar feature in it, is there needed support for smt like this? I could try to do a PR if you would be kind of enough to give me some directions.

**Comment by gandm** [comment]
I'm afraid this isn't possible using the current TextMate grammars that Atom currently uses ( as does Sublime, Vscode etc). 

The Atom team are working on a new incremental grammar parser that would allow this type of functionality but I have no timeframe for this to be released.

You may want to look at the new Atom IDE user interface as this would allow an outline view of variables in a side panel. See [the IDE with this package providing highlighting](https://ide.atom.io/) In addition to the [IDE UI](https://atom.io/packages/atom-ide-ui) would need to add either the IDE-Flowtype or IDE-TypeScript package. Both provide support for JavaScript but also provide support for optional typed JavaScript ( Facebook's Flow or Microsoft's TypeScript).

**Comment by Martinsos** [comment]
Awesome, thank you! I will check out the resources, I didn't know about the Atom IDE, seems great.

By the way, I did find this package https://atom.io/packages/language-javascript-semantic that does not solve this problem diirectly, but it does use [Acorn](https://github.com/ternjs/acorn) to actually parse the javascript, which could provide support needed for this feature, correct? Acorn comes with support for [plugins](https://github.com/ternjs/acorn#existing-plugins) so it can also support stuff that is not yet in standard. Would Acorn be a possible solution for "smarter" syntax highlighting? Or it does not make sense to fiddle with it since Atom IDE is here now?

**Comment by gandm** [comment]
Yes your right that it is programmatically possible but I'd wait. The Atom Github team are planning to release an incremental AST parser named [tree-sitter](https://github.com/tree-sitter) together with numerous language plugins that solves the problems of traditional AST parsers (such as Acorn). Firstly, they don't' work well when encountering an error in the code  and secondly, they have to reparse the whole file which makes it impractical when changing the file continuously as in an editor.

**Comment by Martinsos** [comment]
Sounds great -> having smart editor for all those languages, I am looking forward to it. Actually, Acorn does have [error-tollerant parser](https://github.com/ternjs/acorn#distacorn_loosejs), but it does not have ability to incrementally parse the file (at least not on first glance).
Thanks again for the effort! All the best.
