### ISSUE TITLE
styled-components support breaks highlighting

### ISSUE THREAD

**Issue by ooflorent** [gandm/language-babel#424]
When using SC without tagged template string, the syntax coloring is broken.

<img width="233" alt="sc" src="https://user-images.githubusercontent.com/168498/31127454-4446d442-a84f-11e7-8394-4daa0ee22947.png">

**Comment by gandm** [comment]
I have fixed this in my local grammar but I don't think the above syntax is sound. I believe it should be terminated with an empty template string. I'm not using styled-components but I did a quick experiment and seemed to get strange results without a null string. Also see https://github.com/styled-components/styled-components/issues/1124#issuecomment-325595208

**Comment by ooflorent** [comment]
Many thanks. While the pattern is not commonly used, [it is documented](https://www.styled-components.com/docs/advanced#tagged-template-literals) and [used in libraries](https://github.com/jxnblk/rebass/blob/e5a17b9cf5839d18aaaa7f0b1ae2b033f245a8b8/src/hoc.js#L62-L64).

**Comment by gandm** [comment]
Still don't think it's correct just because it is equivalent. The example in the library is OK because of line 64, so the function chain isn't broken. Anyway, it should work for you now.
