### ISSUE TITLE
Add support for handlebars: hbs

### ISSUE THREAD

**Issue by NullVoxPopuli** [gandm/language-babel#426]
in ember projects, there is a way to do inline-templating via the `hbs` template string method.

example:
```js
import Component from '@ember/component';

export default class MyComponent extends Component {
  static layout = hbs`
    {{#navigation as |nav|}}
      {{nav.link to='some.path'}}
      {{nav.link to='://google.com'}}
    {{/navigation}}
  `;
}
```

Is this something that can be thrown into this package? I see that the `gql\`\`` template string is already supported :-)

the hbs template string is also used in integration tests for components as well,
for example:

```js
test('can be told to render initially', withChai(function(expect) {
  this.set('errors', [{ code: 401 }]);

  this.render(hbs`{{error-header errors=errors hidden=false}}`);

  expect(this.$().text()).to.include(NOT_AUTHORIZED);
}));
```

**Comment by gandm** [comment]
You should be able to do this via this via one of my package settings. See [here](https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions) for more information.

e.g. 

`hbs:text.html.mustache` will use the language-mustache package to highlight your templates.

**Comment by NullVoxPopuli** [comment]
it works!
![2017-10-04-151958_606x160_scrot](https://user-images.githubusercontent.com/199018/31195201-822a2d9a-a917-11e7-8629-05b9ab0c9479.png)

thanks!
for future people I did this (in case you can't find stuff):
![2017-10-04-152036_963x717_scrot](https://user-images.githubusercontent.com/199018/31195232-95798076-a917-11e7-9202-b331129b5044.png)
(using the package atom-handlebars)
