### ISSUE TITLE
Object literal fat arrow with argument parens causes syntax highlighting error in jsx

### ISSUE THREAD

**Issue by astephenb** [gandm/language-babel#43]
Using the fat arrow syntax with argument parens in an object is causing weird syntax highlighting for the remainder of a jsx file.
![with parens](https://cloud.githubusercontent.com/assets/3619060/9202749/3a149a74-4008-11e5-9aaa-7b9443a774af.png)

However, omitting the parens, or using the function shorthand syntax works fine.
![without parens](https://cloud.githubusercontent.com/assets/3619060/9202747/3a1052f2-4008-11e5-987c-8a5d96cf3e2c.png)
![shorthand](https://cloud.githubusercontent.com/assets/3619060/9202748/3a109ef6-4008-11e5-8fb3-a51d13c4ba07.png)

**Comment by gandm** [comment]
I can see what is happening. Neither of the first two are working, but the second is less offensive. In the first two, because the grammar doesn't expect a literal named fat arrow in an expression the 
```
 getAttribute: (name) => { 
```
is being interpreted a flow type of a function named getAttribute returning some form of callback. 

I'll look into this.

**Comment by gandm** [comment]
I've just committed a change to the master branch that should fix this but may have other issues. It is not published to atom. Any chance you can check this out by downloading the new grammar files  and replacing the current ones and reloading atom?

**Comment by gandm** [comment]
>is being interpreted a flow type of a function named getAttribute returning some form of call back

I should have said - is being interpreted as an argument named getAttribute being passed to a function that returns some form function. Or in the second case returning a value of type name.

**Comment by astephenb** [comment]
I'll give it a shot.

**Comment by astephenb** [comment]
It works! Thanks.

**Comment by gandm** [comment]
Thanks for your help. I'll publish this once I've done some more checks.
