### ISSUE TITLE
Many Auto Complete Snippets

### ISSUE THREAD

**Issue by ButSeriously** [gandm/language-babel#430]
I have very annoying bug in my Atom - there are many of the same snippets in the Auto Complete function. This is happening only for HTML attributes.
![2](https://user-images.githubusercontent.com/23147514/31585989-275068c8-b1cb-11e7-8dff-6481e16c1104.png)

I was trying to disable all others packages, but that dosen't fixed anything.

Do you have some ideas about that?

**Comment by gandm** [comment]
Not really. What version of atom and language-babel?

**Comment by ButSeriously** [comment]
Atom 1.21.1 x64
language-babel 2.75.1

**Comment by ButSeriously** [comment]
I've found where was the problem - in the autocomplete-plus core package. I have to set Similar Suggestion Removal
![obraz](https://user-images.githubusercontent.com/23147514/31587060-eb4bf62a-b1da-11e7-8d19-5ad4eec82927.png)

**Comment by gandm** [comment]
Actually there was an issue that should be fixed in 2.75.2
