### ISSUE TITLE
Incorrect highlighting of nested JSX elements

### ISSUE THREAD

**Issue by xenobarbital** [gandm/language-babel#436]
I'm getting strange behavior in the editor with nested JSX elements. When self-closing component (`<Scene/>` in my case) is written without a space before slash, the highlighting of opening and closing tags for the parent is OK, but when you add a space (`<Scene />`) the result is not good.
![right](https://user-images.githubusercontent.com/15430055/32157665-52839f3a-bd5e-11e7-8917-e5e16cc8ef40.png)
![wrong](https://user-images.githubusercontent.com/15430055/32157667-59c4b702-bd5e-11e7-9a22-40a930e59ab1.png)

**Comment by gandm** [comment]
Atom's [bracket matcher](https://github.com/atom/bracket-matcher)  highlights matching tags not this package.
