### ISSUE TITLE
export default async nor parsed correctly

### ISSUE THREAD

**Issue by bradennapier** [gandm/language-babel#438]
Identical to the one you fixed earlier but when using export 

![image](https://user-images.githubusercontent.com/15365418/32197943-67555866-bd83-11e7-8c78-d2d3f603ffc1.png)

**Comment by gandm** [comment]
@bradennapier This is tricky to fix as I can't read ahead! async is not a protected word so `export default async (` could be part of the following code:-
```js
export default async (
);
```
i.e. export a function named async which is valid JS. 

I guess I might treat the space between the `async` and `(` as relevant and assume an arrow function in this case. I'll chew this over.

Also, I'd appreciate it if this issue and your others had a title that more clearly described the error as it makes it hard to review.

**Comment by bradennapier** [comment]
no problem ! will do!

**Comment by gandm** [comment]
Fixed in 2.76.4
