### ISSUE TITLE
[Flow] declare export highlighting

### ISSUE THREAD

**Issue by bradennapier** [gandm/language-babel#439]
When using flow within the declare module syntax, it is not properly handling "handling declare export"  below is a sampling

```js
declare module 'axios' {
  declare export type AxiosConfig = AxiosXHRConfig<*>
  declare type $AxiosXHRConfig<T> = AxiosXHRConfig<T>;
}
```

![image](https://user-images.githubusercontent.com/15365418/32206906-85d29d58-bdb5-11e7-9df7-b898b19444c0.png)

---

**SideNote**:  I would question whether it makes sense to have the "?" in any location (which will make an item optional) highlighted differently to emphasize?  Perhaps the "meta.constant" makes since as it is a "constant modifier" :-P

**Comment by gandm** [comment]
Not sure I quite understand your side note. However I agree that the ? is not handled well in the grammar. To be frank I've been hopping for over a year that Max Brunsfeld's (GitHub Atom developer) new parsing system - [tree-sitter](https://github.com/tree-sitter) and the [atom tree-sitter integration](https://github.com/atom/tree-sitter-syntax) - that replaces TextMate grammars would be coming to Atom. I watched his presentation at GitHub Universe a few weeks ago and he said it should be released in the next few months. So I think we can say goodbye to the horrid regex parsing.

**Comment by bradennapier** [comment]
Wow that would be amazing to see.  Although I do not think it will work well in my case -- heh we will see.

and what i mean is that 

```js
export type $FooState = {
  foo: ?string,
  bar?: number,
};

```

in this case the "?" before string and the "?" after bar should be orange for me (constant).  This way they stand out  and become immediately apparent (since they do have special meaning in these specific locations).  

Should be a fairly straight forward change, we have put our grammars together in completely different ways so it's hard to decipher the specifics.

**Comment by bradennapier** [comment]
Awesome, yeah that works -- appreciate it!
