### ISSUE TITLE
Wrong ES6 method definition colors

### ISSUE THREAD

**Issue by klapec** [gandm/language-babel#44]
Since 0.11.0, parentheses and the parameters themselves are displayed in different colors than before.

@0.10.5:
![https://i.imgur.com/rlYOod1.png](https://i.imgur.com/rlYOod1.png)

@0.11.0 (and 0.11.4 as well):
![https://i.imgur.com/XqxaqEg.png](https://i.imgur.com/XqxaqEg.png)

Was this an intended change? Here's how it looks on Sublime Text 3 with the babel package installed (also notice the `import` and `from` keywords):
![https://i.imgur.com/vxJC4q6.png](https://i.imgur.com/vxJC4q6.png)

I'm using the [oceanic-next-syntax](https://github.com/smlombardi/oceanic-next-syntax) syntax theme, if that matters.

**Comment by gandm** [comment]
When I introduced flow support I changed the value of arguments passed in functions and methods from `variable.parameter.function.js` to `storage.type.variable.flowtype` for no other reason than the color of parameters was just white in the One Dark scheme and it is just a variable after all. I guess the original is the more correct scope name. Do you have strong opinion on this? Not a lot is left from my port of babel-sublime.

I can't see any difference in the import using oceanic-next syntax in regard to imports!
 
![image](https://cloud.githubusercontent.com/assets/2313237/9232354/1e3f2832-4125-11e5-9179-faffa3e64684.png)
![image](https://cloud.githubusercontent.com/assets/2313237/9232366/31e44674-4125-11e5-860b-e3926d05ea91.png)

**Comment by gandm** [comment]
I have no idea about sublime-text as I don't have it and have never used it. My guess is that the syntax styling  for imports is different on both platforms. The scope name for import is `keyword.control.module.js`

**Comment by klapec** [comment]
No, I don't have strong opinion on this. It's not a big deal. I recently switched from Sublime and this particular color scheme is something that I'm used to. I haven't had any problems with 0.10.5 so I'm probably going to stay on it and not update as it "just works". Thanks for the reply.

**Comment by gandm** [comment]
I will change the colour of the parens in my next release. That is an error.
