### ISSUE TITLE
[Flow] Complex Array<> highlights upper-case as constants

### ISSUE THREAD

**Issue by bradennapier** [gandm/language-babel#440]
Sorry for all the reports here!  Just want to get them all out while I remember.

It would appear that multiple levels of Array can trick the grammar into highlighting upper-case as CONSTANTS.

![image](https://user-images.githubusercontent.com/15365418/32206994-1eb3e84c-bdb6-11e7-96f2-291932ab632b.png)

````js
type test = {
  foo: Array<<U>(data: T) => U>
}

**Comment by gandm** [comment]
For some reason I made a commit quite a while ago that stopped me treating << as a nested generic. but I don't know why!
