### ISSUE TITLE
Styled components breaks syntax highlighting.

### ISSUE THREAD

**Issue by vladimirvolek** [gandm/language-babel#442]
This line breaks syntax highlighting

```
border-right: ${props => (props.isLast ? 'none' : `1px solid ${colors.LIGHT_GRAY_3}`)};
```

![image](https://user-images.githubusercontent.com/3112191/32237094-4f059e92-be64-11e7-9d14-e4b23d89bd6c.png)

![image](https://user-images.githubusercontent.com/3112191/32237062-389843ee-be64-11e7-9e46-2ae59788bbf6.png)

**Comment by gandm** [comment]
Seems OK to me
![image](https://user-images.githubusercontent.com/2313237/32237908-21c019ea-be5e-11e7-9df3-4164176440df.png)
Do you have a larger snippet of the actual code?

**Comment by vladimirvolek** [comment]
Reboot fixed it, sorry and thank you :)
