### ISSUE TITLE
Do you plan add support for babel v7 with scoped packages?

### ISSUE THREAD

**Issue by neyasov** [gandm/language-babel#446]

**Comment by gandm** [comment]
`language-babel` should support V7, including scoped packages. As I use the `babel-core` API this should be transparent to me, albeit I'm not entirely sure `source-preview` will work correctly. I just call the `babel-core` api and it does the rest. Have you tested it? Do you have a issue?

**Comment by neyasov** [comment]
When saving, I get an error message `LB: Babel v6.25.0 Transpiler Error`, but in the console without errors.

**Comment by gandm** [comment]
The message indicates Babel v6 is being used. I will provide this version if no other Babel version is found in the project's node-modules. Are you sure you have installed Babel V7 into the project. i.e. is it in the package.json manifest of the project and has it been npm/yarn installed?

**Comment by gandm** [comment]
It's curious that the message only appears in the console. I don't do a console.log but use Atoms notification API on [this line of code](https://github.com/gandm/language-babel/blob/master/lib/transpiler.coffee#L178)

**Comment by neyasov** [comment]
@gandm, If you use the yarn workspace, babel-core moves to the root directory of node_modules, after which the language-babel returns an error on save

**Comment by gandm** [comment]
@neyasov Thanks for the information. I've added a new issue that tracks this https://github.com/gandm/language-babel/issues/451

**Comment by gandm** [comment]
@neyasov I've just pushed a commit that adds support for @babel/core and Yarn workspaces. It'd be great if you could test it. The file changes is in the lib directory https://github.com/gandm/language-babel/blob/master/lib/transpiler-task.coffee You can just copy this and overwrite the one in `~/.atom/packages/language-babel/lib` and restart Atom.y

It now searches project root `babel-core` and `@babel/core` and then if the parent directory has a `yarn.lock` and `package.json` has a `workspaces` property it will check   `babel-core` and `@babel/core. The search is in that order - first found wins.

Let me know how it goes.

**Comment by neyasov** [comment]
@gandm, `babel-core` works well if specified in devDependencies, but `@babel/core` is overridden by old versions of babel-core. I made a fix in #452

**Comment by neyasov** [comment]
@gandm, For lerna monorepo, the error was repeated, because there `@babel/core` is two levels higher

**Comment by gandm** [comment]
@neyasov OK I'll modify to walk to path to root looking for a babel core.
