### ISSUE TITLE
variable as argument to console.log after await is wrongly set as type and primitive

### ISSUE THREAD

**Issue by bobmoff** [gandm/language-babel#448]
![image 2017-11-05 at 12 32 51 am](https://user-images.githubusercontent.com/1033236/32410477-5debc5de-c1c1-11e7-883b-f4ace3725a89.png)

and therefor, monokai will paint it blue :(

this started in the latest version (2.77.0), if i go back to prev version, its fine.

**Comment by gandm** [comment]
Can you try 2.77.1

**Comment by bobmoff** [comment]
Yes, it works. Great! Thx for very fast response.
