### ISSUE TITLE
Syntax highlight breaks when there's jsx code inside a function prop

### ISSUE THREAD

**Issue by juliobetta** [gandm/language-babel#449]
I'm using v2.77.0

![screen shot 2017-11-05 at 10 58 03](https://user-images.githubusercontent.com/394147/32414975-ac0d682e-c218-11e7-974f-8e3142baecd3.png)

**Comment by gandm** [comment]
Can you try 2.77.1

**Comment by juliobetta** [comment]
I can see that there's a v2.77.2, but it's still not working... The problem happens only when I use parens like in `render = { () => ( ... ) }`

**Comment by gandm** [comment]
Oh yes I see now, I missed the open parens on the end of line 17 when testing! I will fix tomorrow. In the meantime you can put the `render => (` on a separate line. Sorry for the inconvenience.

**Comment by gandm** [comment]
OK this should now be fixed in 2.77.3

**Comment by juliobetta** [comment]
Thank you @gandm !!!
