### ISSUE TITLE
Occurrences of 'type' are colored incorrectly

### ISSUE THREAD

**Issue by spencersteers** [gandm/language-babel#45]
Any occurrence of the word 'type' is colored like other storage keywords. It also seems to have weird effects for the rest of the line as well.

<img width="169" alt="screen shot 2015-08-12 at 7 10 52 pm" src="https://cloud.githubusercontent.com/assets/2586501/9240704/9c5d4860-4126-11e5-9fe3-f60adc947746.png">

I poked around a bit and it looks like the pattern is here: https://github.com/gandm/language-babel/blob/master/grammars/Babel%20Language.json#L1696

Not super familiar with language grammars so please disregard if it is something with my setup/syntax theme.

Thanks!

**Comment by gandm** [comment]
Are you using language-babel 0.11.5? What syntax theme? I can't recreate. It could be something above the code in the image you sent me causing it. If you have more code above can I have it? 
One Dark
![image](https://cloud.githubusercontent.com/assets/2313237/9241740/7091d068-416f-11e5-9947-607a6ef1b2af.png)
Atom Dark
![image](https://cloud.githubusercontent.com/assets/2313237/9241750/855fef5c-416f-11e5-81ea-636532009f5b.png)
Cobalt2
![image](https://cloud.githubusercontent.com/assets/2313237/9241762/a7551d1c-416f-11e5-9860-4ef71ca5b1c3.png)

**Comment by gandm** [comment]
Ignore my previous comment I'd left 0.10.5 running when I did the above screen shots! I can see it now. I'll check.

**Comment by gandm** [comment]
Fixed in 0.11.6. Sorry about that.

**Comment by spencersteers** [comment]
No worries! Thanks for the quick fix!
