### ISSUE TITLE
Support pug through template literal

### ISSUE THREAD

**Issue by ezhlobo** [gandm/language-babel#454]
Hey, just want to know what do you think about supporting highlighting of pugjs code?

In js files it can occur with plugins like [pugjs/babel-plugin-transform-react-pug](https://github.com/pugjs/babel-plugin-transform-react-pug).

Example:

```js
const Component = () => pug`
  .wrapper
    p.description Hello World
`
```

Are you interested in supporting pugjs?

**Comment by gandm** [comment]
You should be able to support pug by using the `language-babel` option described [here](https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions)
e.g. Using `atom-pug` or `language-pug` as an extension grammar, put `pug:source.pug` in the config.

**Comment by ezhlobo** [comment]
@gandm that's awesome! Thank you very much, I was thought that this is just for internals...
