### ISSUE TITLE
How to disable auto-completion for tags 

### ISSUE THREAD

**Issue by axe-z** [gandm/language-babel#455]
I use this tool in an autocomplete-plus, that does already handles tag closing, 
And right now I kind of get 2 closing tangs on pressing enter 

`<div></div></div> ,` is there a way to only stop the auto-closing part of it ?

**Comment by gandm** [comment]
Not currently. `language-babel` uses the autocomplete-plus API to provide suggestions. What is the other package/tool you use that also closes tags?
