### ISSUE TITLE
Known Grammar Limitations:-

### ISSUE THREAD

**Issue by gandm** [gandm/language-babel#46]
This grammar has certain limitations.

* let, var and const variables support flow typing but if used then the statement must be terminated with a semi-colon. Multiple variables and assignments may appear in the statement but the first must have a flow type else the grammar assumes no flow types for the remainder of the statement.

* ES7 Class properties with flow typing must terminate with a semi-colon. e.g. `static a: number = 1;` 

* Arrow functions must have the => on the same line as the function name/literal and parameters.

**Comment by myknbani** [comment]
There's also a problem with syntax highlighting.  The first line containing `const` is marked with an error.

![upload](https://cloud.githubusercontent.com/assets/5841268/10598605/ecd7d59e-772c-11e5-8695-ade2cad9e366.jpg)

**Comment by gandm** [comment]
The language-babel syntax seems ok - correct colour etc. The message is from eslint - does it support flow? I didn't think it did?

**Comment by myknbani** [comment]
oh, I didn't notice the ESLint badge...my bad.  I'll just check my eslint config then.  Thanks :D

**Comment by mrapogee** [comment]
Hey,

Can this be fixed? I'm using js-standard style and it's causing issues with ESLint and syntax highlighting.

**Comment by gandm** [comment]
@mrapogee regrettably, I don't think I can fix this ( or maybe I could but it would require a major change that I'm not willing to undertake - essentially rewrite the grammar ). If you use flow syntax in this grammar then these are fixed limitations. You can avoid eslint errors if using js standard's `semi: [2, "never"]` by starting a new line following the let/var/const with `;{}`. and the grammar will also work correctly. Not a great solution I know.

e.g. 
```jsx
var a: any = 'some string'
;{}
var a: any  = 1 + 2
;{}
var a = 1
```

**Comment by mrapogee** [comment]
Okay, I'm just doing this for now
```javascript
const system: EventSystem = buildContext.system; // eslint-disable-line semi
```

Thanks.

**Comment by vjpr** [comment]
Just checking if this is a known consequence on not using a semi-colon after a flow statement. It wasn't clear that using flow without semi-colons would break things unexpectedly.

```
class {
  
  async foo() {
    const a: Object = {}
  }
  
  async bar() { // <- `bar` not detected as `.method` unless `;` after `const a...` above.
    
  }

}
```

Also, `async` becomes a `.variable.readwrite`.

**Comment by gandm** [comment]
@vjpr Yes the grammar only supports flow when I can determine a statement has ended. This is easy with functions and arrows but I need a semi-colon on const, let,var, static's. If you use an ASI coding style and in-line flow typing then this grammar is probably not best suited to you needs.

If semi's aren't your taste then you could use commented typing, such as `const a /*: Object */ = {}`

I'm hoping that the Atom team can allow some form of incremental AST to be used instead of TextMate style grammars but in the meantime this is the best I can do.

**Comment by gandm** [comment]
@vjpr  I see you've released a syntax theme that mentions language-babel doesn't support flow. I don't understand this as it fully supports flow with true scoping for flow objects. It is true that I don't support ASI syntax for certain flow statements as shown above. Also, language-babel is recommended as the flow javascript package for facebook's Nuclide project. See http://nuclide.io/docs/editor/setup/#post-installation__recommended-packages

I'm interested to understand what parts of flow I don't support?

**Comment by vjpr** [comment]
From https://github.com/vjpr/atom-webstorm-syntax-theme

> NOTE: I don't use this plugin because it doesn't fully support Flow.

What I meant was that it doesn't support Flow with ASI. I will update it.

---

What would it take to support Flow+ASI?

**Comment by gandm** [comment]
@vjpr It is quite tricky to support flow and be aware of and also scope flow syntax. It may be possible to add ASI for vars etc but it would take some time and wouldn't be bullet proof. e.g. flow typecasts `([1, "a", true]: Array<mixed>).map(x => x)` starting a line, but I guess that's always an issue for ASI anyway. Looking at this thread I don't see a lot of people requesting it?

The babel-sublime grammar you mention is what this was package was based upon. The JSX and Flow have been added and other parts changed significantly. The current version of that package uses a new form of grammar syntax that is easier and better but isn't supported by Atom. Zertosh who maintains that package is on the Nuclide facebook team and chips in here sometimes.

The other grammars you mention either have issues or ignore/don't scope flow. As a trivial example take the following 3 lines and put them into the grammars you mention. Typical issues are polymorphs maybe misrepresented as a Tag start, Destructuring gives strange scopes for the target, etc.
```jsx
let a: Function = function fooGood<T: { x: number }>(obj: T = {x: 1}): T { return obj; };
var obj: {a: boolean; b: string; c: Foo} = {a: true, b: "Hi", c: new Foo()};
const a=1;
var {x, y, ...o} = {x: '', y: 3, o: {z: false} }; // No flow on this line!!!
```
In the longer term TextMate style grammars have had their day; better an incremental AST parser such as the one GitHub's Max Brunsfield has developed - If your interested see [tree-sitter](https://github.com/tree-sitter/tree-sitter) and [Tree Sitter Package binding](https://github.com/maxbrunsfeld/atom-syntax-tree). I'm hoping that Babel's babylon parser will be able to do this one day.

**Comment by vjpr** [comment]
@gandm Thanks for the details!

The Flow syntax does look quite tricky to detect correctly with the TextMate grammars. I need to read more about incremental AST parsers.

> The other grammars you mention either have issues or ignore/don't scope flow.

I would prefer to ignore Flow parsing. Would this be possible? The thing that stops me being able to use this package is that when I use Flow without semicolons, it will break the rest of the code highlighting.

**Comment by gandm** [comment]
@mrapogee @vjpr Just pushed 2.18.0 that supports using flow in files that use ASI. Let me know how it goes.

**Comment by vjpr** [comment]
Thanks! I'll test it out.
