### ISSUE TITLE
sourceMappingURL is set to absolute path of local source map

### ISSUE THREAD

**Issue by mdupls** [gandm/language-babel#462]
The source maps cannot be displayed by the browser dev tools since the source map urls are absolute paths to the local resources. There should be a way to specify relative paths to the location of the source maps so that a web server can serve these.

I get this:
`//# sourceMappingURL=/Users/<user>/project/dist/index.js`

But want this:

`//# sourceMappingURL=dist/index.js`

Here are my configs:

```
13:06 $ cat .languagebabel 
{
	"projectRoot": true,
	"babelMapsAddUrl": true,
	"babelSourcePath": "src",
	"babelTranspilePath": "dist",
	"babelMapsPath": "dist",
	"transpileOnSave": true,
	"createTranspiledCode": true,
	"createMap": true
}
```

```
15:26 $ cat .babelrc 
{
	"presets": [
		["env", {
			"targets": {
				"chrome": "40",
				"ie": "11"
			}
		}]
	]
}
```

**Comment by gandm** [comment]
Can you try 2.81.1 and let me know how it goes.

**Comment by mdupls** [comment]
Amazing @gandm. That works! Thanks for the speedy fix.
