### ISSUE TITLE
Key names in object literals share same color as strings

### ISSUE THREAD

**Issue by kunokdev** [gandm/language-babel#466]
I am not sure if this is by design but I personally like how default JavaScript highlight uses different color for key names than strings, while `language-babel` package uses same color for both:

![image](https://user-images.githubusercontent.com/13220754/34668849-7351912a-f46f-11e7-9c01-0aed4a7c8d20.png)

Any workaround to make behave like JavaScript highlighter?

**Comment by gandm** [comment]
By design but you can use any color you need. See here for how https://github.com/gandm/language-babel/issues/463#issuecomment-353128987

**Comment by kunokdev** [comment]
Thanks and sorry for duplicate issue.
