### ISSUE TITLE
Supporting the variable convention - vm ?

### ISSUE THREAD

**Issue by alxtz** [gandm/language-babel#467]
![](https://user-images.githubusercontent.com/16031425/34721256-0a4887a6-f57d-11e7-981f-8e52801ee416.png)

Though I see it as a controversial convention, a lot of angular / vue projects uses it.
It's more like the tag `syntax--dollar`.

![](https://user-images.githubusercontent.com/16031425/34721405-92e84aba-f57d-11e7-8d1f-61a39d714fc2.png)

Or maybe we should have a package called `language-conventions` ?

**Comment by gandm** [comment]
Not sure I would want to do this as it is likely used in other ways. e.g. `vm` is also used in Node's Virtual Machine instructions.

**Comment by alxtz** [comment]
@gandm 
That's something I've not heard before, thanks for the remind !
I would be interest to know about the doc about node's VM instructions, is there any references ? ( I've only found the Node VM module )

**Comment by gandm** [comment]
https://nodejs.org/api/vm.html
