### ISSUE TITLE
Note getting HTML syntax highlighting in template strings

### ISSUE THREAD

**Issue by ericbiewener** [gandm/language-babel#469]
See below. I have the [AngularJS-Atom](https://github.com/angular-ui/AngularJS-Atom) package installed as well in case that's relevant. And I do have `Babel` selected as the language for the file. Highlighting works fine in *.html files.

![image](https://user-images.githubusercontent.com/253298/35249523-359e7a1e-ff87-11e7-8523-08da04fb0eae.png)

**Comment by gandm** [comment]
I use the language-mustache package to highlight templates of this type. Please ensure it is installed and enabled.

**Comment by ericbiewener** [comment]
yep, that's it. thanks!
