### ISSUE TITLE
String and fat arrow syntax highlighting for es7 class properties

### ISSUE THREAD

**Issue by peduxe** [gandm/language-babel#47]
Just strings within array square brackets gets highlighted, in the other cases it is white.

\+ `arrow functions` not highlighted as well.

![example with material syntax:](http://i.imgur.com/heJMBr8.png)

![example with one dark syntax:](http://i.imgur.com/a5UhMjt.png)

**Comment by gandm** [comment]
Hope 0.11.9 fixes it for you.

**Comment by peduxe** [comment]
@gandm sweet, that was fast :+1:
