### ISSUE TITLE
Arrow functions with negative number Flow return type breaks syntax highlighting

### ISSUE THREAD

**Issue by CadenP** [gandm/language-babel#474]
An arrow function declared with a return type that includes a negative number causes the syntax highlighting to break.

## Code to Reproduce:
```
// @flow
let a = () :-1 => {}
```

## Example usage:
```
// @flow
let sortFn = (a :number, b :number) :-1|0|1 => {
  if (a === b) return 0
  return a < b ? 1 : -1
}
```

## Workaround:
```
// @flow
type ComparisonResult = -1|0|1
let SortFn = (a :number, b :number) :ComparisonResult => {/*...*/}
```

## Notes:
It does not appear to matter where the minus sign appears in the return type (`:-1` and `:string|-1` both cause the same error).
With generics on the function, the generic types seem to act as JSX tags so "closing" the generic types fix the highlighting for following code (but not preceding code).

**Comment by gandm** [comment]
fixed in 2.83.0. Thanks.
