### ISSUE TITLE
Unable to use Emmet completions

### ISSUE THREAD

**Issue by RustyDev** [gandm/language-babel#475]
I have a `.languagebabel` file with the following flag setting:

```
{
  "emmetCSSAutocomplete" : true
}
```

I also enabled `Allow Local Override` in the package settings. Is there something else I'm missing?

Thanks!

**Comment by gandm** [comment]
That should work. You don't need `Alow Local Override` for emmet - that is only used if you wish to use the Babel transpiller. The atom package `autocomplete-plus` must be enabled.

I guess you are using styled-comnponents? Are you getting any CSS suggestions at all?

**Comment by gandm** [comment]
Ah! I just noticed you added it to `.languagebabel` but it doesn't go there. That is only used for Babel transpiles. You need to change a `language-babel` package setting as shown below.
![image](https://user-images.githubusercontent.com/2313237/35776824-604d7454-099b-11e8-8f4e-e6eac4469f45.png)
This will add a setting to Atom's `config.cson`.

**Comment by RustyDev** [comment]
I have no idea how I missed that :) Thank you!
