### ISSUE TITLE
Grammars are not applied on restored files

### ISSUE THREAD

**Issue by paradoxxxzero** [gandm/language-babel#476]
With atom 1.24.0-beta-3, the babel grammar is not applied to restored at launch jsx files. (They stay with the Plain Text grammar). If I close the file and reopen it, it works as intended. I tried with other grammar packages and it works with them.

NB: It does not apply grammar at package install neither.

**Comment by gandm** [comment]
I don't have control over what Atom allocates as the grammar apart from specifying file types. Atom does the rest.

**Comment by paradoxxxzero** [comment]
I posted it here as it works with other language package I figured something should be done differently.
I'll report upstream thanks.

**Comment by gandm** [comment]
Thanks for reporting to Atom. Seems like their issue now so closing.
