### ISSUE TITLE
Suggested themes?

### ISSUE THREAD

**Issue by Daniel15** [gandm/language-babel#48]
This is not really an issue, but I couldn't find a place for general discussion. 

Do you have any suggested dark themes to use along with this package? The default Atom theme doesn't seem very nice, it has a lot of red in it. Seems like a lot of symbols are red.

**Comment by gandm** [comment]
Not sure what to suggest. There are always some issues with mixing themes and grammar scoping, either inconsistencies or one colour being dominant. If I were a graphic designer I'd do my own theme to go with this grammar, but alas....! FWIW I'm using One Dark but it can be a bit red depending on the code. I've added some screen shots of some other dark themes I've looked at.

One Dark
![image](https://cloud.githubusercontent.com/assets/2313237/9489675/886dca50-4bda-11e5-9733-6b2b0159728a.png)
Oceanic Next
![image](https://cloud.githubusercontent.com/assets/2313237/9489723/fc38570c-4bda-11e5-9abf-d72233a0f5e0.png)
Seti
![image](https://cloud.githubusercontent.com/assets/2313237/9489739/2734c8b4-4bdb-11e5-8318-c79a573435fc.png)
Visual Studio Dark
![image](https://cloud.githubusercontent.com/assets/2313237/9489944/822300e6-4bdc-11e5-8759-064f4c8591e8.png)

**Comment by peduxe** [comment]
Material Syntax is pretty good as well, I prefer to use it with One Dark UI.

**Comment by Daniel15** [comment]
Thanks! @gandm - Which Visual Studio Dark theme is that? I searched for Visual Studio dark but there's a few different themes for it. I use Visual Studio a lot too, so having a matching theme would be great :D

**Comment by gandm** [comment]
@Daniel15 The Visual Studio Dark theme as shown in the last screenshot is this one https://atom.io/themes/visual-studio-dark-syntax
