### ISSUE TITLE
Fewer releases

### ISSUE THREAD

**Issue by JeffCohen** [gandm/language-babel#484]
(I hope it's ok to provide feedback here, I couldn't find a reference to a mailing list or twitter account)

I love this package and appreciate all of the hard work! 

But until Atom can automatically install package updates, it's annoying to be forced to accept package updates every day or every other day.  Unless you're fixing a critical bug, releasing once a week or every other week would be much better.

Thank you!

**Comment by gandm** [comment]
The past few releases have been fixing 'critical' bugs; at least they were for some. I hardly ever use Atom so I guess I'm not affected - I wasn't aware that Atom forced anyone to update packages but I'll try to avoid updating this package too often.
