### ISSUE TITLE
Regex or escape character being highlighting in strings

### ISSUE THREAD

**Issue by peduxe** [gandm/language-babel#49]
![Example](http://i.imgur.com/RywVFwl.png)

Here I want to type the instance where my sql server runs and it appears it's highlighting a javascript regex or escape character, the core javascript grammar behaves the same way.

I expected it would just highlight when it's one of those escape characters for e.g: 
* newline: `\n`
* carriage return: `\r`
* or escape quote: `\'`

**Comment by gandm** [comment]
Fixed in 0.11.11
