### ISSUE TITLE
is there any way to use babel for all js file by default?

### ISSUE THREAD

**Issue by ChenXiyu** [gandm/language-babel#491]
Hey, Thank you for your brilliant work, for this awesome extension. 
I'm trying to set `Babel ES6 JavaScript` as my default parser for all my `js` file, and I tried to set `customFileTypes` like below: 
```
core: 
    customFileTypes:
         "source.js.jsx": [
            "js"
         ]
```
but it not works, when I open `js` file, they still use `javascript`,
and I noticed that `scope.js.jsx` already includes `js` file, even no customization did. 
I guess there are some priority issues in my configurations.
base on the priority assumption, I disabled `language-javascript` extension, it still not works.
can you give me some hint, what should I do to finish this?

**Comment by gandm** [comment]
This core setting can cause issues if it is set.
![image](https://user-images.githubusercontent.com/2313237/38465824-49ea8446-3b18-11e8-9867-a6eded027c3c.png)
Or maybe you have another JS language grammr installed?

**Comment by ChenXiyu** [comment]
Thank you @gandm , toggle off that, `Babel ES6 JavaScript` becomes my default parser for my `js` file.
still, have serval questions: 
1. is `supported languages` means language supported by core packages?
2. is possible or not I can use `Tree Sitter Parsers` and set `Bable` as default at some time?

**Comment by gandm** [comment]
1. Tree-sitter supported packages are those listed [here](https://github.com/atom/atom/pull/16299) but many others are being developed [here](https://github.com/tree-sitter) and by third parties.

2. I don't think so. It appears to be all or nothing. I would suggest asking the question at the atom github repo.

**Comment by ChenXiyu** [comment]
@gandm OK, Thank you for providing information

**Comment by sbrichardson** [comment]
Thank you @gandm - lifesaver!

**Comment by alliuca** [comment]
Disabling Tree Sitter Parsers works but now my cursor doesn't position itself correctly when going to a new line (see gif here, normally the cursor is aligned with the "c" of console)

![](http://g.recordit.co/s8jXUSejKX.gif)

Am I missing another setting for that?
