### ISSUE TITLE
language-babel causes autocomplete to stop working

### ISSUE THREAD

**Issue by adityavm** [gandm/language-babel#492]
Whenever I enable this package, autocompleter stops working / becomes extremely slow. Here are two GIFs showing the same file and keystrokes with and without language-babel enabled:

**With language-babel:**

![babel](https://media.giphy.com/media/mXitXYGcFnblWHcTJs/giphy.gif)

You can see how attempting to trigger it manually doesn't reveal the suggestions either.

**Without language-babel:**

![js](https://media.giphy.com/media/9AJ8peMHHtKIYY2gHl/giphy.gif)

Here the suggestions show up immediately.

Debug info:
```
> apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.1
python 2.7.10
git 2.16.0
```

**Comment by adityavm** [comment]
@gandm I don't see a `~/.atom/cache` directory. Do you mean the `~/.atom/compile-cache` directory?

**Comment by gandm** [comment]
Sorry, yes `~/.atom/compile-cache`

**Comment by adityavm** [comment]
@gandm ran the following sequence:

```shell
> apm rm language-babel
> rm -rf ~/.atom/compile-cache
> apm install language-babel
> atom .
```

Still no good. However, I did notice a couple of more things.

* Autocompleter works fine on a different, much smaller project (i.e. far fewer files, LOC, and `node_modules` packages)
* <kbd>Tab</kbd> doesn't work / works unpredictably when using language-babel. This also goes away when setting the language to standard Javascript.

![tab](https://media.giphy.com/media/4a8emFhoaaLNaavQzm/giphy.gif)

**Comment by gandm** [comment]
Sorry I have no idea. The Atom auto-complete package is independent of language-babel. I only use it when in JSX or styled-components CSS mode. I will say that the colour scheme that you have shown above looks strange. It doesn't match any theme I know of - language-babel doesn't show much white text normally.

**Comment by adityavm** [comment]
@gandm It's just [Monokai Seti](https://atom.io/themes/monokai-seti), and the language is definitely language-babel. I wouldn't make it up ;)

![screen shot 2018-04-14 at 7 18 50 pm](https://user-images.githubusercontent.com/80849/38768972-049b0612-4019-11e8-86f3-3450d5bffd63.png)

Is there a way to prevent language-babel from offering suggestions? I noticed in my bigger project, if I left the file open for some time (don't have exact numbers), the autocompleter did start working, but just for that file. A new file makes it stop again, as does closing and re-opening the existing file which it _was_ working for.

**Comment by gandm** [comment]
Language Babel doesn't offer suggestions inside JavaScript. As I said  the auto-completeplus package provides that data. I only provide suggestions for jsx closing tag names and CSS in a styled-components tagged literal.

**Comment by adityavm** [comment]
@gandm On further investigation, turning off [Atom TernJS](https://github.com/tststs/atom-ternjs) seems to get the autocompleter working again. I'm currently not sure where the issue lies; TernJS without language-babel works fine, and language-babel without TernJS works fine.

I would like to use both at the same time though ...

**Comment by gandm** [comment]
I've just tried atom-ternjs and it doesn't appear to work at all for me with or without `language-babel` enabled. Looking at the package and also the TernJS site it appears to unsupported, or at least awaiting another volunteer to take it over. 

Atom made some changes to the way autocomplete-plus works recently but this shouldn't be a breaking change. Given `language-babel` appears to work correctly I'm going to close this issue. If you have reason to believe I have a bug please re-open.
