### ISSUE TITLE
Tab doesn't work when using language-babel

### ISSUE THREAD

**Issue by adityavm** [gandm/language-babel#493]
When using `language-babel`, the <kbd>Tab</kbd> key doesn't work. Here's a GIF of what happens:

![tab](https://media.giphy.com/media/4a8emFhoaaLNaavQzm/giphy.gif)

The <kbd>i</kbd> is to go into vim insert-mode, after which <kbd>Tab</kbd> does nothing. Switching to `language-javascript` makes it work again.

**Comment by gandm** [comment]
No idea why as handling tabs is done by either Atom or your Vim package - I don't know which Vim you are using. I think you may have some issues with your Atom install. Have you tried it on another device?This package is used by thousands of people. I think Tab not working would be critical and would have been raised by someone else. Given your issues with language-babel I would suggest you switch to language-javascript as that seems to solve your problems.

**Comment by adityavm** [comment]
*Update* I found the offending issue and managed to fix it. `language-babel` seems to be setting the editor grammar to `jsx`, which was activating keybindings for emmet, causing <kbd>Tab</kbd> to fail.

I've fixed the keybindings now, and will close this issue. Hopefully it'll be useful for someone else in the  future.

**Comment by gandm** [comment]
Glad you fixed it. Yes I set the grammar to `source.js.jsx`
