### ISSUE TITLE
Nullish coalescing operator (stage-1 proposal) treated as ternary, breaks highlighting

### ISSUE THREAD

**Issue by MiracleBlue** [gandm/language-babel#495]
Howdy!

I've been making heavy use of some recent early-stage ES proposals, such as [Nullish Coalescing](https://github.com/tc39/proposal-nullish-coalescing).  Currently, language-babel is treating the operator as 2 ternaries, and as such, highlighting in the rest of a function block after this operator is a bit broken.

Example:
![screen shot 2018-04-29 at 9 18 31 am](https://user-images.githubusercontent.com/23368/39401681-6a391812-4b8e-11e8-8816-303834dadd04.png)

The first two functions in that screenshot use the nullish coalescing operator, and the closing brackets and parenthesise don't seem to be tokenized anymore (evidenced by the absence of highlighting and absence of scope classes in the inspector for those pieces)

From inspecting the scopes applied to the operator, each `?` is wrapped with these scopes: `keyword operator ternary js`

Atom: 1.26.1
language-babel: 2.84.0
OS: macOS 10.13.4

**Comment by xixixao** [comment]
Came here to post the same 👍

**Comment by MiracleBlue** [comment]
WOW that was fast.  Thanks so much @gandm for your efforts!
