### ISSUE TITLE
Babel ES6 JavaScript Grammar

### ISSUE THREAD

**Issue by 9585999** [gandm/language-babel#499]
Babel ES6 JavaScript Grammar not work with .js files.

![img 2018-05-10 20 53 50](https://user-images.githubusercontent.com/16165904/39885382-1c01675c-5495-11e8-9dce-615289ef18e2.PNG)
![img 2018-05-10 20 59 19](https://user-images.githubusercontent.com/16165904/39885384-1c219734-5495-11e8-9d07-e478fd920dc0.PNG)

**Comment by gandm** [comment]
I'm guessing that you have tree-sitter turned on. See https://github.com/gandm/language-babel/issues/491 and see if that helps.

**Comment by 9585999** [comment]
@gandm 
You were absolutely right! Many thanks! For a week I suffered and could not understand what was happening :)

**Comment by gandm** [comment]
Glad that fixed it for you.
