### ISSUE TITLE
Is it possible save in a config file where the transpiled files will be written?

### ISSUE THREAD

**Issue by mazzy89** [gandm/language-babel#51]
The package allows to define the folder where the files will be transpiled filling in the setting the field `Babel Transpile Path`. Is is possible to store this value in a config file? is is maybe in babelrc?

**Comment by gandm** [comment]
I'll look at doing this. I won't use .babelrc as I don't want to pollute it. I'm not sure how flexible this should be. One config file in the projects root folder or maybe look for config files in the path from the source file up to the project root. Probably the latter.
