### ISSUE TITLE
JSX not autocompleting with language-babel

### ISSUE THREAD

**Issue by serg337** [gandm/language-babel#516]
Up until a few days ago, when coding react native (using language-babel and autocomplete) all was good and using Monokai syntax my components would appear in a Cyan colour and autocomplete 
was working.

Today my components look like in the picture attached. It's like it doesn't recognize them anymore, autocomplete no longer works for my components. The only way to solve this was to disable language-babel and enable the react plugin for atom. Autocomplete works again and the colour of the component changed.

<img width="755" alt="screen shot 2018-10-31 at 1 28 48 am" src="https://user-images.githubusercontent.com/19732264/47758680-5ac2c680-dcac-11e8-8a49-d8c3e4532d9c.png">
.

How can I fix this? Did I miss something?

**Comment by gandm** [comment]
See https://github.com/gandm/language-babel/issues/510
