### ISSUE TITLE
Self closing tags

### ISSUE THREAD

**Issue by duro** [gandm/language-babel#55]
I am having a hard time in the grammar getting self closing tags to style properly.

Here is what they send up looking like:

![Self Closing Tags](https://cloud.githubusercontent.com/assets/17632/9640029/1bf0f53e-5164-11e5-970e-ecc6017760c6.png)

Checking the inspector, it appears that the closing tag just gets treated like raw text:

![Inspector](https://cloud.githubusercontent.com/assets/17632/9640049/4c15454e-5164-11e5-92b2-be94b21870ed.png)

Could we get the grammar to create a span for that self-closing end of the tag?

**Comment by gandm** [comment]
Should be fixed. Can you let me know what the theme you are using is so I can add it to my tests. Thanks.
