### ISSUE TITLE
Super calls scope

### ISSUE THREAD

**Issue by peduxe** [gandm/language-babel#56]
Would you restrict [this scope](https://github.com/gandm/language-babel/blob/master/grammars/Babel%20Language.json#L925-L926) just to be applied inside a class?

I want to give it another highlight color without overwriting variable declarations, imports, etc.

```js
class {
  constructor () {
    super.foo();
  }
}
```

**Comment by gandm** [comment]
Not easily. Do you have an example of using super outside of a class method?

**Comment by peduxe** [comment]
Oh I forgot to add above that the `super` keyword also styles in the following case,

```js
let super = 0;
```

**Comment by gandm** [comment]
I don't know how you are using super as a variable in a let statement. Anyway, it's going to too difficult to do this.

**Comment by peduxe** [comment]
@gandm not a big deal, I would like to contribute but it seems that there are invalid characters in most of the regexes, I guess it's escaping them but i'm not sure.

**Comment by gandm** [comment]
I'm not sure where the invalid regexs are. Please let me know. Grammar info https://manual.macromates.com/en/language_grammars and http://www.apeth.com/nonblog/stories/textmatebundle.html

**Comment by peduxe** [comment]
There are characters which aren't valid regex, 

[invalid](https://regex101.com/r/vJ1mB6/1)

[valid](https://regex101.com/r/vJ1mB6/2)

Thanks for the links, it's more clear now how the grammars are created.

**Comment by gandm** [comment]
The grammars don't use the JavaScript regex, they use the Oniguruma RegEx engine so that's why they seem invalid.

**Comment by peduxe** [comment]
@gandm oh never heard of oniguruma regex haha
