### ISSUE TITLE
Setting "Disable when no Bablerc File in Path" does not disable the package

### ISSUE THREAD

**Issue by AddictArts** [gandm/language-babel#58]
The grammars are still enabled, is it possible to have a disable for the grammars? It can conflict with other grammars that provide the same function through a different scope.

**Comment by gandm** [comment]
No it's not possible. I'm interested to know what the conflict is?
I guess you prefer other JavaScript grammars so the only suggestions I can make is either i) fork my repo and remove the grammar and use that or just remove the grammar from the downloaded package or ii) use https://atom.io/packages/file-types and associate a grammar with a file type/directory.

**Comment by AddictArts** [comment]
It conflicted for me with https://atom.io/packages/language-javascript-jsx, actually it won over that one, maybe the order they were applied. That package has a scope name source.js.subtlegradient and the built in source.js. I was able to use file-types to set jsx to source.js, thanks. Maybe default to File Types:  es6, babel and let people add js, and jsx or turn off js and jsx? Atom's language-js is what I prefer for js and jsx. Thanks for looking at this.

**Comment by gandm** [comment]
No problem.  If you are using the atom provided language-javascript package for jsx then you aren't using language-Babel for the transform of JSX, so that should be ok. I'm sure you are aware Babel is now the standard jsx transform tool. http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

**Comment by AddictArts** [comment]
Yes I am aware of that babel is the official or standard jsx transform tool. I looked at just removing the grammar, but the save event uses that to fire the transpile. I could change it to the grammar I prefer, but it would be nice to config this. I tried adjusting the theme and you can't control the colors of things like the keys, so I prefer the second attachment to the first and prefer to avoid editing language-babel.less. Thanks for the help.

![1](https://cloud.githubusercontent.com/assets/911906/10406611/357cc650-6e96-11e5-89f5-4e3ff6edf9d5.png)
![2](https://cloud.githubusercontent.com/assets/911906/10406612/3861bf42-6e96-11e5-9ce3-549e13928a7e.png)
