### ISSUE TITLE
Template strings do not close

### ISSUE THREAD

**Issue by duro** [gandm/language-babel#59]
If I use ES6 template strings, everything else after the closing tick gets a `quasi` and `string` class.

<img width="1326" alt="window_and_server_js_-__users_adamduro_workspace_projects_zg-redux-webpack_-_atom" src="https://cloud.githubusercontent.com/assets/17632/9701558/309ef1d4-53e4-11e5-9193-0223e20d7969.png">

<img width="493" alt="window_and_server_js_-__users_adamduro_workspace_projects_zg-redux-webpack_-_atom" src="https://cloud.githubusercontent.com/assets/17632/9701560/57926870-53e4-11e5-975e-4f1cdc4451af.png">

**Comment by duro** [comment]
BTW, here is the theme I am using:

https://github.com/duro/duro-oceanic-next

**Comment by gandm** [comment]
I can't recreate it. Not sure what the embedded planet is.
Atom Dark
![image](https://cloud.githubusercontent.com/assets/2313237/9702899/1752ca50-5468-11e5-9698-ccc688c49b59.png)
Duro Oceanic Next
![image](https://cloud.githubusercontent.com/assets/2313237/9702903/449db664-5468-11e5-8ded-2bab70b9c2eb.png)
Probably something prior to the quasi. Can you let me have the source file up to line 25?

**Comment by gandm** [comment]
Closing this. Open if it's still an issue.
