### ISSUE TITLE
.babelrc support

### ISSUE THREAD

**Issue by mistadikay** [gandm/language-babel#6]
Hi,

Great package and pretty long awaited, thank you!

One thing is missing though. Most babel users use [.babelrc](https://babeljs.io/docs/usage/babelrc/) containing babel configuration which can be different in different projects and even folders. So it would be great if *language-babel* could get that configuration from .babelrc about stage, blacklist transformers, optional transformers, etc. and apply it to corresponding scope this .babelrc is in.

Thanks again, great job!

**Comment by gandm** [comment]
Also as a FYI. `.babelrc` files are supported by language-babel in that if one exists in the chain of directories above and including the source directory the options within will be read and used.

However, I need to add some config/code to make this more sensible. If you remove any transforms from the language-babel config you can use `.babelrc` files quite happily.

**Comment by gandm** [comment]
A new release 0.6.0 pushed to add new features to support .babelrc files

**Comment by mistadikay** [comment]
awesome, thanks!
