### ISSUE TITLE
Bad syntax highlighting with export class

### ISSUE THREAD

**Issue by janmarek** [gandm/language-babel#61]
In this code

```js
export default class Cls {
    static CONSTANT = 1;
}
```

class and static are not highlighted as keywords

**Comment by gandm** [comment]
Yeah sorry about that. I realised after I released 0.13.3 and fixed it in https://github.com/gandm/language-babel/commit/a56518bc9d2e32481eb828f5637dee7445180636 but haven't published it yet. Will do so shortly.
