### ISSUE TITLE
v0.13.3 broke syntax highlighting for function parameters

### ISSUE THREAD

**Issue by AlexKvazos** [gandm/language-babel#62]
v0.13.2 shows like this:
![](https://i.alexkvazos.me/DaemonModel_js_-__Users_alexkvazos_Documents_Projects_CubedHost_Prisma-Panel_-_Atom_1B9F7219.png)

v0.13.3 shows like this:
![](https://i.alexkvazos.me/DaemonModel_js_-__Users_alexkvazos_Documents_Projects_CubedHost_Prisma-Panel_-_Atom_1B9F727E.png)

The function parameters do not have their own style anymore. And something happened some releases ago that this parameters had a different color from the blue one that you can see on `let`and on `@param`.

It was in v0.10.0:
![](https://i.alexkvazos.me/DaemonModel_js_-__Users_alexkvazos_Documents_Projects_CubedHost_Prisma-Panel_-_Atom_1B9F73AB.png)
Parameters where highlighted in their unique color but ES6 class functions were not getting highlighted and @param flags on docblockr were just gray. I'd like that orange parameter color back on ^0.13.3 pleasee

**Comment by gandm** [comment]
jsdoc and jsduck highlighting was introduced by others in two PR's. https://github.com/gandm/language-babel/pull/50 and https://github.com/gandm/language-babel/pull/54
I removed the parameter colour as explained here https://github.com/gandm/language-babel/issues/44
I will take another look at this but I can't promise anything since the flowtype support has made the whole processing quite different.

**Comment by AlexKvazos** [comment]
I don't care if we can't go back to the unique parameter color but having them in plain white with no style difference, then it will get a bit painful. I hope it can go back to how it was on 0.13.2.

**Comment by gandm** [comment]
Themes make a huge difference and it is almost impossible to keep people happy. e.g.screen shots below the Left Image is 0.13.3 the right is 0.10.5

Visual Studio Dark
![image](https://cloud.githubusercontent.com/assets/2313237/9748626/f00f12ce-567d-11e5-87a2-b25ba02c818c.png)

One Dark
![image](https://cloud.githubusercontent.com/assets/2313237/9748639/0b3a6b16-567e-11e5-902d-04874d12e26d.png)

Oceanic Next
![image](https://cloud.githubusercontent.com/assets/2313237/9748652/265955c4-567e-11e5-8a10-64756b238e51.png)

Atom Dark
![image](https://cloud.githubusercontent.com/assets/2313237/9748666/4383d05c-567e-11e5-95f2-913fab0cbed3.png)

**Comment by AlexKvazos** [comment]
I see, man that's sad. Any way you can hint me on how to modify a theme so that it works with your new setup? class names or anything. I just copied a theme and modified a few things long ago that I forgot what was the original one.

**Comment by gandm** [comment]
I'll take a look and see what can be done. Leave it with me.

**Comment by gandm** [comment]
If you just want to colour the arguments in lines 1 and 3 the same, e.g. all orange, that's easy. If you want methods/functions/arrowfunctions to be different from a function call that becomes a problem as a I use single regex grammar path for both.

**Comment by AlexKvazos** [comment]
Nono, having the arguemnts on line 1 and 3 all the same color (orange) is enough. I don't see a need to have different color on parameters of methods/functions/arrowfunctions.

**Comment by AlexKvazos** [comment]
I just pushed the theme i'm using to github, it is not linked to atom package registry yet though.
https://github.com/AlexKvazos/DimmedMonokai

**Comment by gandm** [comment]
Ok will look tomorrow.

**Comment by gandm** [comment]
I've just pushed 0.13.5 out that has made some small changes. You can modify your base.less file in your theme to include the following classes that will change how your code looks. The examples below are pretty horrid but I'll leave it to you to choose correct colours.

```
.variable.other.readwrite {
	color: orange;
}

.variable.other.class {
	color: green;
}

.variable.other.property {
	color: yellow;
}

.variable.other.object {
	color: cyan;
}
```

In your theme this looks like....Aghhhh!

![image](https://cloud.githubusercontent.com/assets/2313237/9754956/bb22e660-56c5-11e5-8367-61cfc3c10d59.png)

**Comment by AlexKvazos** [comment]
Pretty close, Is there a way that the `.readwrite` affects only function parameters? it also colors the imports and that looks very funky.

**Comment by gandm** [comment]
If you mean can I change the scope of `import WebServer`  as shown below, I probably could but I'm not sure I would want to. It seems appropriate to me for it to remain as `variable.other.readwrite.js` Other common JavaScript packages do the same. The JavaScript default package does nothing at all so normally defaults to white.

![image](https://cloud.githubusercontent.com/assets/2313237/9775275/e4cbbba6-5745-11e5-9f31-1dbdf45b3790.png)

**Comment by AlexKvazos** [comment]
Alright, I think I will get used to Tomorrow Night again haha. Thanks a lot for your help! And thank you for maintaining this package.
