### ISSUE TITLE
Flow + extending Immutable Records = Broken syntax highlighting

### ISSUE THREAD

**Issue by Daniel15** [gandm/language-babel#63]
Admittedly this is probably an edge case that might not occur a lot. Flow doesn't have first-class support for [immutable-js records](https://facebook.github.io/immutable-js/docs/#/Record), so a slightly redundant hack to make Flow understand the types of the getters is to make a class that extends the record and adds Flow types as properties. The immutable-js docs also explicitly mentions that immutable records can be extended to add custom methods.

In this snippet, all syntax highlighting from the line under `foo: Immutable.List<string>` all the way to the end of the file is messed up:
```js
class First extends Immutable.Record({
  foo: null,
}) {
  foo: string;

  getStuff(): string {
    return this.foo + '!';
  }
}

class Second extends Immutable.Record({
  foo: null,
}) {
  foo: Immutable.List<string>;

  getStuff(): string {
    return this.foo + '!';
  }
}
```

![Screenshot](https://cloud.githubusercontent.com/assets/91933/9795817/b1e2ee6e-57a7-11e5-872c-577942497c09.png)
(notice different highlighting of second `getStuff` and `return`)

Modifying the `Immutable.Record` call so it's on a single line fixes the syntax highlighting:
![Workaround 1](https://cloud.githubusercontent.com/assets/91933/9796247/0403162c-57aa-11e5-9db0-a6121415879a.png)

Splitting the creation of the record and the subclassing into two separate statements also works properly:
![Workaround 2](https://cloud.githubusercontent.com/assets/91933/9796207/c357837e-57a9-11e5-8332-9c0647295968.png)

**Comment by gandm** [comment]
Interesting. Actually the class field `foo: string` in the Class First is wrong as well. It should be detected as a flow type `support.type.builtin.primitve.flowtype` and it isn't. It is instead scoped as a`support.module.node.js` Putting the  class definition extend parameter on a single line fixes that issue as well. I'll take a look tomorrow. Thanks.

**Comment by Daniel15** [comment]
Thanks for being extremely responsive to issues, I really appreciate it :smile:
