### ISSUE TITLE
Indentation of switch/case/default

### ISSUE THREAD

**Issue by marudor** [gandm/language-babel#7]
Hey,
I really like the indentation and syntax highlighting the only thing bugging me is the non existing indentation of switch statements.
Currently this is the indentation provided:
```javascript
switch(foo) {
  case 0:
  bar = batz;
  break;
```

I would love if you could make it like this:
```javascript
switch(foo) {
  case 0:
    bar = batz;
    break;
```

Would increase readability by a lot.

**Comment by gandm** [comment]
Yes I'm aware of this. I took it out to try to match the behaviour of the default atom provided language-javascript package. They removed it [here](https://github.com/atom/language-javascript/commit/21fae9fe737c277567ab73a07baefbda1658adfa)  to avoid problems. I'll investigate what affect it has and will update this issue with any findings.

**Comment by gandm** [comment]
I've added indent to case and default switches. Seems OK but you have no automatic outdent. Hope this works for you. Fixed in 0.6.1

**Comment by marudor** [comment]
Well without automatic outdent I would prefer to have it like the default atom package.
As I think a the indent should prefer stability.
With no auto outdent you pretty much loose the ability to use the auto indent feature.

While before you could use auto indent it just messes a bit with the switch statement.
Sorry to have you add it and (may) remove it again. But if we currently have no way to make it work with outdent we should stick to the behavior we had before.

**Comment by gandm** [comment]
Ok i'll remove it and push out a patch.
