### ISSUE TITLE
Issue with syntax highlighting in ternary operator

### ISSUE THREAD

**Issue by seekshiva** [gandm/language-babel#70]
When a ternary operator is not surrounded by parentheses, it screws up the syntax highlighting of the lines below it.

Without parentheses:
![screen shot 2015-09-15 at 5 21 57 pm](https://cloud.githubusercontent.com/assets/484349/9875786/9e000762-5bce-11e5-95b8-aae332e7dc99.png)

With parentheses:
![screen shot 2015-09-15 at 5 24 51 pm](https://cloud.githubusercontent.com/assets/484349/9875805/c709c2ce-5bce-11e5-8ea4-a0ebcce4af61.png)

**Comment by gandm** [comment]
Yeah it's the biggest problem I faced when implementing facebook's flow typing. ternary operators particularly when inside  let/const/var operators are a real pain. I will take another at this and see what I can do. You don't need to surround the expression in parens but you need terminate ternaries used in expressions with  a semi-colon ;  It's not aways the case, but it's best.

e.g.
````
    const price = aaa === "total"
     ? true
     : false;
````

Anyway, I'll take another look at this issue.
