### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by josephdburdick** [gandm/language-babel#71]
Hi there, I am running this in Atom and I'm getting the following error on every save while working on a React/ES6 JS file.
 
```
RangeError: Maximum call stack size exceeded
  at RegExp.exec (native)
  at posixSplitPath (path.js:385:22)
  at Object.posix.dirname (path.js:513:16)
  at Transpiler.getLocalConfig (/Users/jb/.atom/packages/language-babel/lib/transpiler.coffee:174:35)
  at Transpiler.getLocalConfig (/Users/jb/.atom/packages/language-babel/lib/transpiler.coffee:174:15)
  at Transpiler.getLocalConfig (/Users/jb/.atom/packages/language-babel/lib/transpiler.coffee:174:15)
  at Transpiler.getLocalConfig (/Users/jb/.atom/packages/language-babel/lib/transpiler.coffee:174:15)
  at Transpiler.getLocalConfig (/Users/jb/.atom/packages/language-babel/lib/transpiler.coffee:174:15)
  at Transpiler.getLocalConfig (/Users/jb/.atom/packages/language-babel/lib/transpiler.coffee:174:15)
  at Transpiler.getLocalConfig (/Users/jb/.atom/packages/language-babel/lib/transpiler.coffee:174:15)
  at Transpiler.getLocalConfig (/Users/jb/.atom/packages/language-babel/lib/transpiler.coffee:174:15
```
The above loops for several hundred more lines.

**Comment by gandm** [comment]
Are you using Nuclide remote fs?

**Comment by gandm** [comment]
If you are using Nuclide Remote can you try updating language-babel to V0.15.0.

**Comment by josephdburdick** [comment]
@gandm I am using Atom but I am not using Nuclide.

**Comment by gandm** [comment]
Can you try v0.15.0.
 what platform are you running this on? Where is the file system you are using is it local or remote? NSF,etc.

**Comment by josephdburdick** [comment]
@gandm I'm running this on Atom 1.0.11, OSX 10.10.15, running on a local filesystem that is coordinated by Atom itself. 

My atom config.cson:
```
"*":
  core:
    themes: [
      "one-dark-ui"
      "base16-tomorrow-dark-theme"
    ]
    disabledPackages: [
      "wrap-guide"
      "language-javascript-jsx"
    ]
  "exception-reporting":
    userId: "#########"
  welcome:
    showOnStartup: false
  editor:
    invisibles: {}
    fontSize: 18
  "atom-beautify":
    _analyticsUserId: "#########"
  emmet: {}
  react:
    enabledForAllJavascriptFiles: true
  "language-babel":
    suppressSourcePathMessages: true
    suppressTranspileOnSaveMessages: true
  jshint:
    supportLintingJsx: true
  "one-dark-ui":
    layoutMode: "Compact"
  "sync-settings":
    _analyticsUserId: "##############"
    personalAccessToken: "##############"
    gistId: "###########"
    _lastBackupHash: "#############"
```

**Comment by gandm** [comment]
Um! I guess you are running the latest version of my package v0.15.0?

**Comment by gandm** [comment]
I released a version of language-babel yesterday v0.15.0 that stops recursion when an invalid path is presented. This was done to fix an Atom/Nuclide remote filesystem issue but you seem to have an almost identical problem The line numbers for the stack trace above indicates that you are running v0.14.0 - Please update the package.

The new version stops continuous recursion as exhibited above. Can you let me know what happens after v.0.15.0 is installed. 

Thanks

**Comment by gandm** [comment]
I have uploaded to github a new version that has a console.log debug output that may help me. It is not published so you will have to download it from [here](https://github.com/gandm/language-babel/archive/master.zip) and copy it to your .atom packages directory. Check the Atom Chrome Inspector console.log when you get issues.

**Comment by josephdburdick** [comment]
@gandm I have copied the contents of that download zip into the corresponding package dir in ~/.apm and so far I have no received any errors. I will reopen if I do, but until then everything looks good. Thanks!

**Comment by gandm** [comment]
Can you check the console.log output in atom when you get a chance. I suspect you still have an underlying issue but maybe not. If there are three lines of output starting LANGUAGE-BABEL it would be interesting to see them. Thanks.

**Comment by josephdburdick** [comment]
Ah, sure. It looks like this:
```
LANGUAGE-BABEL
Project Dir is /Users/jb/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015
Source File is /Applications/MAMP/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015/src/scripts/App.jsx
4transpiler.coffee:205 LANGUAGE-BABEL
Project Dir is /Users/jb/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015
Source File is /Applications/MAMP/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015/gulpfile.babel.js
index.js:229 Uncaught Error: ENOENT: no such file or directory, uv_chdir
transpiler.coffee:205 LANGUAGE-BABEL
Project Dir is /Users/jb/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015
Source File is /Applications/MAMP/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015/gulpfile.babel.js
transpiler.coffee:205 LANGUAGE-BABEL
Project Dir is /Users/jb/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015
Source File is /Applications/MAMP/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015/src/scripts/App.jsx
2transpiler.coffee:205 LANGUAGE-BABEL
Project Dir is /Users/jb/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015
Source File is /Applications/MAMP/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015/gulpfile.babel.js
2transpiler.coffee:205 LANGUAGE-BABEL
Project Dir is /Users/jb/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015
Source File is /Applications/MAMP/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015/src/scripts/App.jsx
transpiler.coffee:205 LANGUAGE-BABEL
Project Dir is /Users/jb/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015
Source File is /Applications/MAMP/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015/src/scripts/test_module.jsx
transpiler.coffee:205 LANGUAGE-BABEL
Project Dir is /Users/jb/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015
Source File is /Applications/MAMP/htdocs/Code/Github/josephdburdick/js/gulp/adoptive-2015/src/scripts/App.jsx
```

**Comment by gandm** [comment]
Yes my code just stops the unlimited recursion that is taking place.Not sure what is happening in your case. The project directory returned from atom should be the one containing the source file. But the of the project directory is  /Users/jb and the file is in /Applications/MAMP 

Where is the file in relation to the project folder you have open in Atom? Done have any symbolic links?

**Comment by josephdburdick** [comment]
I have Symbolic links, yes. My MAMP/htdocs folder is symlinked into my personal home directory for easy Finder access.

**Comment by gandm** [comment]
OK. Atom is doing something strange when giving me back the file name of the file and/or the project holding it. I'll look into this. I guess it isn't a how stopper for you at the moment. I'll reopen this issue to remind me.

**Comment by josephdburdick** [comment]
Ok, cool.

**Comment by gandm** [comment]
I'm going to close this as it isn't a problem for versions of language-babel above v0.15.0

If you are going to use `.languagebabel` config files outside the path of a sym linked source file then I've opened another issue to track that. See https://github.com/gandm/language-babel/issues/75

Thanks
