### ISSUE TITLE
Suggestion: Remove `string unquoted` classes from object keys

### ISSUE THREAD

**Issue by MethodGrab** [gandm/language-babel#73]
Object keys currently have the classes `string unquoted js` which causes them to be displayed in the same style as strings as most syntax themes don't distunguish between `quoted` and `unquoted`.
Is there a reason behind designating object keys as unquoted strings or is this a bug?

Expected:
![image](https://cloud.githubusercontent.com/assets/2421069/9900830/56a47f8c-5c5b-11e5-9f24-dd376f38e51d.png)

Actual:
![image](https://cloud.githubusercontent.com/assets/2421069/9900837/62a1d49c-5c5b-11e5-9cde-81fcdbbce673.png)

**Comment by gandm** [comment]
This grammar was originally a port of babel-sublime, although most of the code has now changed it's a hangover from that.  So below you will see strings with functions/arrows are coded as functions and keys without quotes are, as you say,  string unquoted. I'm a bit loathe to change it as people get irritated by these things. But I have to confess it irritates me the way it is. 

![image](https://cloud.githubusercontent.com/assets/2313237/9901133/60de5278-5c5d-11e5-8edc-8374f4ef9c57.png)

**Comment by MethodGrab** [comment]
Ah, fair enough then, I'll just overwrite it in my custom `styles.less`. Thanks for the explanation!
