### ISSUE TITLE
Automatically add a closing tag when opening a new tag

### ISSUE THREAD

**Issue by seekshiva** [gandm/language-babel#74]
I've gotten used to the `orktes/atom-react` package, where it automatically adds the closing tag.

Would it be possible to add that to `language-babel` as well?

**Comment by gandm** [comment]
No - Sorry. It's a reasonable amount of code he uses to do that it which doesn't seem that worthwhile to me. It would also need some additional work as it fails when using flow polymorphs e.g. `function foo<T>() {}` and also creates additional work when changing some code e.g. 
```
<middle />
```
to
```
<div>
   <middle />
<div/>
````
