### ISSUE TITLE
Comment highlighting?

### ISSUE THREAD

**Issue by AlexKvazos** [gandm/language-babel#76]
Looks like /** */ comments are getting the rest of the file highlighted as comment

![](https://i.alexkvazos.me/new_js_-__Users_alexkvazos_Documents_Projects_CubedHost_Prisma-Panel_-_Atom_1BB1016B.png)

**Comment by gandm** [comment]
Not for me!
![image](https://cloud.githubusercontent.com/assets/2313237/10010971/2d425904-60eb-11e5-97b9-71ea345f2209.png)

Are you using my grammar? Maybe some other text before the /** is causing the issue?
![image](https://cloud.githubusercontent.com/assets/2313237/10010973/3c1458d8-60eb-11e5-9dd6-e3c3b65bcd41.png)

**Comment by gandm** [comment]
I'm closing this. Please re-open if you think it is still an issue. Thanks.
