### ISSUE TITLE
ES7 static properties (Grammar)

### ISSUE THREAD

**Issue by marudor** [gandm/language-babel#79]
When using several static properties only the first static keyword gets highlighted.
If you add a , after the property it will highlight the next one correctly.
Spec allows (or even requires, i'm unsure) to omit the comma.
![2015-09-22 09_47_13-gantt jsx - c__users_entwickler_source_factro_smb factro client_src - atom](https://cloud.githubusercontent.com/assets/1881725/10013151/118d5168-610f-11e5-8be7-3d8a4e9d52f5.jpg)
![2015-09-22 09_47_36-gantt jsx - c__users_entwickler_source_factro_smb factro client_src - atom](https://cloud.githubusercontent.com/assets/1881725/10013152/1192acda-610f-11e5-8c8b-1b1b803bc5a7.jpg)

**Comment by gandm** [comment]
Yes I forgot about this and should have mentioned it in my flowtype limitations issue (yes I know its not a flow typed var). At the moment ES7 class properties should be terminated with a semi-colon or a comma 

I'll see what I can do about removing this limitation.

**Comment by gandm** [comment]
Unsure if this is daily fixed. Will review when I have some timer. Closing for now.
