### ISSUE TITLE
Suppress transpile-on-save success messages

### ISSUE THREAD

**Issue by nematode** [gandm/language-babel#8]
Love the Atom plugin. But I get success on Save so often when I'm really only interested in transpile failures. I'd love to see a preference for suppressing notification for successes.

**Comment by gandm** [comment]
Yes I agree. Will put in next release.

**Comment by gandm** [comment]
Just pushed out 0.7.0. Adds a new flag to optionally suppress success messages.

**Comment by nematode** [comment]
Sweet! Thanks.
