### ISSUE TITLE
When mixing self-terminating and closing-tag elements, tag pairing breaks

### ISSUE THREAD

**Issue by patrys** [gandm/language-babel#84]
Consider the following two examples of JSX:

```
<example>
    <foo>
        <foo/>
    </foo>
</example>
```
In this case placing the cursor anywhere between the opening and closing `foo` tag, highlights the correct pair.

```
<example>
    <foo>
        <foo a="b"/>
    </foo>
</example>
```
This example has an extra attribute (but adding a single space before the terminator is enough to trigger). Atom will incorrectly pair the self-closing element with with a closing tag of the outer `foo` element.

**Comment by gandm** [comment]
Yes it's the package https://github.com/atom/bracket-matcher doing this. It thinks it's HTML/XML and it does the matching. Not much I can do about this. Changing the middle foo to another name also fixes the problem but isn't much use to you.

**Comment by patrys** [comment]
Thanks, the relevant bug is atom/bracket-matcher#115.
