### ISSUE TITLE
Grammar issue with boolean properties in jsx

### ISSUE THREAD

**Issue by billyjanitsch** [gandm/language-babel#86]
If the final property of a non-self-closing jsx tag is a boolean property (i.e. one without an explicit value), it is not correctly parsed. For example, `otherProp` should be highlighted as `prop` is:

<img width="257" alt="screen shot 2015-09-24 at 4 23 28 pm" src="https://cloud.githubusercontent.com/assets/1158733/10085720/b6a09316-62d8-11e5-98e7-83bbd78b102f.png">

**Comment by gandm** [comment]
Ok I'll look at this. If you place a space after otherProp it works so it's probably a bad regex inj the grammar.
![image](https://cloud.githubusercontent.com/assets/2313237/10086028/10dc90de-6304-11e5-972a-15a9537b802c.png)

**Comment by billyjanitsch** [comment]
Thanks for the quick fix!
