### ISSUE TITLE
Highlighting function parameters

### ISSUE THREAD

**Issue by woutderooms** [gandm/language-babel#88]
I recently switched from Sublime to Atom, both using the Monokai syntax highlighting. In Sublime function parameters were highlighted in orange, in Atom they are plain white when using Babel ES6 Javascript syntax.

Syntax: Babel ES6 Javascript
language-babel version: 0.15.4
Atom Version: 1.0.19

<img width="469" alt="screenshot 2015-10-05 20 59 32" src="https://cloud.githubusercontent.com/assets/11516391/10290527/f68edd82-6ba4-11e5-892f-94fa796260c3.png">

**Comment by gandm** [comment]
I explained this difference in https://github.com/gandm/language-babel/issues/44
