### ISSUE TITLE
Screenimage for readme.md

### ISSUE THREAD

**Issue by gandm** [gandm/language-babel#9]
![image](https://cloud.githubusercontent.com/assets/2313237/8019642/47bcc8e0-0c50-11e5-8975-ec067315c662.png)

**Comment by gandm** [comment]
![autoclose](https://cloud.githubusercontent.com/assets/2313237/12352348/218348b6-bb7d-11e5-9245-bd0d1467d71d.gif)
![reformat](https://cloud.githubusercontent.com/assets/2313237/12352494/63f034b0-bb7e-11e5-8317-84b1db470148.gif)

**Comment by gandm** [comment]
https://cloud.githubusercontent.com/assets/2313237/12490818/7535fc50-c06f-11e5-8752-ec0878c5205c.gif

**Comment by gandm** [comment]
![indent](https://cloud.githubusercontent.com/assets/2313237/12700780/4074271e-c7e8-11e5-91d7-774f7808bc1d.gif)

**Comment by gandm** [comment]
@mxstbr I saw your twitter question 29 Sep 2016 but that user isn't me. I don't have a twitter account for this project. What do you need to know?

**Comment by mxstbr** [comment]
@gandm ohhh right. How did you find that tweet then? 😀  Can I reach you at another twitter handle or email? (mine is contact at my handle dot com in case you don't want to post yours publicly)

I want to add support for a project (which we have yet to release) to `language-babel`. (or my fork if you don't to merge upstream, which would be fine too) I've never written anything like this before, so I'm struggling a bit and wanted to ask a question how to do something. (sorry for being vague, don't want to spoil the project publicly yet)

**Comment by gandm** [comment]
@mxstbr just created an email address for this github account.   gh.gandm@gmail.com  you can reach me there.

**Comment by mxstbr** [comment]
Awesome, sent you an email!

**Comment by gandm** [comment]
@mxstbr sent a couple of emails to you.
