### ISSUE TITLE
Causes Atom app to hang when opening minified JS file

### ISSUE THREAD

**Issue by steverandy** [gandm/language-babel#90]
Atom app completely hang when opening a large minified JS file such as jquery.min.js.
When language-babel is disabled, editor opens and render the JS file quickly.

Is this a known issue? Is there a workaround or plan to fix it?

**Comment by gandm** [comment]
Yes looks like an issue that shows itself in minified files. I will investigate.

**Comment by gandm** [comment]
This should be fixed in 0.15.6.  Please note that the syntax won't be coloured correctly as Atom has a restriction on the number of tokens per line that are allowed. Not much I can do about this.

Let me know if you still have problems.

**Comment by serkanlaxy** [comment]
Hello. I hit that bug today. 

Platform: Linux x64
Atom version: 1.16.0
language-babel version: 2.59.1
