### ISSUE TITLE
Broken syntax highligting

### ISSUE THREAD

**Issue by oeb25** [gandm/language-babel#91]
I noticed when calling a function from an array, followed by a colon fx. `a ? a[]() : a`, all following syntax is behaving wierd

### Example
![Example](http://i.imgur.com/6Eg2x3z.png)

_Real world example_
```javascript
typeof obj[key] == 'function' ? obj[key]() : obj[key]
```

I'm sorry if this is too much of an edge case. Also if this is not an issue with this package I'm sorry too ;)

**Comment by gandm** [comment]
Thanks for letting me know. Hope it's fixed now.

**Comment by oeb25** [comment]
It is, thanks alot :+1:
