### ISSUE TITLE
Syntax Highlighting with Template Strings & Emoji

### ISSUE THREAD

**Issue by MethodGrab** [gandm/language-babel#92]
`language-babel` 0.15.7.
Template strings containing emoji will break the syntax highlighting. For example:
```
console.info( `----\n==> 🌎  API is running on port ${config.apiPort}` );
```

![image](https://cloud.githubusercontent.com/assets/2421069/10538236/0ab50c9e-73ef-11e5-8e6f-29af89bb53d6.png)

**Comment by gandm** [comment]
Seems to work for me albeit the \n in the template isn't highlighted which is a bug. Below is the test using Oceanic Next, which seems to corresponf to your theme.

![image](https://cloud.githubusercontent.com/assets/2313237/10541964/a1705018-740c-11e5-87db-0be5706b9fd2.png)

**Comment by MethodGrab** [comment]
Correct, it's Oceanic Next.

Hmm, the same thing seems to be happening with the default JavaScript syntax as well so I guess it's not a problem with `language-babel`, sorry about that! It also still happens when I open atom with `atom --safe` so I don't think it's a plugin/theme conflict.

I'm on OSX 10.10.4 with Atom 1.0.19 if that affects anything.

**Comment by gandm** [comment]
I tested using windows 10 and atom 1.0.19 . Also another person has reported something similar https://github.com/atom/atom/issues/9153

**Comment by MethodGrab** [comment]
Thanks! I was looking at the issues for atom/language-javascript. It's odd that it highlights correctly for you though!

**Comment by gandm** [comment]
Also, looking at the first quoted string content the semi colon terminated the statement is white where it should be blue/magenta in Oceanic Next. So it doesn't appear to be a template issue but just an issue with certain emoji's?

**Comment by MethodGrab** [comment]
Good catch, I hadn't noticed that! It seems to only happen in specific cases.
