### ISSUE TITLE
Broken syntax highlighting

### ISSUE THREAD

**Issue by oeb25** [gandm/language-babel#93]
I'm sorry, but I found another case...

This occurs when using functions in switch statements as conditions.

## Example
![Example](http://i.imgur.com/aLZkQE8.png)

**Comment by gandm** [comment]
No problem. Should be fixed now.

**Comment by oeb25** [comment]
Thanks m8!

**Comment by oeb25** [comment]
Instead of createing a new issue, I'm just going to post new errors in the comments!

I really appreciate your effort :) :+1: 

## Fat Arrows
![example](http://i.imgur.com/HranO2B.png)

In this example, which was my initial finding and harder to replicate, the following line was also blue.
![example](http://i.imgur.com/4kygjK7.png)

### BONUS!
![bonus example](http://i.imgur.com/yhjKocz.png)

---

_Thanks for making the editor a better editor_ :+1:

**Comment by gandm** [comment]
I'll take a look.

**Comment by gandm** [comment]
Should be fixed in 0.15.10
