### ISSUE TITLE
works terribly slow

### ISSUE THREAD

**Issue by prog666** [gandm/language-babel#94]
when I switch to normal javascript syntax highlighting - everything is fine, when use your extension some of cursor movements or code editing take a lot of time to process

**Comment by gandm** [comment]
You're going to have to give me something to work on! I have no problems on a file with 24,000 lines of js. Do you have a source file that is giving you the problem that I can use?

**Comment by prog666** [comment]
After some testing with disabling and enabling the plugin and changing the language of the file it started working fine. I'll test more and give you details.

**Comment by prog666** [comment]
Well, it is not every time that this lag happens, I did the same thing (like ctrl + end, ctrl + x, arrow up, ctrl + v) and it lagged only once, but delay was about 5 seconds

**Comment by gandm** [comment]
It's not a lot to go on. Ideally I need the offending source file, version of Atom, OS version & type + any other packages enabled.

**Comment by prog666** [comment]
It happens on all es6 files.
Atom v1.0.19
Arch Linux X86_64 4.2.3-1-ARCH

plugins:
- emmet
- remote-ftp
- atom-jade
- ex-mode
- highlight-selected
- imdone-atom
- jscs-fixer
- language-babel
- language-iced-coffescript
- linter
- linter-jscs
- vim-mode

Actually, i've tried to disable all except language-babel, issue didn't go away.

**Comment by gandm** [comment]
Um! I don't have Arch Linux but just tried Ubuntu navigating the graphql js files at https://github.com/graphql/graphql-js and didn't see any issues. I don't suppose there are any messages in the console. view->developer->toggle developer tools?

**Comment by prog666** [comment]
just this one
/usr/share/atom/resources/app.asar/src/deserializer-manager.js:44 No deserializer found for Object

**Comment by gandm** [comment]
I don't use the serializer so that could be another package. I just used Ubuntu on the babel source code which is pretty much all ES6 and again I saw no issues. Not sure what to suggest.

**Comment by gandm** [comment]
I noticed you have a tabs repo in you github account and I found an issue with my package parsing the browser-polyfill.js file. This is corrected in 0.15.12. You may want to try that version and see if has improved things. I'll close this issue. If you have another js file that is giving you problems then re-open this case.

**Comment by prog666** [comment]
you're awesome
