### ISSUE TITLE
toggle-quotes does not work

### ISSUE THREAD

**Issue by steverandy** [gandm/language-babel#95]
[toggle-quotes](https://github.com/atom/toggle-quotes) package does not work when the file is rendered with Babel ES6 JavaScript. It works well in other language.

**Comment by gandm** [comment]
I can see the issue but don't have time today to fix.

**Comment by gandm** [comment]
0.15.9 should fix the problem.

**Comment by steverandy** [comment]
Yes it does. Thank you very much.
