### ISSUE TITLE
Syntax Highlighting for function parameters

### ISSUE THREAD

**Issue by jryu01** [gandm/language-babel#96]
Function parameters are not highlighted as follows and are indifferent with variables:
![atom](https://cloud.githubusercontent.com/assets/3279838/10799884/8e776bea-7d85-11e5-94b9-34d0cccbc23c.png)

They are properly highlighted in default atom javascript syntax:
![default](https://cloud.githubusercontent.com/assets/3279838/10800059/64cffd10-7d86-11e5-8883-9dbb4a6f59b5.png)

And also, in Sublime Text3 with babel syntax:
![sublime](https://cloud.githubusercontent.com/assets/3279838/10799894/9a277cd2-7d85-11e5-98f7-39aedf47f842.png)

**Comment by gandm** [comment]
This is by design.

**Comment by jryu01** [comment]
Is there any specific reason to not highlight the function parameters? 
I feel it is much easier to read when they are highlighted. (Maybe because I'm used to the old style)

**Comment by gandm** [comment]
Really it was just my personal taste. 

Other people have noticed this but as I don't use Monokai themes I don't see it. e.g.

I'm using Visual Studio Dark
this is language-babel
![image](https://cloud.githubusercontent.com/assets/2313237/10801383/14ec1f62-7daf-11e5-9c1e-67ed0c988763.png)

and this is language-javascript
![image](https://cloud.githubusercontent.com/assets/2313237/10801373/03ad32ea-7daf-11e5-977f-68e292e0e6bd.png)
