### ISSUE TITLE
Supporting of new version of .babelrc

### ISSUE THREAD

**Issue by schovi** [gandm/language-babel#97]
After upgrading to Babel 6  i am getting transpile errors `Uknow options .babelrc.presets`

Using new syntax for presets like this.
```
{
  "presets": [
    "es2015"
  ]
}
```

**Comment by gandm** [comment]
Yeah. I'm looking at supporting Babel 6 soon. In the meantime you'll have to disable the transpiler options in language-babel.

**Comment by gandm** [comment]
Just published V1.0.0 which supports Babel V6. Please read the README about plugins/presets and let me know how it goes. Thanks.

**Comment by schovi** [comment]
@gandm Getting `Unknown plguin "syntax-decorators" specified in .../.babel.rc at 0`

But i have plugin installed
```
"devDependencies": {
  "babel-plugin-syntax-decorators": "^6.0.14"
}
```

**Comment by gandm** [comment]
Did you install the plugin in the atom path as per the readme? Just installing it in your package won't work as Babel looks for it in the atom paths.

**Comment by schovi** [comment]
@gandm I am not sure if I understand readme file what exactly have to install and how to write config.

I just have `~/work/amazing-app` where i have `package.json` with installed plugin and configured `.babel.rc`

Thanks for help!

**Comment by gandm** [comment]
As I mentioned in the readme how this works is in flux so I'm trying to workout the best way of supporting Babel v6. For now you need to install presets and plugins in the working directory for Atom. The working directory is shown in the package settings for language-babel - look at the field description above the plugins option to see this path. Install es2015 somewhere in the path shown.

**Comment by gandm** [comment]
@schovi language-babel V2.0.2 now suppoprt babel V6 in  a more sensible way. It will now allow multiple projects to be edited within Atom, each with differing babel-core and plugin/presetsversions loaded. I'll close this. Reopen if you still have problems. P.S. If you update language-babel ensure you stop and restart Atom. Thx
